// ================================================
// data-clasica.js — Base de datos de aeronaves
// Era clásica: pioneros, Guerra del Rif y Guerra Civil (1911-1939)
// ================================================
// CAMPO "image": Añadir la URL de la imagen aquí.
// Si está vacío, se mostrará un marcador de posición.
// Este archivo declara la variable global aircraftData; el archivo
// data-moderna.js (cargado a continuación) le añade las aeronaves
// de 1939-2026 mediante concat().

var aircraftData = [
  {
    id: 1,
    era: "clasica",
    name: "Farman MF.7",
    image: "",
    designation: "Henri Farman MF.7 Longhorn",
    year: 1911, yearEnd: 1916,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Reconocimiento / Entrenamiento",
    crew: 2,
    description: "El Farman MF.7, apodado «Longhorn» por sus característicos patines de aterrizaje extendidos, fue la primera aeronave militar adquirida por España. En 1911, el Ejército compró tres ejemplares destinados al recién creado aeródromo de Cuatro Vientos, cerca de Madrid.",
    engine: "Renault 8B V8, 70 cv",
    wingspan: "15,90 m", length: "11,45 m", height: "3,40 m",
    emptyWeight: "480 kg", maxWeight: "700 kg",
    maxSpeed: "95 km/h", range: "250 km", ceiling: "3.800 m",
    armament: "Ninguno fijo; el observador podía portar armas ligeras",
    variants: [
      { name: "MF.7", engine: "Renault 8B V8, 70 cv", maxSpeed: "95 km/h", emptyWeight: "480 kg", maxWeight: "700 kg", armament: "Ninguno fijo; el observador podía portar armas ligeras", desc: "Versión estándar con motor Renault 8B de 70 cv y patines curvados característicos" },
      { name: "MF.7bis", engine: "Renault 8B V8, 70 cv (misma planta motriz)", maxSpeed: "92 km/h", emptyWeight: "515 kg", maxWeight: "725 kg", armament: "Ninguno fijo; el observador podía portar armas ligeras", desc: "Variante mejorada con alerones modificados, tren de aterrizaje reforzado y refinamientos aerodinámicos menores" }
    ],
    history: "Los MF.7 de Cuatro Vientos fueron los caballos de batalla de la instrucción inicial. Aunque obsoletos al inicio de las operaciones en Marruecos, sirvieron como plataforma esencial para la primera generación de pilotos militares españoles."
  },
  {
    id: 3,
    era: "clasica",
    name: "Farman MF.11",
    image: "",
    designation: "Henry Farman F.11 / MF.11bis",
    year: 1913, yearEnd: 1918,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Reconocimiento / Bombardeo ligero",
    crew: 2,
    description: "El Farman MF.11 fue la aeronave de combate principal durante las primeras operaciones militares españolas en Marruecos. Biplano propulsor con la barquilla montada delante del motor, ofrecía al observador un excelente campo de tiro frontal.",
    engine: "Renault 8Bb V8, 80 cv (posteriormente 8Bd de 100 cv)",
    wingspan: "16,15 m", length: "9,45 m", height: "3,20 m",
    emptyWeight: "530 kg", maxWeight: "830 kg",
    maxSpeed: "105 km/h", range: "300 km", ceiling: "4.000 m",
    armament: "1 × Hotchkiss M1914 de 7 mm en montaje flexible (observador); hasta 100 kg de bombas",
    variants: [
      { name: "MF.11 A2", engine: "Renault 8Bb V8, 80 cv", maxSpeed: "100 km/h", emptyWeight: "530 kg", maxWeight: "830 kg", armament: "1 × Hotchkiss M1914 de 7 mm en montaje flexible (observador)", desc: "Variante biplaza de reconocimiento con Renault de 80 cv, modelo estándar utilizado en Marruecos" },
      { name: "MF.11bis", engine: "Renault 8Bd V8, 100 cv", maxSpeed: "112 km/h", emptyWeight: "565 kg", maxWeight: "865 kg", armament: "1 × Hotchkiss M1914 de 7 mm en montaje flexible (observador)", desc: "Versión mejorada con Renault 8Bd de 100 cv, superficies de cola ampliadas y estructura reforzada" },
      { name: "MF.11 Bn2", engine: "Renault 8Bd V8, 100 cv", maxSpeed: "105 km/h", emptyWeight: "600 kg", maxWeight: "900 kg", armament: "1 × Hotchkiss de 7 mm; hasta 100 kg de bombas en soportes nocturnos y depósito auxiliar", desc: "Variante de bombardeo nocturno con soportes de bombas y depósitos auxiliares de combustible" }
    ],
    history: "El MF.11 fue la espina dorsal de la escuadrilla expedicionaria en Marruecos desde 1913. Realizó reconocimiento sobre el Rif, dirigió el tiro artillero y llevó a cabo los primeros bombardeos españoles con granadas improvisadas."
  },
  {
    id: 4,
    era: "clasica",
    name: "Caudron G.3",
    image: "img/CaudronG3.webp",
    designation: "Caudron G.3",
    year: 1919, yearEnd: 1924,
    branch: "ejercito",
    type: "entrenamiento",
    typeLabel: "Entrenamiento elemental",
    crew: 2,
    description: "El Caudron G.3, diseño francés ya veterano de la Guerra Europea (2.450 ejemplares fabricados, vendidos después a bajo precio a varias naciones), llegó a la aviación militar española como avión de escuela elemental, no como aparato de combate: entró en servicio en mayo-junio de 1919 en Getafe, bastante después de lo que se suele asumir.",
    engine: "Le Rhône 9C rotativo, 80 cv",
    wingspan: "13,22 m", length: "6,86 m", height: "2,55 m",
    emptyWeight: "445 kg", maxWeight: "734 kg",
    maxSpeed: "106 km/h", range: "N/D (autonomía 4 h)", ceiling: "3.000 m (techo práctico)",
    armament: "Ninguno",
    variants: [
      { name: "G.3 (escuela elemental)", engine: "Le Rhône 9C, 80 cv", maxSpeed: "106 km/h", emptyWeight: "445 kg", maxWeight: "734 kg", armament: "Ninguno", desc: "Único tipo documentado en servicio español; no hay constancia de subvariantes A2/D2/E2 diferenciadas para España, a diferencia del uso general del tipo durante la Guerra Europea. Subida a 2.000 m en 20 minutos." }
    ],
    history: "Fue material básico de las escuelas de Getafe, Sevilla y Los Alcázares desde el curso de 1920 (\"promoción de los 100\"), con 12 ejemplares en inventario según el informe del coronel Soriano de septiembre de 1920, que ya recomendaba sustituirlo por el Avro 504K. Fue desapareciendo paulatinamente, sin referencias en el Servicio a partir de 1924. Recordado como avión fácil mas de bajas actuaciones, con el arcaico mando lateral por alabeo del ala superior. (Fuente: J.M. Salas Larrazábal, «Aviones militares españoles 1911-1936».)"
  },
  {
    id: 5,
    era: "clasica",
    name: "Farman F.40",
    image: "",
    designation: "Farman F.40 / F.41 / F.46",
    year: 1915, yearEnd: 1919,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Reconocimiento / Bombardeo",
    crew: 2,
    description: "El Farman F.40 supuso una mejora significativa respecto al MF.11, con un motor Renault de 130 cv y aerodinámica refinada. Biplano propulsor capaz de transportar una carga bélica considerable, se convirtió en uno de los principales tipos de combate durante el período central de la guerra del Rif.",
    engine: "Renault 8Fb V8, 130 cv",
    wingspan: "18,20 m", length: "9,60 m", height: "3,30 m",
    emptyWeight: "700 kg", maxWeight: "1.100 kg",
    maxSpeed: "128 km/h", range: "400 km", ceiling: "4.500 m",
    armament: "1 × Hotchkiss de 7 mm en montaje flexible; hasta 200 kg de bombas",
    variants: [
      { name: "F.40", engine: "Renault 8Fb V8, 130 cv", maxSpeed: "128 km/h", emptyWeight: "700 kg", maxWeight: "1.100 kg", armament: "1 × Hotchkiss de 7 mm en montaje flexible; hasta 200 kg de bombas", desc: "Versión estándar biplaza de reconocimiento/bombardeo con Renault 8Fb de 130 cv" },
      { name: "F.41", engine: "Renault 8Fb V8, 130 cv", maxSpeed: "132 km/h", emptyWeight: "715 kg", maxWeight: "1.120 kg", armament: "1 × Hotchkiss de 7 mm; mecanismo de liberación de bombas mejorado, hasta 200 kg", desc: "Variante con barquilla revisada, mejor aerodinámica y mecanismo de liberación de bombas mejorado" },
      { name: "F.46", engine: "Renault 8Fb V8, 130 cv", maxSpeed: "125 km/h", emptyWeight: "680 kg", maxWeight: "1.050 kg", armament: "Ninguno; equipo de bombardeo retirado, doble mando para instrucción", desc: "Conversión a entrenador con doble mando y equipo de bombardeo retirado" }
    ],
    history: "El F.40 proporcionó por primera vez a las tripulaciones españolas una capacidad ofensiva real. Desde los aeródromos marroquíes, realizó bombardeos sistemáticos sobre campamentos y posiciones rifeñas."
  },
  {
    id: 6,
    era: "clasica",
    name: "Caudron G.4",
    image: "",
    designation: "Caudron G.4 A2 / B2 / E2",
    year: 1916, yearEnd: 1919,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Bimotor de Bombardeo / Reconocimiento",
    crew: 3,
    description: "El Caudron G.4 fue el primer bimotor militar español y representó un salto cualitativo importante. Basado en el exitoso G.3 pero ampliado con dos motores entre los dobles botalones, podía transportar una carga de bombas considerable a grandes distancias.",
    engine: "2 × Le Rhône 9C 9 cilindros rotativo, 80 cv cada uno o 2 × Anzani 10 cilindros radial, 100 cv cada uno",
    wingspan: "17,00 m", length: "7,25 m", height: "2,60 m",
    emptyWeight: "780 kg", maxWeight: "1.250 kg",
    maxSpeed: "121 km/h", range: "360 km", ceiling: "4.300 m",
    armament: "1-2 × Hotchkiss de 7 mm en montajes flexibles; hasta 300 kg de bombas",
    variants: [
      { name: "G.4 A2", engine: "2 × Le Rhône 9C, 80 cv cada uno", maxSpeed: "121 km/h", emptyWeight: "780 kg", maxWeight: "1.250 kg", armament: "1 × Hotchkiss de 7 mm; equipo fotográfico y combustible extra", desc: "Variante triplaza de reconocimiento de largo alcance con equipo fotográfico y combustible extra" },
      { name: "G.4 B2", engine: "2 × Anzani 10 cilindros radial, 100 cv cada uno", maxSpeed: "130 km/h", emptyWeight: "830 kg", maxWeight: "1.320 kg", armament: "1-2 × Hotchkiss de 7 mm; hasta 300 kg de bombas en soportes subalares", desc: "Variante triplaza de bombardeo con soportes subalares y posición de bombardero en barquilla delantera" },
      { name: "G.4 E2", engine: "2 × Le Rhône 9C, 80 cv cada uno", maxSpeed: "115 km/h", emptyWeight: "760 kg", maxWeight: "1.200 kg", armament: "Ninguno; doble mando para conversión operativa", desc: "Entrenador bimotor con doble mando para conversión operativa" }
    ],
    history: "La llegada del G.4 dotó a la aviación española de una fuerza de bombardeo genuina. Sus motores dobles proporcionaban redundancia sobre el terreno hostil marroquí, aunque los motores rotativos requerían mantenimiento frecuente."
  },
  {
    id: 7,
    era: "clasica",
    name: "Avro 504K",
    image: "",
    designation: "Avro 504K",
    year: 1919, yearEnd: 1934,
    branch: "ejercito",
    type: "entrenamiento",
    typeLabel: "Entrenamiento elemental",
    crew: 2,
    description: "El Avro 504K, con bancada adaptable a distintos motores rotativos, fue el entrenador que \"desagarrotó\" a la aviación militar española tras el aislamiento de la Guerra Europea, introduciendo el método de instrucción Smith-Barry (con doble mando y tubo de comunicación acústica «Gosport» entre profesor y alumno), muy superior al rudimentario sistema heredado de la «era del Farman».",
    engine: "Le Rhône 9C rotativo, 80 cv; también Gnôme Monosoupape de 100 cv o Le Rhône 9J de 110 cv",
    wingspan: "10,98 m", length: "8,97 m", height: "3,18 m",
    emptyWeight: "559 kg", maxWeight: "823 kg",
    maxSpeed: "153 km/h a nivel del mar (con Le Rhône 9J)", range: "N/D", ceiling: "unos 4.000 m",
    armament: "Ninguno",
    variants: [
      { name: "Avro 504K (motor 80 cv)", engine: "Le Rhône 9C, 80 cv", desc: "Motorización original de los primeros 32 ejemplares del Servicio." },
      { name: "Avro 504K (motor 110 cv)", engine: "Le Rhône 9J, 110 cv", maxSpeed: "153 km/h a nivel del mar; 136 km/h a 3.000 m", desc: "Reequipados a partir de 1923 aproximadamente; datos de actuaciones documentados con esta motorización." }
    ],
    history: "Su origen fue el «El Estanco» (núm. 1), regalado por el Rey de Inglaterra, y otro incautado en Ciudad Real. En septiembre de 1920 el Servicio tenía 32 unidades, cifra que llegó a no menos de 48. Fue el material dominante en las escuelas elementales de Getafe y Sevilla hasta su supresión en 1924, y en la Escuela de Pilotaje de Alcalá al menos hasta 1934. También se usó por contrato en escuelas civiles (CEA de Albacete, Loring de Carabanchel Alto) para formar pilotos de tropa. (Fuente: J.M. Salas Larrazábal, «Aviones militares españoles 1911-1936».)"
  },
  {
    id: 8,
    era: "clasica",
    name: "FBA Type H",
    image: "",
    designation: "FBA Type H / Type C",
    year: 1917, yearEnd: 1925,
    branch: "armada",
    type: "hidroavion",
    typeLabel: "Hidroavión Naval",
    crew: 2,
    description: "El FBA Type H fue la primera aeronave operada por la recién creada Aeronáutica Naval en 1917. Estos compactos hidrocanoas propulsores fueron adquiridos para patrulla costera y reconocimiento desde bases navales españolas.",
    engine: "Hispano-Suiza 8Aa V8, 150 cv o 8Ab, 180 cv",
    wingspan: "13,30 m", length: "9,10 m", height: "3,20 m",
    emptyWeight: "780 kg", maxWeight: "1.150 kg",
    maxSpeed: "140 km/h", range: "450 km", ceiling: "4.200 m",
    armament: "1 × Vickers o Lewis de 7 mm en montaje flexible; hasta 100 kg de bombas o cargas de profundidad",
    variants: [
      { name: "Type A", engine: "Hispano-Suiza 8Aa V8, 150 cv", maxSpeed: "135 km/h", emptyWeight: "780 kg", maxWeight: "1.150 kg", armament: "1 × Lewis de 7 mm en montaje flexible", desc: "Modelo de producción inicial con Hispano-Suiza 8Aa de 150 cv para patrulla costera" },
      { name: "Type H", engine: "Hispano-Suiza 8Ab V8, 180 cv", maxSpeed: "140 km/h", emptyWeight: "810 kg", maxWeight: "1.190 kg", armament: "1 × Vickers o Lewis de 7 mm; hasta 100 kg de bombas o cargas de profundidad, depósitos ampliados", desc: "Variante definitiva en servicio español con depósitos ampliados y equipamiento tropical para Marruecos" }
    ],
    history: "Los hidroaviones FBA fueron las aeronaves fundacionales de la aviación naval española. Operaron desde bases costeras realizando patrullas antisubmarinas, escolta de convoyes y reconocimiento marítimo."
  },
  {
    id: 9,
    era: "clasica",
    name: "SPAD VII",
    image: "",
    designation: "Société Pour L'Aviation et ses Dérivés SPAD S.VII",
    year: 1917, yearEnd: 1924,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza monoplaza",
    crew: 1,
    description: "El SPAD VII fue el primer avión de caza verdadero de España, dotando a las escuadrillas de capacidad de combate moderna. Propulsado por el excelente motor V8 Hispano-Suiza, combinaba construcción robusta con buena velocidad y prestaciones en picado.",
    engine: "Hispano-Suiza 8Aa V8, 150 cv (posteriormente 8Ac, 180 cv)",
    wingspan: "7,82 m", length: "6,08 m", height: "2,20 m",
    emptyWeight: "500 kg", maxWeight: "720 kg",
    maxSpeed: "192 km/h", range: "360 km", ceiling: "5.800 m",
    armament: "1 × Vickers de 7,7 mm sincronizada a través del arco de la hélice",
    variants: [
      { name: "SPAD VII (150 cv)", engine: "Hispano-Suiza 8Aa V8, 150 cv", maxSpeed: "180 km/h", emptyWeight: "500 kg", maxWeight: "720 kg", armament: "1 × Vickers de 7,7 mm sincronizada", desc: "Versión inicial con Hispano-Suiza 8Aa de 150 cv, estándar en las primeras entregas españolas" },
      { name: "SPAD VII (180 cv)", engine: "Hispano-Suiza 8Ac V8, 180 cv", maxSpeed: "192 km/h", emptyWeight: "510 kg", maxWeight: "735 kg", armament: "1 × Vickers de 7,7 mm sincronizada; mejor régimen de trepada y techo", desc: "Versión mejorada con Hispano-Suiza 8Ac de 180 cv, mejor régimen de trepada y techo" }
    ],
    history: "El SPAD VII transformó la capacidad de caza española. En Marruecos demostró su valor en misiones de ametrallamiento y reconocimiento armado. Sus motores Hispano-Suiza facilitaban el mantenimiento al ser de origen español."
  },
  {
    id: 10,
    era: "clasica",
    name: "Hanriot HD.1",
    image: "",
    designation: "Hanriot HD.1 / HD.2",
    year: 1918, yearEnd: 1928,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza monoplaza",
    crew: 1,
    description: "El Hanriot HD.1 fue un caza ágil y maniobrable que complementó a los SPAD VII en servicio español. Algunos pilotos lo preferían por su superior maniobrabilidad y manejo más ligero en altitud. Su motor rotativo Le Rhône le confería una respuesta característica.",
    engine: "Le Rhône 9J 9 cilindros rotativo, 110 cv",
    wingspan: "8,70 m", length: "5,85 m", height: "2,94 m",
    emptyWeight: "415 kg", maxWeight: "620 kg",
    maxSpeed: "183 km/h", range: "300 km", ceiling: "6.000 m",
    armament: "1 × Vickers de 7,7 mm sincronizada (algunos ejemplares españoles con 2 × Vickers)",
    variants: [
      { name: "HD.1", engine: "Le Rhône 9J rotativo, 110 cv", maxSpeed: "183 km/h", emptyWeight: "415 kg", maxWeight: "620 kg", armament: "1 × Vickers de 7,7 mm sincronizada (algunos ejemplares con 2)", desc: "Caza terrestre estándar con Le Rhône 9J de 110 cv y una Vickers" },
      { name: "HD.2", engine: "Le Rhône 9J rotativo, 110 cv", maxSpeed: "165 km/h", emptyWeight: "480 kg", maxWeight: "700 kg", armament: "1 × Vickers de 7,7 mm; fuselaje reforzado y flotadores para uso naval", desc: "Conversión a caza con flotadores para uso naval con pontones y fuselaje reforzado" }
    ],
    history: "Los HD.1 españoles sirvieron principalmente en el teatro marroquí, donde su maniobrabilidad era valiosa para misiones de ataque a baja cota. El tipo continuó en servicio hasta bien entrada la década de 1920."
  },
  {
    id: 11,
    era: "clasica",
    name: "Breguet 14",
    image: "",
    designation: "Breguet 14 A.2 / B.2",
    year: 1919, yearEnd: 1931,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Reconocimiento / Bombardeo ligero",
    crew: 2,
    description: "El Breguet 14, de estructura principalmente metálica (fuselaje de tubo de aluminio, alas con largueros de aluminio), fue el avión de combate más importante de la aviación militar española en Marruecos durante los años veinte, con unos 140 ejemplares en servicio a lo largo de su vida operativa, en tres motorizaciones distintas.",
    engine: "Renault 12F, 300 cv; Fiat A.12bis, 300 cv; o (reconversión posterior) Rolls-Royce Eagle VIII, 360 cv",
    wingspan: "14,364 m (ala superior) / 12,400 m (ala inferior)", length: "9 m", height: "3,3 m",
    emptyWeight: "1.070 kg", maxWeight: "1.600 kg",
    maxSpeed: "192 km/h a nivel del mar (motor Renault)", range: "N/D (autonomía 4 h 30 min)", ceiling: "6.000 m",
    armament: "2 ametralladoras gemelas de observador; 12 bombas de 11 kg",
    variants: [
      { name: "Br.14 (motor Renault 12F)", engine: "Renault 12F, 300 cv", maxSpeed: "192 km/h a nivel del mar", desc: "Motorización original y preferida por su mayor fiabilidad; primer ejemplar regalado por Francia llegó a Cuatro Vientos en julio de 1919." },
      { name: "Br.14 (motor Fiat A.12bis)", engine: "Fiat A.12bis, 300 cv", maxSpeed: "similar al Renault, actuaciones parecidas", armament: "Igual armamento; tubos de escape situados por el lado derecho (frente a la disposición del Renault)", desc: "Adquiridos en 1921 por razones económicas; equiparon los Grupos de África de Tetuán y Larache. Los motores Fiat no tenían la fiabilidad de los Rolls-Royce Eagle." },
      { name: "Br.14 (reconversión Rolls-Royce Eagle VIII)", engine: "Rolls-Royce Eagle VIII, 360 cv", desc: "Reconversión realizada por el Parque de Sevilla desde 1927 para alargar la vida útil de la célula, con alerones modificados de cuernos de equilibrado y hélices de cuatro palas; participó en las últimas operaciones de la campaña de Marruecos y sirvió en la escuadrilla del Sahara (1928-1931)." }
    ],
    history: "Adquirido a partir de 1919 tras la donación francesa del primer ejemplar, prestó largo y duro servicio en Marruecos (Tetuán, Larache, «La Balumba» en Melilla), siendo preferido por muchos al De Havilland DH.4. Participó en el desembarco de Alhucemas y en las operaciones finales de la Guerra del Rif. Un desarrollo español tardío se equipó con motor Hispano-Suiza 8F de 300 cv. Producción francesa total: unos 8.000 ejemplares (2.450 corresponden al Caudron G.3, no confundir). (Fuente: J.M. Salas Larrazábal, «Aviones militares españoles 1911-1936».)"
  },
  {
    id: 12,
    era: "clasica",
    name: "De Havilland DH.9",
    image: "",
    designation: "De Havilland DH.9 (motor Hispano-Suiza)",
    year: 1919, yearEnd: 1938,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Reconocimiento y bombardeo ligero / Escuela de transformación",
    crew: 2,
    description: "A diferencia del DH.9 británico original (motor Siddeley Puma), la práctica totalidad de los DH.9 españoles llevaban motor Hispano-Suiza: unos 120 ejemplares fabricados bajo licencia por «La Hispano» en Guadalajara, más algunos importados con el mismo motor. Considerado poco adecuado para el durísimo empleo en Marruecos, prestó en cambio un servicio inapreciable como avión de la Escuela de Transformación durante toda una década.",
    engine: "Hispano-Suiza 8Fb, 300 cv",
    wingspan: "12,93 m", length: "aprox. 9,30 m", height: "3,41 m",
    emptyWeight: "unos 1.000 kg", maxWeight: "unos 1.650 kg",
    maxSpeed: "unos 190 km/h", range: "N/D", ceiling: "N/D",
    armament: "1 (o 2) ametralladoras de observador; probablemente 12 bombas de 10-12 kg",
    variants: [
      { name: "DH.9 (motor Hispano-Suiza 8Fb)", engine: "Hispano-Suiza 8Fb, 300 cv", maxSpeed: "unos 190 km/h", desc: "Motorización estándar española, distinta de la Siddeley Puma original británica; considerada 'maravilla mecánica' por el coronel Soriano en 1920 pero de fiabilidad discutida (aunque pilotos con experiencia atribuían las averías a fallos de instalación, no al motor)." },
      { name: "DH.9A (motor Napier Lion)", engine: "Napier Lion, 450 cv", desc: "Versión distinta y posterior, con motor Napier Lion de 450 cv; equipó una escuadrilla separada del Grupo núm. 3/4 de África hacia 1925-1927, junto a los DH.4 y Potez 15. Sin datos técnicos completos disponibles en esta fuente." }
    ],
    history: "El primer DH.9 con motor Hispano llegó hacia 1919-1920; en el raid Madrid-Lisboa de febrero de 1920 fue el único de los cuatro biplazas participantes con autonomía suficiente para volar sin escala. El coronel Soriano consideraba el motor Hispano poco seguro para volar «por encima de un enemigo como el Moro»; por ello el DH.9 apenas se envió a Marruecos (solo una escuadrilla, 1926-1927), sirviendo principalmente en las escuelas peninsulares y, sobre todo, en la Escuela de Clasificación o Transformación de Cuatro Vientos (después Guadalajara) desde su origen hasta 1927 y años después. Siguió en uso durante la Guerra Civil por ambos bandos (designación republicana «RH», nacional tipo 34), de baja hacia 1938. (Fuente: J.M. Salas Larrazábal, «Aviones militares españoles 1911-1936».)"
  },
  {
    id: 202,
    era: "clasica",
    name: "De Havilland DH.4",
    image: "",
    designation: "De Havilland DH.4 (motor Rolls-Royce)",
    year: 1919, yearEnd: 1927,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Reconocimiento y bombardeo ligero",
    crew: 2,
    description: "El De Havilland DH.4, con puesto de piloto bajo la cabaña y observador separado por el depósito de gasolina, fue el aparato de combate más fiable y estimado de la aviación militar española durante la fase decisiva de la Guerra del Rif, gracias sobre todo a la robustez de su motor Rolls-Royce, muy superior a la del Hispano-Suiza del DH.9. Formó el núcleo del célebre «Grupo Rolls».",
    engine: "Rolls-Royce 275 HP (Eagle VI o VII), 322 cv; posiblemente algunos con Eagle VIII de 360 cv",
    wingspan: "12,93 m", length: "9,21 m", height: "3,09 m",
    emptyWeight: "unos 1.070 kg", maxWeight: "unos 1.780 kg",
    maxSpeed: "188 km/h a 2.000 m (Eagle III); hasta 220 km/h con Eagle VIII", range: "N/D (autonomía 3:30-3:45 h)", ceiling: "4.880 m",
    armament: "2 ametralladoras gemelas Darne de observador; 12 bombas de 10-12 kg",
    variants: [
      { name: "DH.4 (Eagle VI/VII, «Havilland-Rolls»)", engine: "Rolls-Royce Eagle VI/VII, 322 cv", desc: "Motorización estándar de casi toda la flota española, conocida como «Havilland-Rolls» para distinguirla del DH.9 («Havilland-Hispano»)." }
    ],
    history: "Los primeros DH.4 llegaron en 1919; tras el desastre de Annual (julio 1921) se adquirieron 42 DH.4/DH.9 adicionales, la mayoría DH.4, muchos donados por provincias españolas (luciendo sus nombres: «Ávila», «Cartagena»...). Formó la célebre escuadrilla germen del «Grupo Rolls» en Melilla, mandado sucesivamente por Delgado Brackenbury, J. González Gallarza y el legendario Pepe Carrillo (caído en combate el 28 de noviembre de 1924 volando en solitario). Participó en las jornadas de Tizi Assa (1923) y en el desembarco de Alhucemas (1925). Los DH.4 desaparecieron del servicio al terminar la campaña de Marruecos en julio de 1927. (Fuente: J.M. Salas Larrazábal, «Aviones militares españoles 1911-1936».)"
  },
  {
    id: 203,
    era: "clasica",
    name: "De Havilland DH.6",
    image: "",
    designation: "De Havilland DH.6 («Havilland-Escuela»)",
    year: 1919, yearEnd: 1931,
    branch: "ejercito",
    type: "entrenamiento",
    typeLabel: "Entrenamiento elemental",
    crew: 2,
    description: "Apodado en España «Havilland-Escuela», el DH.6 fue un entrenador elemental de diseño deliberadamente sencillo y barato (con alas rectangulares que, según se decía en su Gran Bretaña de origen, «se fabricaban por millas y se cortaban por yardas»). De bajas prestaciones, se fabricó en dos motorizaciones muy distintas según el fabricante.",
    engine: "Hispano-Suiza 8A, 140 cv (importados, designados E.140) o Hispano-Suiza 8Ab, 180 cv (fabricados por La Hispano de Guadalajara, designados E.180)",
    wingspan: "10,95 m", length: "8,32 m", height: "3,29 m",
    emptyWeight: "665 kg (motor RAF 1a de referencia)", maxWeight: "920 kg",
    maxSpeed: "106 km/h a nivel del mar (motor RAF 1a de 90 cv, como referencia)", range: "N/D", ceiling: "N/D",
    armament: "Ninguno",
    variants: [
      { name: "DH.6 / E.140 (importado)", engine: "Hispano-Suiza 8A, 140 cv", desc: "Unos 20 ejemplares importados de Gran Bretaña con radiador frontal, en inventario desde 1919-1920; 18 en septiembre de 1920, ya recomendados para extinguir." },
      { name: "DH.6 / E.180 (La Hispano, Guadalajara)", engine: "Hispano-Suiza 8Ab, 180 cv", desc: "Unos 25 ejemplares fabricados en España desde hacia 1924-1925, con puestos independientes, radiadores Lamblin entre las patas del tren y timón con cuerno de equilibrado; usado sobre todo por el Grupo núm. 31 (segundo de reconocimiento de Madrid) como aparato interino." }
    ],
    history: "No se empleó, contra lo previsto, como escuela elemental estándar (ese papel lo cumplió el Avro 504K), sino como aparato de perfeccionamiento y, sobre todo, para remolcar mangas de tiro al blanco en la Escuela de Tiro y Bombardeo de Los Alcázares desde 1921. Dado de baja hacia 1931, aunque algunos ejemplares siguieron volando cedidos a aeroclubes. (Fuente: J.M. Salas Larrazábal, «Aviones militares españoles 1911-1936».)"
  },
  {
    id: 13,
    era: "clasica",
    name: "Bristol F.2B Fighter",
    image: "",
    designation: "Bristol F.2B Fighter",
    year: 1920, yearEnd: 1931,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Caza / Reconocimiento",
    crew: 2,
    description: "El Bristol F.2B Fighter fue uno de los mejores biplazas de la Primera Guerra Mundial y sirvió en España como avión de caza y reconocimiento. Su combinación de velocidad, maniobrabilidad y armamento defensivo lo hacía formidable incluso frente a cazas monoplazas.",
    engine: "Rolls-Royce Falcon III V12, 275 cv",
    wingspan: "11,96 m", length: "7,87 m", height: "2,97 m",
    emptyWeight: "975 kg", maxWeight: "1.475 kg",
    maxSpeed: "198 km/h", range: "460 km", ceiling: "5.945 m",
    armament: "1 × Vickers de 7,7 mm fija sincronizada; 1-2 × Lewis de 7,7 mm en montaje Scarff (observador)",
    variants: [
      { name: "F.2B (Falcon III)", engine: "Rolls-Royce Falcon III V12, 275 cv", maxSpeed: "198 km/h", emptyWeight: "975 kg", maxWeight: "1.475 kg", armament: "1 × Vickers fija sincronizada; 1-2 × Lewis en montaje Scarff (observador)", desc: "Variante estándar con Rolls-Royce Falcon III de 275 cv, principal versión en servicio español Variante única en servicio español; no se documentan otras plantas motrices en España." }
    ],
    history: "Los Bristol Fighter españoles operaron en Marruecos como escolta de bombardeo y reconocimiento armado. Su versatilidad los mantuvo en servicio hasta bien entrada la década de 1930."
  },
  {
    id: 14,
    era: "clasica",
    name: "Nieuport 24/27",
    image: "",
    designation: "Nieuport 24 / 24bis / 27",
    year: 1921, yearEnd: 1930,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza monoplaza",
    crew: 1,
    description: "Los Nieuport 24 y 27 fueron los últimos cazas de la línea Nieuport en servir con la aviación militar española. Evolución de los exitosos Nieuport 11 y 17, ofrecían mejor rendimiento que los SPAD VII en maniobrabilidad a baja cota, aunque eran más frágiles.",
    engine: "Le Rhône 9Jb 9 cilindros rotativo, 120 cv (Ni.24) o Gnome Monosoupape 9N, 150 cv (Ni.27)",
    wingspan: "8,21 m", length: "5,78 m", height: "2,40 m",
    emptyWeight: "385 kg", maxWeight: "580 kg",
    maxSpeed: "185 km/h", range: "300 km", ceiling: "5.500 m",
    armament: "1 × Vickers de 7,7 mm sincronizada o 2 × Lewis sobre el ala superior (algunos Ni.24)",
    variants: [
      { name: "Nieuport 24", engine: "Le Rhône 9Jb rotativo, 120 cv", maxSpeed: "180 km/h", emptyWeight: "385 kg", maxWeight: "580 kg", armament: "1 × Vickers de 7,7 mm sincronizada (algunos con 2 × Lewis sobre el ala superior)", desc: "Caza con Le Rhône de 120 cv y cola rediseñada, algunos con armamento sobre el ala" },
      { name: "Nieuport 27", engine: "Gnome Monosoupape 9N rotativo, 150 cv", maxSpeed: "185 km/h", emptyWeight: "400 kg", maxWeight: "595 kg", armament: "1 × Vickers de 7,7 mm sincronizada; tren de aterrizaje revisado", desc: "Versión final de producción con Gnome Monosoupape de 150 cv y tren de aterrizaje revisado" }
    ],
    history: "Los Nieuport 24/27 sirvieron como cazas de primera línea en Marruecos, complementando y posteriormente reemplazando a los SPAD VII y Hanriot HD.1 más antiguos."
  },
  {
    id: 15,
    era: "clasica",
    name: "Breguet XIX",
    image: "",
    designation: "Breguet XIX A2 / B2 / G.R. (Grand Raid)",
    year: 1922, yearEnd: 1937,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Bombardeo / Reconocimiento",
    crew: 2,
    description: "El Breguet XIX fue el avión estándar de la aviación militar española durante más de una década. Versátil, robusto y fiable, sirvió como bombardero, avión de reconocimiento y plataforma para récords de distancia. Construido bajo licencia por CASA en España.",
    engine: "Lorraine-Dietrich 12Db V12, 400 cv o Hispano-Suiza 12Hb V12, 500 cv",
    wingspan: "14,83 m", length: "9,51 m", height: "3,69 m",
    emptyWeight: "1.370 kg", maxWeight: "2.450 kg",
    maxSpeed: "230 km/h", range: "800 km", ceiling: "7.000 m",
    armament: "1 × Vickers de 7,7 mm fija; 2 × Lewis de 7,7 mm en torreta; hasta 500 kg de bombas",
    variants: [
      { name: "XIX A2", engine: "Lorraine-Dietrich 12Db V12, 400 cv", maxSpeed: "215 km/h", emptyWeight: "1.370 kg", maxWeight: "2.380 kg", armament: "1 × Vickers fija; 2 × Lewis en torreta; equipo fotográfico", desc: "Variante de reconocimiento con equipo fotográfico y motores Lorraine de 400 cv" },
      { name: "XIX B2", engine: "Hispano-Suiza 12Hb V12, 500 cv", maxSpeed: "230 km/h", emptyWeight: "1.420 kg", maxWeight: "2.450 kg", armament: "1 × Vickers fija; 2 × Lewis en torreta; hasta 500 kg de bombas internas y externas", desc: "Variante de bombardeo con soportes de bombas internos y externos, armamento completo" },
      { name: "XIX G.R. (Grand Raid)", engine: "Hispano-Suiza 12Lbr V12, 650 cv", maxSpeed: "235 km/h", emptyWeight: "1.900 kg", maxWeight: "3.700 kg", armament: "Desarmado en configuración de récord; depósitos ampliados a más de 5.000 litros (versión «Cuatro Vientos»/Superbidón)", desc: "Versión de largo alcance para récords de distancia con depósitos ampliados" },
      { name: "XIX hidroavión", engine: "Hispano-Suiza 12Hb V12, 500 cv", maxSpeed: "205 km/h", emptyWeight: "1.650 kg", maxWeight: "2.700 kg", armament: "1 × Vickers fija; 2 × Lewis en torreta; conversión con flotadores para la Aeronáutica Naval", desc: "Conversión con flotadores para la Aeronáutica Naval" }
    ],
    history: "El Breguet XIX fue la espina dorsal de la aviación militar española desde 1922 hasta la Guerra Civil. Participó en todas las operaciones del Rif, incluyendo Alhucemas, y en los vuelos de larga distancia que dieron fama a la aviación española. Durante la Guerra Civil fue utilizado por ambos bandos, aunque ya obsoleto."
  },
  {
    id: 16,
    era: "clasica",
    name: "Fokker C.IV",
    image: "",
    designation: "Fokker C.IV",
    year: 1923, yearEnd: 1932,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Reconocimiento / Bombardeo ligero",
    crew: 2,
    description: "El Fokker C.IV fue un biplaza de reconocimiento holandés que entró en servicio español en 1923. Sus prestaciones eran adecuadas para las misiones de reconocimiento y bombardeo ligero en Marruecos.",
    engine: "Napier Lion W12, 450 cv",
    wingspan: "14,00 m", length: "9,40 m", height: "3,30 m",
    emptyWeight: "1.250 kg", maxWeight: "2.050 kg",
    maxSpeed: "205 km/h", range: "750 km", ceiling: "5.500 m",
    armament: "2 × Vickers de 7,7 mm fijas; 1 × Lewis de 7,7 mm en montaje móvil; hasta 200 kg de bombas",
    variants: [
      { name: "C.IV", engine: "Napier Lion W12, 450 cv", maxSpeed: "205 km/h", emptyWeight: "1.250 kg", maxWeight: "2.050 kg", armament: "2 × Vickers fijas; 1 × Lewis móvil; hasta 200 kg de bombas", desc: "Variante estándar de reconocimiento con Napier Lion de 450 cv Variante única adquirida por España; no se documentan subvariantes en servicio español." }
    ],
    history: "Los Fokker C.IV participaron en la fase final de la guerra del Rif, incluyendo el desembarco de Alhucemas. Su autonomía y velocidad los hacían útiles para misiones de exploración profunda."
  },
  {
    id: 17,
    era: "clasica",
    name: "Macchi M.18",
    image: "",
    designation: "Macchi M.18",
    year: 1923, yearEnd: 1934,
    branch: "armada",
    type: "hidroavion",
    typeLabel: "Hidroavión Naval",
    crew: 2,
    description: "El Macchi M.18 fue un hidroavión italiano de reconocimiento y bombardeo que sirvió con la Aeronáutica Naval española. Versátil y fiable, operó desde bases costeras y desde buques portahidroaviones.",
    engine: "Isotta-Fraschini V6, 250 cv",
    wingspan: "14,90 m", length: "10,80 m", height: "3,70 m",
    emptyWeight: "1.450 kg", maxWeight: "2.200 kg",
    maxSpeed: "165 km/h", range: "600 km", ceiling: "4.500 m",
    armament: "1-2 × ametralladoras de 7,7 mm en montaje flexible; hasta 400 kg de bombas",
    variants: [
      { name: "M.18", engine: "Isotta-Fraschini V6, 250 cv", maxSpeed: "165 km/h", emptyWeight: "1.450 kg", maxWeight: "2.200 kg", armament: "1-2 × ametralladoras de 7,7 mm; hasta 400 kg de bombas", desc: "Versión estándar de reconocimiento y bombardeo con Isotta-Fraschini V6 de 250 cv" },
      { name: "M.18AR", engine: "Isotta-Fraschini V6, 250 cv", maxSpeed: "160 km/h", emptyWeight: "1.500 kg", maxWeight: "2.250 kg", armament: "1-2 × ametralladoras de 7,7 mm; flotadores desmontables para operar desde tierra o agua", desc: "Variante con flotadores desmontables para operar desde tierra o agua" }
    ],
    history: "Los Macchi M.18 operaron desde las bases navales de Cartagena, Cádiz y la base de Atalayón en Marruecos. Participaron en las operaciones navales del desembarco de Alhucemas y en misiones de patrulla costera."
  },
  {
    id: 18,
    era: "clasica",
    name: "Dornier Wal",
    image: "",
    designation: "Dornier Do J Wal / Super Wal",
    year: 1929, yearEnd: 1939,
    branch: "armada",
    type: "hidroavion",
    typeLabel: "Hidroavión de Patrulla / Reconocimiento",
    crew: 4,
    description: "El Dornier Wal fue un gran hidrocanoa bimotor de construcción metálica que prestó servicio con la Aeronáutica Naval española. Famoso por el vuelo del Plus Ultra, fue el hidroavión más importante de la aviación naval española durante la década de 1930.",
    engine: "2 × Napier Lion W12, 450 cv cada uno o 2 × Rolls-Royce Eagle IX V12, 375 cv cada uno",
    wingspan: "22,00 m", length: "17,25 m", height: "5,00 m",
    emptyWeight: "3.500 kg", maxWeight: "5.600 kg",
    maxSpeed: "190 km/h", range: "1.200 km", ceiling: "3.500 m",
    armament: "2-3 × ametralladoras de 7,7 mm en posiciones defensivas; hasta 500 kg de bombas",
    variants: [
      { name: "Wal (Napier Lion)", engine: "2 × Napier Lion W12, 450 cv cada uno", maxSpeed: "195 km/h", emptyWeight: "3.400 kg", maxWeight: "5.400 kg", armament: "2-3 × ametralladoras de 7,7 mm; hasta 500 kg de bombas", desc: "Versión estándar con dos Napier Lion de 450 cv, utilizada en el vuelo del Plus Ultra Motorización del ejemplar «Plus Ultra» (1926)." },
      { name: "Wal (Rolls-Royce Eagle)", engine: "2 × Rolls-Royce Eagle IX V12, 375 cv cada uno", maxSpeed: "180 km/h", emptyWeight: "3.500 kg", maxWeight: "5.600 kg", armament: "2-3 × ametralladoras de 7,7 mm; hasta 500 kg de bombas; mayor fiabilidad y autonomía", desc: "Versión con motores Rolls-Royce Eagle, mayor fiabilidad y autonomía" },
      { name: "Super Wal", engine: "2 × Rolls-Royce Eagle IX V12, 375 cv cada uno (célula ampliada)", maxSpeed: "175 km/h", emptyWeight: "4.100 kg", maxWeight: "6.500 kg", armament: "2-3 × ametralladoras de 7,7 mm; hasta 700 kg de bombas, mayor capacidad de carga", desc: "Versión ampliada con mayor capacidad y motores más potentes" }
    ],
    history: "El Dornier Wal se hizo célebre por el vuelo del Plus Ultra (1926), que cruzó el Atlántico Sur desde Palos de la Frontera a Buenos Aires. Durante la Guerra Civil, los Wal supervivientes prestaron servicio en misiones de patrulla marítima."
  },
  {
    id: 19,
    era: "clasica",
    name: "Nieuport-Delage NiD-52",
    image: "",
    designation: "Nieuport-Delage NiD-52 / NiD-62",
    year: 1930, yearEnd: 1938,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza monoplaza",
    crew: 1,
    description: "El Nieuport-Delage NiD-52 fue el caza estándar de la aviación militar española a principios de la década de 1930. Construido bajo licencia por Hispano-Suiza en Guadalajara, era un sesquiplano elegante pero ya obsoleto al estallar la Guerra Civil en 1936.",
    engine: "Hispano-Suiza 12Mbr V12, 500 cv",
    wingspan: "12,00 m", length: "7,90 m", height: "3,20 m",
    emptyWeight: "1.250 kg", maxWeight: "1.850 kg",
    maxSpeed: "260 km/h", range: "550 km", ceiling: "8.500 m",
    armament: "2 × Vickers de 7,7 mm sincronizadas",
    variants: [
      { name: "NiD-52", engine: "Hispano-Suiza 12Mbr V12, 500 cv", maxSpeed: "260 km/h", emptyWeight: "1.250 kg", maxWeight: "1.850 kg", armament: "2 × Vickers de 7,7 mm sincronizadas", desc: "Versión estándar de caza sesquiplano con Hispano-Suiza 12Mbr de 500 cv" },
      { name: "NiD-62", engine: "Hispano-Suiza 12Xcrs V12, 690 cv", maxSpeed: "298 km/h", emptyWeight: "1.340 kg", maxWeight: "1.960 kg", armament: "2 × Vickers de 7,7 mm sincronizadas; aerodinámica refinada", desc: "Versión mejorada con motor Hispano-Suiza 12Xcrs de 690 cv y aerodinámica refinada" }
    ],
    history: "Al estallar la Guerra Civil, el NiD-52 era el caza más numeroso en ambas fuerzas. Obsoleto frente a los cazas modernos, sufrió graves pérdidas pero combatió en los primeros meses del conflicto hasta ser reemplazado por los Polikarpov y Fiat."
  },
  {
    id: 20,
    era: "clasica",
    name: "De Havilland DH.82 Tiger Moth",
    image: "",
    designation: "De Havilland DH.82A Tiger Moth",
    year: 1934, yearEnd: 1939,
    branch: "ejercito",
    type: "entrenamiento",
    typeLabel: "Entrenamiento",
    crew: 2,
    description: "El Tiger Moth fue el entrenador estándar de la aviación militar española en el período previo a la Guerra Civil. Biplano robusto y dócil, fue adquirido para formar a los pilotos que luego volarían los cazas y bombarderos modernos.",
    engine: "De Havilland Gipsy Major I4 invertido, 130 cv",
    wingspan: "8,94 m", length: "7,29 m", height: "2,68 m",
    emptyWeight: "506 kg", maxWeight: "816 kg",
    maxSpeed: "157 km/h", range: "480 km", ceiling: "4.145 m",
    armament: "Ninguno (algunos equipados con soportes para bombas de entrenamiento)",
    variants: [
      { name: "DH.82A", engine: "De Havilland Gipsy Major I4 invertido, 130 cv", maxSpeed: "157 km/h", emptyWeight: "506 kg", maxWeight: "816 kg", armament: "Ninguno (algunos con soportes para bombas de entrenamiento)", desc: "Versión estándar con Gipsy Major de 130 cv, la más utilizada en España Única variante documentada en servicio español." }
    ],
    history: "Los Tiger Moth formaron a cientos de pilotos españoles antes y durante la Guerra Civil. Ambos bandos utilizaron ejemplares capturados para la instrucción de nuevos pilotos."
  },
  {
    id: 21,
    era: "clasica",
    name: "Vickers Vildebeest",
    image: "",
    designation: "Vickers Type 264 Vildebeest IV",
    year: 1934, yearEnd: 1939,
    branch: "armada",
    type: "bombardeo",
    typeLabel: "Torpedero / Bombardeo",
    crew: 3,
    description: "El Vickers Vildebeest fue un biplano torpedero adquirido por la Aeronáutica Naval para misiones de ataque marítimo. Aunque obsoleto al estallar la Guerra Civil, siguió operando en misiones de patrulla y ataque costero.",
    engine: "Bristol Pegasus IIM3 radial, 825 cv",
    wingspan: "14,95 m", length: "11,28 m", height: "4,32 m",
    emptyWeight: "2.195 kg", maxWeight: "3.540 kg",
    maxSpeed: "230 km/h", range: "1.250 km", ceiling: "5.545 m",
    armament: "1 × Vickers de 7,7 mm fija; 1-2 × Lewis en posiciones dorsales; 1 torpedo de 457 mm o 500 kg de bombas",
    variants: [
      { name: "Vildebeest IV", engine: "Bristol Pegasus IIM3 radial, 825 cv", maxSpeed: "230 km/h", emptyWeight: "2.195 kg", maxWeight: "3.540 kg", armament: "1 × Vickers fija; 1-2 × Lewis dorsales; 1 torpedo de 457 mm o 500 kg de bombas", desc: "Versión con Bristol Pegasus IIM3 de 825 cv, la principal en servicio español Única variante documentada en servicio de la Aeronáutica Naval española." }
    ],
    history: "Los Vildebeest de la Armada operaron desde bases costeras durante la Guerra Civil en misiones de patrulla marítima y ataque a buques. Su lentitud los hacía vulnerables a los cazas enemigos."
  },
  {
    id: 22,
    era: "clasica",
    name: "Junkers Ju 52/3m",
    image: "",
    designation: "Junkers Ju 52/3m (transporte y bombardeo)",
    year: 1936, yearEnd: 1939,
    branch: "nacional",
    type: "transporte",
    typeLabel: "Transporte / Bombardeo",
    crew: 3,
    description: "El Junkers Ju 52/3m fue el principal avión de transporte del bando nacional durante la Guerra Civil. Su robustez y capacidad de carga lo convirtieron en la espina dorsal del puente aéreo que transportó a las tropas del Ejército de África a la península en los primeros días del conflicto.",
    engine: "3 × BMW 132A radial, 660 cv cada uno",
    wingspan: "29,25 m", length: "18,90 m", height: "4,50 m",
    emptyWeight: "6.570 kg", maxWeight: "10.500 kg",
    maxSpeed: "265 km/h", range: "1.300 km", ceiling: "5.500 m",
    armament: "1-2 × MG 15 de 7,92 mm en posiciones defensivas; hasta 2.000 kg de bombas (versión de bombardeo)",
    variants: [
      { name: "Ju 52/3m (transporte)", engine: "3 × BMW 132A radial, 660 cv cada uno", maxSpeed: "265 km/h", emptyWeight: "6.570 kg", maxWeight: "10.500 kg", armament: "1-2 × MG 15 de 7,92 mm defensivas; capacidad para 17-18 soldados", desc: "Versión de transporte estándar con capacidad para 17-18 soldados o carga equivalente" },
      { name: "Ju 52/3m (bombardeo)", engine: "3 × BMW 132A radial, 660 cv cada uno", maxSpeed: "255 km/h", emptyWeight: "6.700 kg", maxWeight: "10.500 kg", armament: "1-2 × MG 15 de 7,92 mm; hasta 2.000 kg de bombas en soportes internos", desc: "Versión modificada con soportes de bombas y armamento defensivo adicional" }
    ],
    history: "El Ju 52 fue decisivo en los primeros días de la Guerra Civil al trasladar por aire a las tropas del Ejército de África desde Marruecos a la península. Este puente aéreo fue una operación pionera en la historia del transporte aéreo militar."
  },
  {
    id: 23,
    era: "clasica",
    name: "Polikarpov I-15",
    image: "",
    designation: "Polikarpov I-15 / I-15bis «Chato»",
    year: 1936, yearEnd: 1939,
    branch: "republicana",
    type: "caza",
    typeLabel: "Caza biplano",
    crew: 1,
    description: "El Polikarpov I-15, apodado «Chato» por sus alas en gaviota, fue uno de los dos cazas soviéticos principales de la aviación republicana. Extremadamente maniobrable, era formidable en combate cerrado a baja y media cota.",
    engine: "M-25V radial, 750 cv",
    wingspan: "10,00 m", length: "6,10 m", height: "2,74 m",
    emptyWeight: "1.250 kg", maxWeight: "1.725 kg",
    maxSpeed: "370 km/h", range: "530 km", ceiling: "9.300 m",
    armament: "4 × ShKAS de 7,62 mm en el capó; hasta 150 kg de bombas",
    variants: [
      { name: "I-15", engine: "M-25 radial, 700 cv", maxSpeed: "367 km/h", emptyWeight: "1.220 kg", maxWeight: "1.700 kg", armament: "4 × PV-1 de 7,62 mm en el capó; hasta 100 kg de bombas", desc: "Versión inicial con ala en gaviota y M-25 de 700 cv, apodada «Chato» Ala en gaviota característica; apodado «Chato»." },
      { name: "I-15bis", engine: "M-25V radial, 750 cv", maxSpeed: "370 km/h", emptyWeight: "1.250 kg", maxWeight: "1.725 kg", armament: "4 × ShKAS de 7,62 mm en el capó; hasta 150 kg de bombas; ala superior recta", desc: "Versión con ala recta, motor M-25V de 750 cv y aerodinámica mejorada" }
    ],
    history: "El I-15 «Chato» fue el caza biplano más importante de la República. Su excepcional maniobrabilidad lo hacía letal en combate cerrado. Participó en la defensa de Madrid, Brunete, Teruel y el Ebro."
  },
  {
    id: 24,
    era: "clasica",
    name: "Polikarpov I-16",
    image: "",
    designation: "Polikarpov I-16 Type 5/10/18 «Mosca»",
    year: 1936, yearEnd: 1939,
    branch: "republicana",
    type: "caza",
    typeLabel: "Caza monoplano",
    crew: 1,
    description: "El Polikarpov I-16, apodado «Mosca» (y «Rata» por los nacionales), fue un revolucionario caza monoplano de ala baja. Uno de los primeros cazas con tren retráctil del mundo, fue el caza más rápido de la Guerra Civil en su momento y el principal adversario del Fiat CR.32 y el Messerschmitt Bf 109.",
    engine: "M-25A radial, 730 cv (Type 5) o M-25V, 750 cv (Type 10) o M-62, 800 cv (Type 18)",
    wingspan: "9,00 m", length: "5,96 m", height: "2,56 m",
    emptyWeight: "1.070 kg", maxWeight: "1.540 kg",
    maxSpeed: "460 km/h (Type 18)", range: "450 km", ceiling: "9.700 m",
    armament: "2-4 × ShKAS de 7,62 mm; 2 × ShVAK de 20 mm (Type 18); hasta 200 kg de bombas",
    variants: [
      { name: "I-16 Type 5", engine: "M-25A radial, 730 cv", maxSpeed: "440 km/h", emptyWeight: "1.025 kg", maxWeight: "1.475 kg", armament: "2 × ShKAS de 7,62 mm en el capó", desc: "Versión inicial con M-25A de 730 cv y 2 ShKAS, la primera en llegar a España Primera versión en llegar a España (otoño de 1936)." },
      { name: "I-16 Type 10", engine: "M-25V radial, 750 cv", maxSpeed: "448 km/h", emptyWeight: "1.070 kg", maxWeight: "1.540 kg", armament: "4 × ShKAS de 7,62 mm; hasta 200 kg de bombas; versión más numerosa en España", desc: "Versión mejorada con 4 ShKAS y motor M-25V de 750 cv, la más numerosa" },
      { name: "I-16 Type 18", engine: "M-62 radial, 800 cv", maxSpeed: "460 km/h", emptyWeight: "1.120 kg", maxWeight: "1.590 kg", armament: "2 × ShVAK de 20 mm + 2 × ShKAS de 7,62 mm; hasta 200 kg de bombas", desc: "Versión con motor M-62 de 800 cv, cañones ShVAK de 20 mm y mejores prestaciones" }
    ],
    history: "El I-16 «Mosca» fue el caza de mayor prestaciones de la República. Su velocidad y trepada superaban al Fiat CR.32, pero su manejo era más exigente. Combatió desde la defensa de Madrid hasta la batalla del Ebro, siendo poco a poco superado por los Bf 109."
  },
  {
    id: 25,
    era: "clasica",
    name: "Heinkel He 51",
    image: "",
    designation: "Heinkel He 51 A-1 / B-1 / C-1",
    year: 1936, yearEnd: 1939,
    branch: "nacional",
    type: "caza",
    typeLabel: "Caza biplano",
    crew: 1,
    description: "El Heinkel He 51 fue el primer caza suministrado a la aviación nacional por la Alemania nazi. Biplano de construcción mixta, era robusto pero ya obsoleto frente al Polikarpov I-16 republicano. Pese a sus limitaciones, sirvió como caza, avión de ataque a tierra y entrenador avanzado.",
    engine: "BMW VI 7,3Z V12, 750 cv",
    wingspan: "11,00 m", length: "8,40 m", height: "3,20 m",
    emptyWeight: "1.460 kg", maxWeight: "1.900 kg",
    maxSpeed: "330 km/h", range: "570 km", ceiling: "7.700 m",
    armament: "2 × MG 17 de 7,92 mm sincronizadas; hasta 6 bombas de 10 kg para apoyo cercano (versión C)",
    variants: [
      { name: "He 51 A-1", engine: "BMW VI 7,3Z V12, 750 cv", maxSpeed: "330 km/h", emptyWeight: "1.460 kg", maxWeight: "1.900 kg", armament: "2 × MG 17 de 7,92 mm sincronizadas", desc: "Versión de caza estándar con BMW VI de 750 cv, primera en llegar a España" },
      { name: "He 51 B-1", engine: "BMW VI 7,3Z V12, 750 cv", maxSpeed: "315 km/h", emptyWeight: "1.560 kg", maxWeight: "2.010 kg", armament: "2 × MG 17 de 7,92 mm; flotadores para operaciones marítimas", desc: "Variante con flotadores para operaciones marítimas, utilizada de forma limitada" },
      { name: "He 51 C-1", engine: "BMW VI 7,3Z V12, 750 cv", maxSpeed: "320 km/h", emptyWeight: "1.520 kg", maxWeight: "1.970 kg", armament: "2 × MG 17 de 7,92 mm; hasta 6 bombas de 10 kg para apoyo cercano", desc: "Versión de ataque a tierra con soportes para bombas ligeras, la más útil en combate" }
    ],
    history: "El He 51 llegó a España con la Legión Cóndor como sustituto provisional del He 45. Rápidamente demostró ser inferior al I-16 republicano en velocidad y trepada, siendo relegado a misiones de ataque al suelo y entrenamiento avanzado."
  },
  {
    id: 26,
    era: "clasica",
    name: "Fiat CR.32",
    image: "",
    designation: "Fiat CR.32 / CR.32bis / CR.32quater «Chirri»",
    year: 1936, yearEnd: 1939,
    branch: "nacional",
    type: "caza",
    typeLabel: "Caza biplano",
    crew: 1,
    description: "El Fiat CR.32, apodado «Chirri», fue el caza más emblemático del bando nacional y posiblemente el mejor biplano de caza de la Guerra Civil. Suministrado por Italia, era extraordinariamente maniobrable y robusto, formando el núcleo de la Aviación Legionaria y de las escuadrillas de caza nacionales.",
    engine: "Fiat A.30 RA bis V12, 600 cv",
    wingspan: "9,50 m", length: "7,45 m", height: "2,36 m",
    emptyWeight: "1.260 kg", maxWeight: "1.690 kg",
    maxSpeed: "360 km/h", range: "680 km", ceiling: "8.800 m",
    armament: "2 × Breda-SAFAT de 12,7 mm sincronizadas; hasta 200 kg de bombas (CR.32bis y quater)",
    variants: [
      { name: "CR.32", engine: "Fiat A.30 RA bis V12, 600 cv", maxSpeed: "360 km/h", emptyWeight: "1.260 kg", maxWeight: "1.690 kg", armament: "2 × Breda-SAFAT de 12,7 mm sincronizadas", desc: "Versión estándar con 2 × Breda de 12,7 mm y Fiat A.30 RA bis de 600 cv" },
      { name: "CR.32bis", engine: "Fiat A.30 RA bis V12, 600 cv", maxSpeed: "356 km/h", emptyWeight: "1.320 kg", maxWeight: "1.760 kg", armament: "2 × Breda de 12,7 mm + 2 × Breda de 7,7 mm sobre el ala; soportes para bombas", desc: "Variante con 2 × Breda de 12,7 mm + 2 × Breda de 7,7 mm sobre el ala, soportes para bombas" },
      { name: "CR.32quater", engine: "Fiat A.30 RA bis V12, 600 cv", maxSpeed: "365 km/h", emptyWeight: "1.230 kg", maxWeight: "1.650 kg", armament: "2 × Breda de 12,7 mm (sin armamento alar); mejor maniobrabilidad por menor peso", desc: "Versión aligerada sin armamento alar, solo las 2 Breda de 12,7 mm, mejor maniobrabilidad" }
    ],
    history: "El CR.32 «Chirri» fue el caza más exitoso del bando nacional. A sus mandos, Joaquín García Morato logró 40 victorias, convirtiéndose en el as de la Guerra Civil. En combate cerrado podía enfrentarse al I-15 con ventaja, aunque era más lento que el I-16 en velocidad punta."
  },
  {
    id: 27,
    era: "clasica",
    name: "Savoia-Marchetti SM.79",
    image: "",
    designation: "Savoia-Marchetti SM.79 Sparviero",
    year: 1936, yearEnd: 1939,
    branch: "nacional",
    type: "bombardeo",
    typeLabel: "Bombardero medio",
    crew: 5,
    description: "El Savoia-Marchetti SM.79 «Sparviero» fue el bombardero italiano más importante en servicio con el bando nacional. Trimotor de madera y tela, era rápido y resistente al daño. Apodado «el jorobado» por su característica cabina superior, realizó misiones de bombardeo estratégico y ataque marítimo.",
    engine: "3 × Alfa Romeo 126 RC.34 radial, 750 cv cada uno",
    wingspan: "21,20 m", length: "16,20 m", height: "4,10 m",
    emptyWeight: "6.800 kg", maxWeight: "10.500 kg",
    maxSpeed: "430 km/h", range: "2.000 km", ceiling: "6.500 m",
    armament: "1 × Breda de 12,7 mm en torreta dorsal; 2 × Breda de 7,7 mm (ventral y lateral); hasta 1.250 kg de bombas",
    variants: [
      { name: "SM.79-I", engine: "3 × Alfa Romeo 126 RC.34 radial, 750 cv cada uno", maxSpeed: "430 km/h", emptyWeight: "6.800 kg", maxWeight: "10.500 kg", armament: "1 × Breda de 12,7 mm dorsal; 2 × Breda de 7,7 mm; hasta 1.250 kg de bombas", desc: "Versión estándar de bombardeo con tres Alfa Romeo 126 RC.34, principal variante en España" },
      { name: "SM.79-II", engine: "3 × Piaggio P.XI RC.40 radial, 1.000 cv cada uno", maxSpeed: "445 km/h", emptyWeight: "7.200 kg", maxWeight: "11.300 kg", armament: "1 × Breda de 12,7 mm dorsal; 2 × Breda de 7,7 mm; hasta 1.250 kg de bombas, mayor potencia", desc: "Variante con motores Piaggio P.XI RC.40 de 1.000 cv, algunas unidades en la fase final de la guerra" }
    ],
    history: "Los SM.79 del bando nacional realizaron bombardeos sobre ciudades republicanas y misiones de ataque marítimo contra puertos y buques. Su velocidad les permitía a menudo escapar de los cazas enemigos sin escolta de caza."
  },
  {
    id: 28,
    era: "clasica",
    name: "Savoia-Marchetti SM.81",
    image: "",
    designation: "Savoia-Marchetti SM.81 Pipistrello",
    year: 1936, yearEnd: 1939,
    branch: "nacional",
    type: "bombardeo",
    typeLabel: "Bombardero medio / Transporte",
    crew: 6,
    description: "El Savoia-Marchetti SM.81 «Pipistrello» fue un trimotor bombardero/transporte italiano que sirvió con las fuerzas nacionales desde el inicio del conflicto. Antecesor del SM.79, era más lento pero igualmente fiable, y fue utilizado tanto en bombardeo como en transporte de tropas y suministros.",
    engine: "3 × Alfa Romeo 125 RC.35 radial, 680 cv cada uno o 3 × Piaggio P.X RC.35, 700 cv cada uno",
    wingspan: "24,00 m", length: "18,30 m", height: "4,80 m",
    emptyWeight: "5.600 kg", maxWeight: "9.300 kg",
    maxSpeed: "340 km/h", range: "1.500 km", ceiling: "6.500 m",
    armament: "1-2 × Breda de 12,7 mm en torretas; 3-4 × Breda de 7,7 mm; hasta 2.000 kg de bombas",
    variants: [
      { name: "SM.81 (Alfa Romeo)", engine: "3 × Alfa Romeo 125 RC.35 radial, 680 cv cada uno", maxSpeed: "340 km/h", emptyWeight: "5.600 kg", maxWeight: "9.300 kg", armament: "1-2 × Breda de 12,7 mm en torretas; 3-4 × Breda de 7,7 mm; hasta 2.000 kg de bombas", desc: "Versión estándar con motores Alfa Romeo 125 RC.35 de 680 cv" },
      { name: "SM.81 (Piaggio)", engine: "3 × Piaggio P.X RC.35 radial, 700 cv cada uno", maxSpeed: "345 km/h", emptyWeight: "5.650 kg", maxWeight: "9.350 kg", armament: "1-2 × Breda de 12,7 mm; 3-4 × Breda de 7,7 mm; hasta 2.000 kg de bombas, ligeramente más potente", desc: "Versión con motores Piaggio P.X RC.35 de 700 cv, ligeramente más potente" }
    ],
    history: "Los SM.81 fueron de los primeros aviones italianos en llegar a España tras el golpe de julio de 1936. Participaron en el puente aéreo del Estrecho y en bombardeos sobre objetivos republicanos durante toda la guerra."
  },
  {
    id: 29,
    era: "clasica",
    name: "Tupolev SB",
    image: "",
    designation: "Tupolev ANT-40 SB / SB-2 «Katiuska»",
    year: 1936, yearEnd: 1939,
    branch: "republicana",
    type: "bombardeo",
    typeLabel: "Bombardero medio rápido",
    crew: 3,
    description: "El Tupolev SB, apodado «Katiuska» por los españoles, fue un bombardero medio bimotor de ala baja que sirvió con la aviación republicana. En su momento era uno de los bombarderos más rápidos del mundo, capaz de escapar de muchos cazas enemigos en vuelo nivelado.",
    engine: "2 × Klimov M-100A V12, 860 cv cada uno",
    wingspan: "20,33 m", length: "12,57 m", height: "3,25 m",
    emptyWeight: "3.260 kg", maxWeight: "5.600 kg",
    maxSpeed: "423 km/h", range: "1.200 km", ceiling: "9.300 m",
    armament: "4 × ShKAS de 7,62 mm en posiciones defensivas; hasta 600 kg de bombas en bahía interna",
    variants: [
      { name: "SB-2M-100A", engine: "2 × Klimov M-100A V12, 860 cv cada uno", maxSpeed: "410 km/h", emptyWeight: "3.260 kg", maxWeight: "5.600 kg", armament: "4 × ShKAS de 7,62 mm defensivas; hasta 600 kg de bombas", desc: "Versión estándar con Klimov M-100A de 860 cv, principal variante en España" },
      { name: "SB-2M-103", engine: "2 × Klimov M-103 V12, 960 cv cada uno", maxSpeed: "423 km/h", emptyWeight: "3.400 kg", maxWeight: "5.750 kg", armament: "4 × ShKAS de 7,62 mm defensivas; hasta 600 kg de bombas; mejor velocidad, llegada en 1938", desc: "Versión con Klimov M-103 de 960 cv, mejor velocidad, llegada en 1938" }
    ],
    history: "Los «Katiuska» fueron los bombarderos más efectivos de la República. Su velocidad les permitía realizar incursiones sin escolta de caza. Bombardearon objetivos nacionales en el frente, puertos y aeródromos, sufriendo pérdidas crecientes a medida que los cazas nacionales mejoraban."
  },
  {
    id: 30,
    era: "clasica",
    name: "Polikarpov R-5",
    image: "",
    designation: "Polikarpov R-5 / R-Z «Natacha» / R-5SSS",
    year: 1936, yearEnd: 1939,
    branch: "republicana",
    type: "ataque",
    typeLabel: "Reconocimiento / Ataque",
    crew: 2,
    description: "El Polikarpov R-5 fue un biplaza de reconocimiento y ataque ligero suministrado por la Unión Soviética a la República. Versión mejorada, el R-Z «Natacha», fue utilizado intensivamente en misiones de observación artillera, bombardeo ligero y apoyo cercano en el frente.",
    engine: "M-17F V12, 680 cv (R-5) o M-34 radial, 830 cv (R-Z)",
    wingspan: "15,50 m", length: "10,56 m", height: "3,25 m",
    emptyWeight: "1.970 kg", maxWeight: "3.050 kg",
    maxSpeed: "280 km/h (R-Z)", range: "800 km", ceiling: "6.400 m",
    armament: "1 × PV-1 de 7,62 mm fija; 1 × ShKAS de 7,62 mm (observador); hasta 500 kg de bombas (R-Z)",
    variants: [
      { name: "R-5SSS", engine: "M-17F V12, 680 cv", maxSpeed: "235 km/h", emptyWeight: "1.970 kg", maxWeight: "2.900 kg", armament: "1 × PV-1 fija; 1 × ShKAS observador; hasta 400 kg de bombas", desc: "Versión de reconocimiento y bombardeo con M-17F de 680 cv, mejor aerodinámica" },
      { name: "R-Z «Natacha»", engine: "M-34 radial, 830 cv", maxSpeed: "280 km/h", emptyWeight: "2.100 kg", maxWeight: "3.050 kg", armament: "1 × PV-1 fija; 1 × ShKAS observador; hasta 500 kg de bombas, armamento reforzado", desc: "Versión de ataque mejorada con motor M-34 de 830 cv, mayor carga bélica y armamento reforzado" }
    ],
    history: "Los R-5 y R-Z «Natacha» realizaron miles de misiones de reconocimiento y ataque a lo largo de la Guerra Civil. Su baja velocidad los hacía vulnerables a los cazas enemigos, pero su capacidad para operar desde aeródromos improvisados los hacía muy valiosos para el apoyo táctico."
  },
  {
    id: 31,
    era: "clasica",
    name: "Dornier Do 17",
    image: "",
    designation: "Dornier Do 17 E-1 / F-1 / P-1",
    year: 1937, yearEnd: 1939,
    branch: "nacional",
    type: "bombardeo",
    typeLabel: "Bombardero medio rápido",
    crew: 4,
    description: "El Dornier Do 17, apodado «lápiz volador» por su fuselaje esbelto, fue un bombardero bimotor alemán suministrado a la Legión Cóndor. Rápido y difícil de interceptar por los cazas republicanos de primera generación, realizó misiones de bombardeo y reconocimiento fotográfico.",
    engine: "2 × BMW VI 7,3 V12, 750 cv cada uno",
    wingspan: "18,00 m", length: "15,80 m", height: "3,40 m",
    emptyWeight: "3.300 kg", maxWeight: "5.500 kg",
    maxSpeed: "350 km/h", range: "1.100 km", ceiling: "5.900 m",
    armament: "4-6 × MG 15 de 7,92 mm en posiciones defensivas; hasta 500 kg de bombas",
    variants: [
      { name: "Do 17 E-1", engine: "2 × BMW VI 7,3 V12, 750 cv cada uno", maxSpeed: "350 km/h", emptyWeight: "3.300 kg", maxWeight: "5.500 kg", armament: "4-6 × MG 15 de 7,92 mm; hasta 500 kg de bombas", desc: "Versión de bombardeo estándar con BMW VI, utilizada por la Legión Cóndor" },
      { name: "Do 17 F-1", engine: "2 × BMW VI 7,3 V12, 750 cv cada uno", maxSpeed: "355 km/h", emptyWeight: "3.400 kg", maxWeight: "5.600 kg", armament: "4-6 × MG 15 de 7,92 mm; cámaras y combustible adicional en lugar de bombas", desc: "Versión de reconocimiento de largo alcance con cámaras y combustible adicional" },
      { name: "Do 17 P-1", engine: "2 × BMW 132N radial, 865 cv cada uno", maxSpeed: "365 km/h", emptyWeight: "3.420 kg", maxWeight: "5.650 kg", armament: "4-6 × MG 15 de 7,92 mm; equipo de reconocimiento táctico", desc: "Versión de reconocimiento táctico con motores BMW 132 radiales" }
    ],
    history: "Los Do 17 de la Legión Cóndor operaron desde bases en España en misiones de bombardeo y reconocimiento. Su velocidad les permitía frecuentemente evadir a los cazas republicanos, aunque sufrieron pérdidas ante los I-16."
  },
  {
    id: 32,
    era: "clasica",
    name: "Heinkel He 111",
    image: "",
    designation: "Heinkel He 111 B-1 / B-2 / E-1",
    year: 1937, yearEnd: 1939,
    branch: "nacional",
    type: "bombardeo",
    typeLabel: "Bombardero medio",
    crew: 5,
    description: "El Heinkel He 111 fue el bombardero alemán más moderno empleado en la Guerra Civil. Bimotor con la característica cabina acristalada, representó un salto tecnológico respecto a los Ju 52 y Do 17 anteriores. Fue utilizado tanto en bombardeo táctico como estratégico.",
    engine: "2 × Junkers Jumo 211 Da V12, 1.000 cv cada uno (B-2) o 2 × Daimler-Benz DB 600Ga V12, 950 cv (E-1)",
    wingspan: "22,60 m", length: "16,40 m", height: "3,40 m",
    emptyWeight: "5.500 kg", maxWeight: "8.600 kg",
    maxSpeed: "370 km/h", range: "1.500 km", ceiling: "6.500 m",
    armament: "3 × MG 15 de 7,92 mm en posiciones defensivas (nariz, dorsal, ventral); hasta 2.000 kg de bombas",
    variants: [
      { name: "He 111 B-1", engine: "2 × Junkers Jumo 210 Da V12, 680 cv cada uno", maxSpeed: "345 km/h", emptyWeight: "5.300 kg", maxWeight: "8.200 kg", armament: "3 × MG 15 de 7,92 mm defensivas; hasta 1.500 kg de bombas", desc: "Versión inicial con Jumo 210 Da de 680 cv, primeras entregas a la Legión Cóndor" },
      { name: "He 111 B-2", engine: "2 × Junkers Jumo 211 Da V12, 1.000 cv cada uno", maxSpeed: "370 km/h", emptyWeight: "5.500 kg", maxWeight: "8.600 kg", armament: "3 × MG 15 de 7,92 mm defensivas; hasta 2.000 kg de bombas", desc: "Versión con Jumo 211 Da de 1.000 cv, mejor velocidad y capacidad de carga" },
      { name: "He 111 E-1", engine: "2 × Daimler-Benz DB 600Ga V12, 950 cv cada uno", maxSpeed: "375 km/h", emptyWeight: "5.600 kg", maxWeight: "8.700 kg", armament: "3 × MG 15 de 7,92 mm defensivas; hasta 2.000 kg de bombas, llegada en 1938", desc: "Versión con DB 600Ga de 950 cv y mayor capacidad de bombas, llegada en 1938" }
    ],
    history: "Los He 111 de la Legión Cóndor participaron en bombardeos estratégicos sobre ciudades republicanas, incluyendo la infraestructura industrial y los puertos. Su velocidad y armamento defensivo los hacían más resistentes que los anteriores bombarderos."
  },
  {
    id: 33,
    era: "clasica",
    name: "Messerschmitt Bf 109",
    image: "",
    designation: "Messerschmitt Bf 109 B-1 / B-2 / C-1 / D-1",
    year: 1937, yearEnd: 1939,
    branch: "nacional",
    type: "caza",
    typeLabel: "Caza monoplano",
    crew: 1,
    description: "El Messerschmitt Bf 109 fue el caza más avanzado empleado en la Guerra Civil Española. Monoplano de ala baja con tren retráctil, representaba la nueva generación de cazas y superaba a todos los aviones republicanos en velocidad y trepada, incluido el Polikarpov I-16.",
    engine: "Junkers Jumo 210 Da V12, 680 cv (B-1/B-2) o Jumo 210 Ga, 730 cv (C-1) o Daimler-Benz DB 600Aa, 960 cv (D-1)",
    wingspan: "9,87 m", length: "8,80 m", height: "2,45 m",
    emptyWeight: "1.580 kg", maxWeight: "1.980 kg",
    maxSpeed: "470 km/h (D-1)", range: "440 km", ceiling: "8.200 m",
    armament: "2-3 × MG 17 de 7,92 mm (versión B); 4 × MG 17 (versión C); 2 × MG 17 + 1 × MG FF de 20 mm (versión D temprana)",
    variants: [
      { name: "Bf 109 B-1/B-2", engine: "Junkers Jumo 210 Da/Ga V12, 680-730 cv", maxSpeed: "440 km/h", emptyWeight: "1.505 kg", maxWeight: "1.900 kg", armament: "2-3 × MG 17 de 7,92 mm", desc: "Versión inicial con Jumo 210 Da/Ga de 680/730 cv y 2-3 MG 17, primera en combatir en España Primera versión en combatir en España (1937)." },
      { name: "Bf 109 C-1", engine: "Junkers Jumo 210 Ga V12, 730 cv", maxSpeed: "450 km/h", emptyWeight: "1.550 kg", maxWeight: "1.950 kg", armament: "4 × MG 17 de 7,92 mm; mayor potencia de fuego", desc: "Versión con 4 × MG 17 y Jumo 210 Ga de 730 cv, mayor potencia de fuego" },
      { name: "Bf 109 D-1", engine: "Daimler-Benz DB 600Aa V12, 960 cv", maxSpeed: "470 km/h", emptyWeight: "1.580 kg", maxWeight: "1.980 kg", armament: "2 × MG 17 de 7,92 mm + 1 × MG FF de 20 mm; la más potente en España", desc: "Versión con DB 600Aa de 960 cv, la más potente en España, superior a todos los cazas republicanos" }
    ],
    history: "El Bf 109 llegó a España con la Legión Cóndor a finales de 1937 y cambió decisivamente la guerra aérea. En manos de pilotos experimentados como Werner Mölders, demostró una superioridad clara sobre el I-16 en velocidad y trepada, contribuyendo a la superioridad aérea nacional en 1938-39."
  },
  {
    id: 34,
    era: "clasica",
    name: "Henschel Hs 123",
    image: "",
    designation: "Henschel Hs 123 A-1",
    year: 1937, yearEnd: 1939,
    branch: "nacional",
    type: "ataque",
    typeLabel: "Ataque a tierra / Buzo",
    crew: 1,
    description: "El Henschel Hs 123 fue un biplano de ataque a tierra alemán que demostró ser extraordinariamente efectivo en la Guerra Civil. Aunque de diseño aparentemente anticuado, su resistencia al daño, precisión en el bombardeo en picado y capacidad para operar desde aeródromos improvisados lo convirtieron en un arma temible.",
    engine: "BMW 132Dc radial, 880 cv",
    wingspan: "10,50 m", length: "8,33 m", height: "3,20 m",
    emptyWeight: "1.500 kg", maxWeight: "2.220 kg",
    maxSpeed: "341 km/h", range: "855 km", ceiling: "9.000 m",
    armament: "2 × MG 17 de 7,92 mm en el capó; hasta 450 kg de bombas (1 × 250 kg bajo el fuselaje + 4 × 50 kg bajo las alas)",
    variants: [
      { name: "Hs 123 A-1", engine: "BMW 132Dc radial, 880 cv", maxSpeed: "341 km/h", emptyWeight: "1.500 kg", maxWeight: "2.220 kg", armament: "2 × MG 17 de 7,92 mm en el capó; hasta 450 kg de bombas", desc: "Versión única de producción con BMW 132Dc de 880 cv, armamento fijo y soportes de bombas Única versión de producción operada en España." }
    ],
    history: "Los Hs 123 de la Legión Cóndor fueron devastadores en misiones de apoyo cercano y bombardeo en picado sobre posiciones republicanas. Su precisión y resistencia al daño los hicieron muy apreciados, y demostraron que un biplano podía seguir siendo útil en combate moderno."
  },
  {
    id: 35,
    era: "clasica",
    name: "Douglas DC-2",
    image: "",
    designation: "Douglas DC-2 / DC-2-142",
    year: 1934, yearEnd: 1939,
    branch: "republicana",
    type: "transporte",
    typeLabel: "Transporte",
    crew: 2,
    description: "El Douglas DC-2 fue un bimotor de transporte comercial adaptado al servicio militar durante la Guerra Civil. La República adquirió varios ejemplares de la línea comercial de LAPE (Líneas Aéreas Postales Españolas), utilizándolos para transporte de personal, evacuación sanitaria y misiones de enlace.",
    engine: "2 × Wright SGR-1820-F52 Cyclone radial, 750 cv cada uno",
    wingspan: "25,91 m", length: "18,89 m", height: "4,97 m",
    emptyWeight: "5.650 kg", maxWeight: "8.440 kg",
    maxSpeed: "325 km/h", range: "1.750 km", ceiling: "6.860 m",
    armament: "Ninguno estándar",
    variants: [
      { name: "DC-2-142", engine: "2 × Wright SGR-1820-F52 Cyclone radial, 750 cv cada uno", maxSpeed: "325 km/h", emptyWeight: "5.650 kg", maxWeight: "8.440 kg", armament: "Ninguno estándar", desc: "Versión estándar de transporte con Wright Cyclone de 750 cv, la principal en servicio español Única variante operada por la República, procedente de la flota comercial de LAPE." }
    ],
    history: "Los DC-2 de LAPE fueron requisados por la República al estallar la guerra. Realizaron misiones de transporte de autoridades, evacuación de heridos y enlace entre frentes. Algunos lograron escapar a territorio francés al final del conflicto."
  }
];
