// ================================================
// data-moderna.js — Base de datos de aeronaves
// Era moderna: posguerra, autarquía, Guerra Fría, OTAN
// y actualidad (1939-2026)
// ================================================
// CAMPO "image": Añadir la URL de la imagen aquí.
// Si está vacío, se mostrará un marcador de posición.
// Este archivo AMPLÍA el array aircraftData declarado en
// data-clasica.js; debe cargarse después de aquél.

aircraftData = aircraftData.concat([
  {
    id: 36,
    era: "moderna",
    name: "Messerschmitt Bf 109 (Escuadrilla Azul)",
    image: "",
    designation: "Messerschmitt Bf 109 E / F",
    year: 1941, yearEnd: 1944,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza de escolta y superioridad aérea",
    crew: 1,
    description: "Entre 1941 y 1944, la Escuadrilla Azul —voluntarios españoles integrados en la Luftwaffe junto a la División Azul— combatió en el Frente del Este a los mandos del Bf 109, encuadrada primero en el JG 27 y después en el JG 51 «Mölders». No se trató de aeronaves del inventario nacional, sino de aparatos alemanes pilotados por españoles.",
    engine: "Daimler-Benz DB 601 V12, 1.100-1.200 cv (según variante E/F)",
    wingspan: "9,87 m", length: "8,64 m", height: "2,50 m",
    emptyWeight: "2.010 kg", maxWeight: "2.700 kg",
    maxSpeed: "570-600 km/h", range: "660 km", ceiling: "11.000 m",
    armament: "2 × MG 17 de 7,92 mm + 1 × MG FF/MG 151 de 20 mm (según versión)",
    variants: [
      { name: "Bf 109 E", desc: "Versión empleada por las primeras rotaciones de la Escuadrilla Azul, encuadrada en el JG 27" },
      { name: "Bf 109 F", desc: "Versión aerodinámicamente refinada empleada por las rotaciones posteriores en el JG 51 «Mölders»" }
    ],
    history: "A lo largo de cinco rotaciones (1941-1944) los pilotos españoles realizaron 5.086 salidas y 611 combates, siéndoles acreditados 163 aviones soviéticos derribados por la pérdida de 22 pilotos muertos o desaparecidos —casi uno de cada tres—. El primer escuadrón fue mandado por Ángel Salas Larrazábal; trece pilotos españoles alcanzaron la condición de as. Las cifras exactas de victorias varían ligeramente entre fuentes españolas y alemanas."
  },
  {
    id: 37,
    era: "moderna",
    name: "CASA 2.111",
    image: "",
    designation: "CASA 2.111 B / D (licencia Heinkel He 111H-16)",
    year: 1945, yearEnd: 1973,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Bombardero medio / Transporte / Entrenamiento",
    crew: 5,
    description: "Versión española del bombardero alemán Heinkel He 111, construida bajo licencia por CASA durante la autarquía. Los primeros ejemplares emplearon motores Junkers Jumo 211F recuperados de un depósito francés; a partir de 1953 se reequiparon con motores británicos Rolls-Royce Merlin, dando lugar a la versión definitiva.",
    engine: "2 × Rolls-Royce Merlin 500-29 V12, 1.600 cv cada uno (versión B/D con Merlin); inicialmente 2 × Junkers Jumo 211F",
    wingspan: "22,60 m", length: "16,40 m", height: "4,00 m",
    emptyWeight: "5.750 kg", maxWeight: "8.200 kg",
    maxSpeed: "435 km/h (con Merlin)", range: "2.300 km", ceiling: "8.000 m",
    armament: "Variable según rol; en configuración de bombardeo original hasta 2.000 kg de bombas (desarmado en las versiones de posguerra dedicadas a transporte y enlace)",
    variants: [
      { name: "CASA 2.111 (Jumo)", desc: "Serie inicial con motores Junkers Jumo 211F, primer vuelo el 23 de mayo de 1945" },
      { name: "CASA 2.111 B/D (Merlin)", desc: "Reequipada con motores Rolls-Royce Merlin 500-29 tras el pedido de 173 motores en 1953, versión definitiva y más numerosa" }
    ],
    history: "Se construyeron unos 236 ejemplares (producción hasta 1956). Cinco CASA 2.111 bombardearon posiciones enemigas durante la Guerra de Ifni (1957-58). Sirvió en bombardeo, reconocimiento, transporte y entrenamiento hasta bien entrados los años sesenta, y en labores de transporte hasta 1973; varios ejemplares supervivientes se emplearon después en el rodaje de la película «La Batalla de Inglaterra» (1969) caracterizados como He 111 originales."
  },
  {
    id: 38,
    era: "moderna",
    name: "CASA 352",
    image: "",
    designation: "CASA 352 / 352L (licencia Junkers Ju 52/3m)",
    year: 1945, yearEnd: 1975,
    branch: "ejercito",
    type: "transporte",
    typeLabel: "Transporte / Lanzamiento paracaidista",
    crew: 2,
    description: "Versión española del célebre trimotor de transporte alemán Junkers Ju 52/3m, fabricada por CASA durante la autarquía en dos variantes según su planta motriz: la 352 con motores BMW originales y la 352L con motores españoles ENMASA Beta.",
    engine: "3 × BMW 132A radial, 725 cv cada uno (versión 352); 3 × ENMASA Beta radial, 700 cv cada uno (versión 352L)",
    wingspan: "29,25 m", length: "18,90 m", height: "5,55 m",
    emptyWeight: "5.720 kg", maxWeight: "10.500 kg",
    maxSpeed: "265 km/h", range: "1.300 km", ceiling: "5.900 m",
    armament: "Ninguno estándar; capacidad para 17 paracaidistas o carga equivalente",
    variants: [
      { name: "CASA 352", desc: "Unos 106 ejemplares con motores radiales BMW 132A" },
      { name: "CASA 352L", desc: "Unos 64 ejemplares con motores españoles ENMASA Beta" }
    ],
    history: "Se construyeron en torno a 170 unidades (1945-1953). Cinco CASA 352 lanzaron 75 paracaidistas durante la Guerra de Ifni (1957-58). Fue la columna vertebral del transporte aéreo y la instrucción paracaidista españolas durante casi tres décadas, retirándose del servicio militar en 1975."
  },
  {
    id: 39,
    era: "moderna",
    name: "Hispano HA-1112 «Buchón»",
    image: "",
    designation: "Hispano Aviación HA-1112-M1L (derivado del Bf 109G-2, designación C.4K)",
    year: 1954, yearEnd: 1965,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza de ataque a tierra",
    crew: 1,
    description: "Descendiente español del Messerschmitt Bf 109G-2, construido en Sevilla a partir de células alemanas incompletas entregadas sin motor. Tras versiones iniciales poco satisfactorias con motor Hispano-Suiza, la variante definitiva se reequipó con el motor británico Rolls-Royce Merlin, dando lugar a un peculiar «híbrido» germano-británico que se convirtió en el último Bf 109 en servicio militar del mundo.",
    engine: "Rolls-Royce Merlin 500-45 V12, 1.600 cv, con hélice Rotol de cuatro palas",
    wingspan: "9,92 m", length: "9,10 m", height: "2,60 m",
    emptyWeight: "2.630 kg", maxWeight: "3.400 kg",
    maxSpeed: "665-674 km/h", range: "850 km", ceiling: "11.500 m",
    armament: "2 × cañón Hispano-Suiza HS-404/HS-808 de 20 mm; hasta 16 cohetes Oerlikon de 80 mm",
    variants: [
      { name: "HA-1109-J1L / HA-1112-K1L «Tripala»", desc: "Versiones iniciales con motor Hispano-Suiza y hélice tripala, primer vuelo en marzo de 1945, prestaciones insuficientes" },
      { name: "HA-1112-M1L «Buchón»", desc: "Versión definitiva con motor Rolls-Royce Merlin 500-45, primer vuelo el 29 de marzo de 1954; unos 172 ejemplares construidos" }
    ],
    history: "Empleado en misiones de apoyo cercano y policía colonial sobre el Sáhara español. Retirado el 27 de diciembre de 1965, siendo el último caza derivado del Bf 109 en servicio militar activo en el mundo. Varios supervivientes protagonizaron, caracterizados de Messerschmitt, la película «La Batalla de Inglaterra» (1969) y siguen volando hoy en colecciones históricas."
  },
  {
    id: 40,
    era: "moderna",
    name: "Hispano HA-200 «Saeta»",
    image: "",
    designation: "Hispano Aviación HA-200 / HA-220 «Super Saeta» (designación E.14 / C.10-A.10)",
    year: 1962, yearEnd: 1980,
    branch: "ejercito",
    type: "entrenamiento",
    typeLabel: "Entrenamiento a reacción / Ataque ligero",
    crew: 2,
    description: "Primer avión a reacción de diseño íntegramente español, desarrollado por Hispano Aviación con la participación de Willy Messerschmitt a partir del anterior HA-100 Triana de hélice. Biplaza en tándem con cabina presurizada y dos turborreactores gemelos montados en el morro; derivó en el monoplaza de ataque HA-220 Super Saeta.",
    engine: "2 × Turboméca Marboré II turborreactor, 400 kg de empuje cada uno",
    wingspan: "10,42 m", length: "8,97 m", height: "3,00 m",
    emptyWeight: "2.235 kg", maxWeight: "3.400 kg",
    maxSpeed: "700 km/h", range: "1.100 km", ceiling: "12.700 m",
    armament: "2 × ametralladora de 7,62 mm u opcional cañón de 12,7 mm; puntos subalares para bombas ligeras y cohetes (HA-220)",
    variants: [
      { name: "HA-200", desc: "Versión de entrenamiento biplaza en tándem, primer vuelo el 12 de agosto de 1955, en servicio desde 1962" },
      { name: "HA-220 «Super Saeta»", desc: "Versión monoplaza de ataque ligero derivada, con mayor capacidad de armamento subalar" }
    ],
    history: "Se construyeron 212 ejemplares en total, incluidos 90 fabricados en Egipto como Helwan Al-Kahira. El HA-200/220 combatió activamente contra el Frente Polisario en el Sáhara Occidental a mediados de los años setenta, siendo el primer reactor de diseño español empleado en combate real."
  },
  {
    id: 41,
    era: "moderna",
    name: "North American F-86 Sabre",
    image: "",
    designation: "North American F-86F-40 Sabre (designación C.5)",
    year: 1955, yearEnd: 1973,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza de superioridad aérea",
    crew: 1,
    description: "Primer caza a reacción de procedencia estadounidense operado por España, recibido tras el Pacto de Madrid de 1953 con Estados Unidos. Marcó el salto definitivo de la aviación militar española a la era del jet moderno tras años de aislamiento internacional y equipo obsoleto.",
    engine: "General Electric J47-GE-27, 2.720 kg de empuje",
    wingspan: "11,30 m", length: "11,44 m", height: "4,47 m",
    emptyWeight: "5.050 kg", maxWeight: "8.230 kg",
    maxSpeed: "1.100 km/h", range: "1.250 km", ceiling: "15.000 m",
    armament: "6 × ametralladora Browning M3 de 12,7 mm; puntos subalares para cohetes o bombas y, posteriormente, misiles AIM-9 Sidewinder",
    variants: [
      { name: "F-86F-40", desc: "Estándar único operado por España, procedente de excedentes de la USAF y modernizado al estándar F-40 con ala «6-3» de borde de ataque extendido" }
    ],
    history: "Llegaron a Getafe el 30 de junio de 1955; se recibieron unos 270 ejemplares, que equiparon las Alas 1 (Manises), 2 (Zaragoza), 4 (Palma) y 6 (Torrejón). Sobre el F-86 se formó en 1956 la primera patrulla acrobática española, la «Patrulla Ascua». Permaneció en servicio hasta 1973, acumulando cerca de 350.000 horas de vuelo."
  },
  {
    id: 42,
    era: "moderna",
    name: "Lockheed F-104G Starfighter",
    image: "",
    designation: "Lockheed F-104G / TF-104G (designación C.8 / CE.8)",
    year: 1965, yearEnd: 1972,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza interceptor",
    crew: 1,
    description: "Interceptor supersónico de ala en flecha extremadamente reducida («misil tripulado»), construido bajo licencia por Canadair. España lo empleó exclusivamente como interceptor de buen tiempo desde Torrejón, logrando el excepcional historial de no perder ni un solo ejemplar en siete años de servicio, algo único entre todos los operadores del tipo.",
    engine: "General Electric J79-GE-11A, 15.600 lbf con postcombustión",
    wingspan: "6,68 m", length: "16,69 m", height: "4,11 m",
    emptyWeight: "6.760 kg", maxWeight: "13.170 kg",
    maxSpeed: "2.130 km/h (Mach 2)", range: "1.740 km", ceiling: "15.240 m",
    armament: "1 × cañón M61 Vulcan de 20 mm; misiles AIM-9 Sidewinder",
    variants: [
      { name: "F-104G / C.8", desc: "18 ejemplares monoplaza de interceptación" },
      { name: "TF-104G / CE.8", desc: "3 ejemplares biplaza de entrenamiento" }
    ],
    history: "Llegaron a Rota el 6 de junio de 1965 (21 ejemplares en total) para equipar el Ala 6/16 en Torrejón. Alemania Occidental, por comparación, perdió 292 de sus 916 Starfighters y 116 pilotos. Retirado en enero de 1973 (último vuelo), sustituido por el F-4C Phantom II."
  },
  {
    id: 43,
    era: "moderna",
    name: "Dassault Mirage III",
    image: "",
    designation: "Dassault Mirage IIIEE / IIIDE (designación C.11 / CE.11)",
    year: 1970, yearEnd: 1993,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza interceptor de ala delta",
    crew: 1,
    description: "Caza delta francés apodado «Plancheta» por su silueta de ala triangular, adquirido para sustituir parte de la flota de F-86 Sabre. Basado en Manises (Valencia), equipó los escuadrones 111 y 113.",
    engine: "SNECMA Atar 9C, 6.200 kgf con postcombustión",
    wingspan: "8,22 m", length: "15,03 m", height: "4,50 m",
    emptyWeight: "7.050 kg", maxWeight: "13.700 kg",
    maxSpeed: "2.350 km/h (Mach 2,2)", range: "1.200 km", ceiling: "20.000 m",
    armament: "2 × cañón DEFA de 30 mm; misiles Matra R530/Magic, bombas y cohetes",
    variants: [
      { name: "Mirage IIIEE / C.11", desc: "24 ejemplares monoplaza, primeros ocho recibidos el 12 de junio de 1970" },
      { name: "Mirage IIIDE / CE.11", desc: "6 ejemplares biplaza de entrenamiento" }
    ],
    history: "España operó 30 ejemplares desde 1970. Sirvió de puente entre la generación del Sabre y la del Mirage F1/F-4 Phantom, retirándose a comienzos de los años noventa."
  },
  {
    id: 44,
    era: "moderna",
    name: "Dassault Mirage F1",
    image: "",
    designation: "Dassault Mirage F1CE / EE / EDA (designación C.14)",
    year: 1975, yearEnd: 2013,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza multirol",
    crew: 1,
    description: "Caza francés de ala en flecha convencional que sustituyó al Mirage delta, operado por las Alas 11 (Manises), 14 (Los Llanos, Albacete) y 46 (Gando, Canarias). Buena parte de la flota recibió una modernización de aviónica y estructura entre 1996 y 2001.",
    engine: "SNECMA Atar 9K-50, 7.200 kgf con postcombustión",
    wingspan: "8,40 m", length: "15,30 m", height: "4,50 m",
    emptyWeight: "7.400 kg", maxWeight: "16.200 kg",
    maxSpeed: "2.350 km/h (Mach 2,2)", range: "1.390 km", ceiling: "20.000 m",
    armament: "2 × cañón DEFA de 30 mm; misiles Matra Magic/Super 530, bombas y cohetes",
    variants: [
      { name: "Mirage F1CE / F1EE", desc: "Versiones monoplaza de caza e interceptación, grueso de la flota (48 modernizados en el SLEP de 1996-2001)" },
      { name: "Mirage F1EDA", desc: "4 ejemplares biplaza de entrenamiento operativo" }
    ],
    history: "España operó 91 ejemplares desde 1975; el último aparato modernizado se entregó el 15 de marzo de 2001. La primera misión española de Policía Aérea del Báltico de la OTAN (2006) se realizó con cuatro Mirage F1M del Ala 14 desde Šiauliai (Lituania), con España como nación líder. Retirado el 23 de junio de 2013 y sustituido por el Eurofighter (Alas 11/14) y el F/A-18 (Ala 46); muchos ejemplares retirados pasaron después a operar como agresores en Estados Unidos."
  },
  {
    id: 45,
    era: "moderna",
    name: "McDonnell Douglas F-4C / RF-4C Phantom II",
    image: "",
    designation: "McDonnell Douglas F-4C Phantom II / RF-4C (designación C.12 / CR.12)",
    year: 1971, yearEnd: 2002,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza multirol / Reconocimiento",
    crew: 2,
    description: "Caza bimotor pesado biplaza que sustituyó al F-104G Starfighter en el Ala 12 de Torrejón, aportando capacidad multirol y de reabastecimiento en vuelo. La versión de reconocimiento RF-4C equipó específicamente el Escuadrón 123.",
    engine: "2 × General Electric J79-GE-15, 75,6 kN cada uno con postcombustión",
    wingspan: "11,71 m", length: "19,20 m", height: "5,02 m",
    emptyWeight: "13.760 kg", maxWeight: "26.310 kg",
    maxSpeed: "2.370 km/h (Mach 2,2)", range: "2.815 km", ceiling: "16.600 m",
    armament: "Hasta 7 toneladas de armamento aire-aire y aire-tierra en pilones externos; el RF-4C, desarmado, portaba equipo de reconocimiento fotográfico",
    variants: [
      { name: "F-4C / C.12", desc: "36-40 ejemplares de caza, primeros recibidos en febrero de 1971 para los escuadrones 121 y 122 del Ala 12" },
      { name: "RF-4C / CR.12", desc: "12 ejemplares de reconocimiento fotográfico (4 desde 1978 y 8 ex Guardia Nacional Aérea de Kentucky desde 1989) para el Escuadrón 123" }
    ],
    history: "El F-4C, apoyado por reabastecedores KC-97L, se retiró en 1989 tras 28 años de servicio; el RF-4C continuó en servicio hasta 2002. Entre ambas versiones acumularon unas 55.000 horas de vuelo en cerca de 36.200 salidas."
  },
  {
    id: 46,
    era: "moderna",
    name: "Northrop / CASA F-5",
    image: "",
    designation: "Northrop SF-5A/B, modernizado SF-5M (designación C.9 / CE.9-AE.9)",
    year: 1970, yearEnd: 2026,
    branch: "ejercito",
    type: "entrenamiento",
    typeLabel: "Caza ligero / Entrenamiento avanzado",
    crew: 2,
    description: "Caza ligero estadounidense fabricado bajo licencia por CASA en Sevilla y Getafe. Tras décadas como caza de primera línea, la flota modernizada F-5M continúa hoy en activo como entrenador avanzado de la Escuela de Caza y Ataque en Talavera la Real.",
    engine: "2 × General Electric J85-GE-13, 22,2 kN cada uno con postcombustión",
    wingspan: "8,10 m", length: "14,38 m", height: "4,01 m",
    emptyWeight: "3.667 kg", maxWeight: "9.379 kg",
    maxSpeed: "1.445 km/h", range: "1.400 km", ceiling: "15.800 m",
    armament: "2 × cañón M39 de 20 mm; hasta 1.680 kg de misiles AIM-9, bombas y cohetes en pilones externos",
    variants: [
      { name: "SF-5A", desc: "Versión monoplaza de caza ligera" },
      { name: "SF-5B", desc: "Versión biplaza de entrenamiento" },
      { name: "SF-5M", desc: "Modernización de aviónica que mantiene la flota en servicio como entrenador avanzado" }
    ],
    history: "CASA construyó 70 ejemplares, el primero volado el 22 de mayo de 1968; el primero llegó a Talavera la Real el 12 de noviembre de 1970. El tipo alcanzó 50 años de servicio español el 12 de noviembre de 2020, con más de 170.000 horas de vuelo acumuladas y más de 1.000 pilotos de caza formados en él, y sigue operativo con el Ala 23."
  },
  {
    id: 47,
    era: "moderna",
    name: "CASA C-101 Aviojet",
    image: "",
    designation: "CASA C-101EB/CC (designación E.25 «Mirlo»)",
    year: 1980, yearEnd: 2026,
    branch: "ejercito",
    type: "entrenamiento",
    typeLabel: "Entrenamiento a reacción",
    crew: 2,
    description: "Primer entrenador a reacción diseñado por CASA (con apoyo de MBB y Northrop) para sustituir al HA-200 Saeta. Biplaza en tándem, equipa la Academia General del Aire en San Javier y es la montura de la Patrulla Águila.",
    engine: "1 × Garrett TFE731-2 turbofán, 3.500 lbf",
    wingspan: "10,60 m", length: "12,50 m", height: "4,25 m",
    emptyWeight: "3.470 kg", maxWeight: "5.600 kg",
    maxSpeed: "770 km/h", range: "3.700 km", ceiling: "12.500 m",
    armament: "6 puntos subalares (hasta 2.250 kg) más bahía ventral para cañón de 30 mm en versiones de ataque",
    variants: [
      { name: "C-101EB", desc: "Versión inicial de entrenamiento básico y avanzado, primer vuelo el 27 de junio de 1977, en servicio desde el 17 de marzo de 1980" },
      { name: "C-101CC", desc: "Versión de ataque ligero con capacidad de armamento ampliada" }
    ],
    history: "España encargó 88 ejemplares (166 construidos en total contando exportaciones). Monta la Academia General del Aire (Ala 79) desde 1980 y a la Patrulla Águila desde su debut el 4 de junio de 1985. Prevista su sustitución por el Pilatus PC-21 hacia 2026."
  },
  {
    id: 48,
    era: "moderna",
    name: "CASA C-212 Aviocar",
    image: "",
    designation: "CASA C-212 Aviocar (designación T.12 / TR.12)",
    year: 1974, yearEnd: 2026,
    branch: "ejercito",
    type: "transporte",
    typeLabel: "Transporte ligero / Instrucción paracaidista",
    crew: 2,
    description: "Bimotor de transporte ligero de diseño español, el avión más vendido de la historia de CASA. Empleado en transporte táctico, instrucción de salto paracaidista, vigilancia marítima (versión Patrullera) y enlace, en proceso de sustitución por nuevos Airbus C-295.",
    engine: "2 × Honeywell TPE331 turbohélice, ~900-925 shp cada uno (según serie)",
    wingspan: "20,28 m", length: "16,15 m", height: "6,60 m",
    emptyWeight: "3.780 kg", maxWeight: "8.100 kg",
    maxSpeed: "354 km/h", range: "1.680 km", ceiling: "7.925 m",
    armament: "Ninguno estándar en la versión de transporte; capacidad para 25 paracaidistas",
    variants: [
      { name: "C-212 Aviocar (transporte)", desc: "Versión estándar de transporte táctico e instrucción de salto" },
      { name: "C-212 (VIGMA)", desc: "Versión de vigilancia marítima operada por la Armada" }
    ],
    history: "Se construyeron 483 ejemplares en total (el modelo más exportado de CASA). Los C-212 empleados en instrucción paracaidista acumulan más de 105.000 horas de vuelo y más de 1.000.000 de lanzamientos en paracaídas hasta finales de 2025. En diciembre de 2025 España encargó 18 nuevos Airbus C-295 para sustituir la flota restante de C-212 y CN-235."
  },
  {
    id: 49,
    era: "moderna",
    name: "McDonnell Douglas / Boeing EF-18 Hornet",
    image: "",
    designation: "McDonnell Douglas EF-18A/M Hornet, EF-18B/BM (designación C.15 / CE.15)",
    year: 1986, yearEnd: 2026,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza multirol",
    crew: 1,
    description: "Elegido en el programa FACA (Futuro Avión de Caza y Ataque) para sustituir al Mirage III, F-4 Phantom II y F-5, el EF-18 Hornet ha sido el caballo de batalla del Ejército del Aire durante cuatro décadas, operando desde las Alas 12 (Torrejón), 15 (Zaragoza) y, hasta junio de 2026, 46 (Gando).",
    engine: "2 × General Electric F404-GE-400, ~71,2 kN cada uno con postcombustión",
    wingspan: "11,43 m", length: "17,07 m", height: "4,66 m",
    emptyWeight: "10.455 kg", maxWeight: "23.541 kg",
    maxSpeed: "1.915 km/h (Mach 1,8)", range: "3.330 km", ceiling: "15.240 m",
    armament: "1 × cañón M61 Vulcan de 20 mm; misiles AIM-9, AIM-120 AMRAAM, AGM-88 HARM, AGM-84 Harpoon; bombas guiadas y pods Litening",
    variants: [
      { name: "EF-18A / EF-18B", desc: "Lote inicial de 72 ejemplares (60 monoplaza + 12 biplaza), primeras entregas desde el 10 de julio de 1986" },
      { name: "EF-18A+ (ex USN)", desc: "24 ejemplares adicionales ex US Navy recibidos desde diciembre de 1995 para equipar el Ala 46 en Gando" },
      { name: "EF-18M / EF-18BM", desc: "Modernización a estándar F/A-18C/D (aviónica, radar y armamento) realizada desde 1993 por McDonnell Douglas y CASA" }
    ],
    history: "Con 96 ejemplares recibidos en total, el EF-18 ha participado en operaciones OTAN sobre Bosnia y Kosovo (Destacamento «Ícaro», 1994-2002), en la Operación Unified Protector sobre Libia (2011) y en sucesivas misiones de Policía Aérea del Báltico de la OTAN («Destacamento Vilkas»). El Ala 46 retiró sus EF-18A+ en junio de 2026, iniciando su relevo por el Eurofighter dentro del programa Halcón."
  },
  {
    id: 50,
    era: "moderna",
    name: "Eurofighter Typhoon",
    image: "",
    designation: "Eurofighter Typhoon C.16 / CE.16",
    year: 2003, yearEnd: 2026,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza multirol de superioridad aérea",
    crew: 1,
    description: "Caza europeo de cuarta generación avanzada desarrollado conjuntamente por Reino Unido, Alemania, Italia y España, y actual espina dorsal de la defensa aérea española, con base en las Alas 11 (Morón), 14 (Los Llanos/Albacete) y 46 (Gando).",
    engine: "2 × Eurojet EJ200 turbofán, con postcombustión",
    wingspan: "11,09 m", length: "15,97 m", height: "5,29 m",
    emptyWeight: "11.500 kg", maxWeight: "22.800 kg",
    maxSpeed: "2.470 km/h (Mach 2,0)", range: "3.500 km", ceiling: "19.812 m",
    armament: "1 × cañón Mauser BK-27 de 27 mm; misiles AMRAAM, Meteor e IRIS-T; armamento aire-tierra guiado",
    variants: [
      { name: "C.16 (monoplaza)", desc: "Versión operativa estándar de caza multirol" },
      { name: "CE.16 (biplaza)", desc: "Versión de entrenamiento operativo" },
      { name: "Tranche 4 «Halcón»", desc: "Nueva generación con radar de escaneo electrónico activo (AESA), en proceso de incorporación 2025-2035" }
    ],
    history: "El primer prototipo biplaza español (DA-6) voló desde Getafe el 31 de agosto de 1996; las primeras entregas a España llegaron en mayo de 2004, asumiendo la Alerta de Reacción Rápida de la OTAN desde Morón en julio de 2008. España opera hoy unos 69 Eurofighters de un pedido original de 74, cifra que crecerá hasta 115 con el programa Halcón (45 nuevos Tranche 4 para sustituir al EF-18 Hornet: 20 unidades del contrato «Halcón I» de junio de 2022, con primer avión presentado en Getafe el 1 de junio de 2025, y 25 unidades más del contrato «Halcón II» firmado con la NETMA el 20 de diciembre de 2024, con entregas entre 2030 y 2035)."
  },
  {
    id: 51,
    era: "moderna",
    name: "AV-8B Harrier II Plus (Armada)",
    image: "",
    designation: "McDonnell Douglas/BAe EAV-8B «Matador II» / EAV-8B+ «Matador II+» (designación VA.1B)",
    year: 1987, yearEnd: 2026,
    branch: "armada",
    type: "caza",
    typeLabel: "Caza de despegue y aterrizaje vertical/corto (VTOL/STOVL) embarcado",
    crew: 1,
    description: "Único caza embarcado de ala fija de la Armada Española, operado por la 9ª Escuadrilla desde Rota y, en el mar, desde el portaaviones «Príncipe de Asturias» y, en la actualidad, desde el buque de proyección estratégica «Juan Carlos I».",
    engine: "1 × Rolls-Royce Pegasus 11-61 (F402-RR-408A), ~10.700 kg de empuje vectorial",
    wingspan: "9,25 m", length: "14,55 m", height: "3,55 m",
    emptyWeight: "6.740 kg", maxWeight: "14.100 kg",
    maxSpeed: "1.065 km/h", range: "1.840 km", ceiling: "15.000 m",
    armament: "1 × cañón GAU-12 de 25 mm; misiles AIM-9 Sidewinder, bombas y cohetes en pilones subalares",
    variants: [
      { name: "EAV-8B «Cobra»", desc: "Primeros 3 ejemplares recibidos el 6 de octubre de 1987" },
      { name: "EAV-8B+ «Matador II+»", desc: "8 nuevos ejemplares ensamblados en España por CASA entre 1996 y 1997, con radar mejorado; el resto de la flota recibió el mismo estándar" }
    ],
    history: "La escuadrilla acumula más de 50.000 horas de vuelo. Su relevo (posiblemente por el F-35B) se debate para en torno al año 2030."
  },
  {
    id: 52,
    era: "moderna",
    name: "Airbus A400M Atlas",
    image: "",
    designation: "Airbus A400M Atlas (designación T.23)",
    year: 2016, yearEnd: 2026,
    branch: "ejercito",
    type: "transporte",
    typeLabel: "Transporte táctico y estratégico",
    crew: 3,
    description: "Cuatrimotor turbohélice de nueva generación fabricado en Sevilla, operado por el Ala 31 (Zaragoza), empleado en despliegues estratégicos y misiones de apoyo en el marco de la OTAN y en el Sahel.",
    engine: "4 × Europrop TP400-D6 turbohélice, ~11.000 shp cada uno",
    wingspan: "42,36 m", length: "45,10 m", height: "14,70 m",
    emptyWeight: "76.500 kg", maxWeight: "141.000 kg",
    maxSpeed: "780 km/h", range: "4.540 km (con carga máxima)", ceiling: "12.190 m",
    armament: "Ninguno estándar; capacidad de reabastecimiento en vuelo y de lanzamiento de carga y paracaidistas",
    variants: [
      { name: "A400M Atlas", desc: "Versión estándar en servicio con el Ala 31" }
    ],
    history: "Sustituye gradualmente a los C-130 Hércules y CN-235 en misiones de transporte estratégico, habiendo participado en despliegues expedicionarios como el realizado en Australia junto a Eurofighters y el A330 MRTT."
  },
  {
    id: 53,
    era: "moderna",
    name: "Airbus A330 MRTT",
    image: "",
    designation: "Airbus A330 MRTT (designación TK.24)",
    year: 2023, yearEnd: 2026,
    branch: "ejercito",
    type: "cisterna",
    typeLabel: "Reabastecimiento en vuelo / Transporte estratégico",
    crew: 3,
    description: "Avión cisterna y de transporte estratégico de largo alcance, convertido por Airbus en Getafe a partir de aviones Iberia ex A330; equipa el recién creado Ala 45 en Torrejón, que sustituye a los antiguos Boeing 707 y KC-130H.",
    engine: "2 × Rolls-Royce Trent 700 turbofán",
    wingspan: "60,30 m", length: "58,80 m", height: "17,40 m",
    emptyWeight: "125.000 kg", maxWeight: "233.000 kg",
    maxSpeed: "880 km/h", range: "16.000 km", ceiling: "12.500 m",
    armament: "Ninguno; sistema de reabastecimiento en vuelo por manguera y cesta (probe-and-drogue)",
    variants: [
      { name: "A330 MRTT", desc: "Tres unidades adquiridas en noviembre de 2021, convertidas por Airbus en Getafe" }
    ],
    history: "El 15 de octubre de 2025 el TK-24-03 del Ala 45 realizó, según el propio Ejército del Aire y del Espacio, «el vuelo más largo, realizado sin escalas, de la historia» de la fuerza aérea española: 11.600 km sobre 12 países en 15 horas y 26 minutos, partiendo de Hangzhou (China)."
  },
  {
    id: 54,
    era: "moderna",
    name: "Airbus C-295",
    image: "",
    designation: "Airbus C-295 / C-295 MPA-MSA «VIGMA» (designación T.21)",
    year: 2001, yearEnd: 2026,
    branch: "ejercito",
    type: "transporte",
    typeLabel: "Transporte medio / Patrulla marítima",
    crew: 5,
    description: "Bimotor turbohélice de transporte medio de diseño español, operado por el Ala 35 (Getafe) desde 2001 en sustitución del CN-235, y desplegado también en versión de patrulla marítima. Apoya misiones exteriores como el Destacamento «Marfil» en Senegal para operaciones en el Sahel.",
    engine: "2 × Pratt & Whitney Canada PW127G turbohélice, ~2.645 shp cada uno",
    wingspan: "25,81 m", length: "24,45 m", height: "8,60 m",
    emptyWeight: "11.200 kg", maxWeight: "23.200 kg",
    maxSpeed: "480 km/h", range: "4.167 km", ceiling: "9.144 m",
    armament: "Ninguno en versión de transporte; la versión MPA/MSA puede portar torpedos y misiles antibuque",
    variants: [
      { name: "C-295 (transporte)", desc: "Versión estándar operada por los escuadrones 352 y 353 del Ala 35" },
      { name: "C-295 MPA/MSA «VIGMA»", desc: "Versión de patrulla y vigilancia marítima; 16 unidades adicionales encargadas junto con las de transporte" }
    ],
    history: "Es el mayor operador mundial del tipo, con más de 90.000 horas de vuelo acumuladas. En diciembre de 2025 España encargó 18 unidades adicionales (unos 1.560 millones de euros) para sustituir la flota restante de C-212 y CN-235."
  },
  {
    id: 55,
    era: "moderna",
    name: "Eurocopter/Airbus Tigre",
    image: "",
    designation: "Eurocopter/Airbus EC-665 Tigre HAP / HAD-E (designación HA-28)",
    year: 2007, yearEnd: 2026,
    branch: "tierra",
    type: "helicoptero",
    typeLabel: "Helicóptero de ataque",
    crew: 2,
    description: "Helicóptero de ataque franco-alemán-español, fabricado en parte en la planta de Albacete, que equipa a las Fuerzas Aeromóviles del Ejército de Tierra (FAMET) en misiones de reconocimiento armado y apoyo de fuego.",
    engine: "2 × MTU/Turbomeca/Rolls-Royce MTR390 turboeje",
    wingspan: "N/D (rotor principal: 13,00 m de diámetro)", length: "15,80 m", height: "3,80 m",
    emptyWeight: "3.300 kg", maxWeight: "6.600 kg",
    maxSpeed: "315 km/h", range: "800 km", ceiling: "4.000 m",
    armament: "1 × cañón de 30 mm; misiles HOT/Spike, cohetes de 68 mm y misiles aire-aire Mistral",
    variants: [
      { name: "Tigre HAP", desc: "Configuración inicial de apoyo y protección, primeros 6 ejemplares recibidos" },
      { name: "Tigre HAD/E", desc: "Versión mejorada de apoyo destructivo/español, con mayor capacidad de armamento" }
    ],
    history: "España adquirió 24 ejemplares desde la elección del programa en 2003. Una versión modernizada del Tigre podría entrar en servicio hacia 2030, según declaraciones del jefe de las FAMET."
  },
  {
    id: 56,
    era: "moderna",
    name: "NH90",
    image: "",
    designation: "NHIndustries NH90 TTH (Ejército de Tierra: HT-29; Ejército del Aire: HD.29 «Lobo»)",
    year: 2015, yearEnd: 2026,
    branch: "tierra",
    type: "helicoptero",
    typeLabel: "Helicóptero de transporte táctico",
    crew: 4,
    description: "Helicóptero de transporte táctico de nueva generación, adquirido para las FAMET, el Ejército del Aire y la Armada en sustitución de flotas más antiguas de Bell y Puma/Cougar.",
    engine: "2 × Rolls-Royce Turbomeca RTM322 turboeje",
    wingspan: "N/D (rotor principal: 16,30 m de diámetro)", length: "19,56 m", height: "5,44 m",
    emptyWeight: "6.400 kg", maxWeight: "10.600 kg",
    maxSpeed: "300 km/h (crucero)", range: "1.600 km", ceiling: "6.000 m",
    armament: "Puntos para ametralladoras de puerta; sin armamento pesado estándar",
    variants: [
      { name: "NH90 TTH / HT-29 (FAMET)", desc: "Primeras entregas al Ejército de Tierra desde 2015" },
      { name: "NH90 / HD.29 «Lobo» (Ejército del Aire)", desc: "Entregas al Ejército del Aire desde 2020" }
    ],
    history: "España encargó 45 unidades repartidas entre los tres ejércitos; las FAMET operan en conjunto unos 75 helicópteros de distintos tipos con cerca de 1.400 efectivos."
  }
]);
