// ================================================
// data.js — Aircraft dataset
// ================================================

const aircraftData = [
  {
    id: 1,
    name: "Farman MF.7",
    designation: "Henri Farman MF.7 Longhorn",
    year: 1911,
    yearEnd: 1916,
    branch: "ejercito",
    type: "recon",
    typeLabel: "Reconnaissance / Trainer",
    crew: 2,
    description: "The Farman MF.7, nicknamed 'Longhorn' for its distinctive extended landing skids, was the very first military aircraft acquired by Spain. In early 1911, the Spanish Army purchased three examples delivered to the newly established Cuatro Vientos airfield near Madrid. These aircraft marked the birth of Spanish military aviation and served as primary trainers for the first generation of Spanish military pilots.",
    engine: "Renault 8B V8, 70 hp",
    wingspan: "15.90 m",
    length: "11.45 m",
    height: "3.40 m",
    emptyWeight: "480 kg",
    maxWeight: "700 kg",
    maxSpeed: "95 km/h",
    range: "250 km",
    ceiling: "3,800 m",
    armament: "None fixed; observer could carry light personal weapons",
    variants: [
      { name: "MF.7", desc: "Standard production version with Renault 8B 70 hp engine and characteristic curved skids" },
      { name: "MF.7bis", desc: "Improved variant with modified ailerons, reinforced landing gear, and minor aerodynamic refinements" }
    ],
    history: "The MF.7s at Cuatro Vientos were the workhorses of early training. Though obsolete by the time combat operations began in Morocco, they served as the essential platform from which Spain's first military aviators earned their wings. By 1915, surviving examples had been relegated to training duties exclusively."
  },
  {
    id: 2,
    name: "Nieuport IV",
    designation: "Nieuport IV-G / IV-M",
    year: 1912,
    yearEnd: 1916,
    branch: "ejercito",
    type: "recon",
    typeLabel: "Reconnaissance / Trainer",
    crew: 2,
    description: "The Nieuport IV was among the first monoplanes in Spanish military service. Acquired starting in 1912, these elegant wire-braced aircraft supplemented the Farmans at Cuatro Vientos. The IV-G variant was a two-seater used for reconnaissance and training, while the IV-M was a single-seat version occasionally used for communications and liaison duties.",
    engine: "Gnome Omega 7-cylinder rotary, 70 hp",
    wingspan: "9.20 m",
    length: "6.80 m",
    height: "2.60 m",
    emptyWeight: "340 kg",
    maxWeight: "560 kg",
    maxSpeed: "110 km/h",
    range: "200 km",
    ceiling: "3,500 m",
    armament: "None standard",
    variants: [
      { name: "IV-G", desc: "Two-seat reconnaissance and training version with Gnome 70 hp, wider chord wing" },
      { name: "IV-M", desc: "Single-seat version with reduced wingspan for communications and liaison roles" }
    ],
    history: "Nieuport IVs served alongside the Farman biplanes in the early escuadrillas. Their monoplane configuration offered better speed than the Farmans but was more demanding to fly. By 1915 they were being replaced by more modern types, with remaining airframes used in training roles."
  },
  {
    id: 3,
    name: "Farman MF.11",
    designation: "Henry Farman F.11 / MF.11bis",
    year: 1913,
    yearEnd: 1918,
    branch: "ejercito",
    type: "recon",
    typeLabel: "Reconnaissance / Light Bomber",
    crew: 2,
    description: "The Farman MF.11 was the primary combat aircraft during Spain's first military operations in Morocco. A pusher biplane with the nacelle mounted ahead of the engine, it gave the observer an excellent forward field of fire. Spanish escuadrillas flew MF.11s from Tetuan beginning in late 1913, conducting the first combat reconnaissance and bombing missions in Spanish military history.",
    engine: "Renault 8Bb V8, 80 hp (later 8Bd at 100 hp)",
    wingspan: "16.15 m",
    length: "9.45 m",
    height: "3.20 m",
    emptyWeight: "530 kg",
    maxWeight: "830 kg",
    maxSpeed: "105 km/h",
    range: "300 km",
    ceiling: "4,000 m",
    armament: "1 x 7mm Hotchkiss M1914 on flexible mount (observer); up to 100 kg bombs",
    variants: [
      { name: "MF.11 A2", desc: "Two-seat reconnaissance variant with 80 hp Renault, standard production model used in Morocco" },
      { name: "MF.11bis", desc: "Improved version with 100 hp Renault 8Bd, enlarged tail surfaces and reinforced structure" },
      { name: "MF.11 Bn2", desc: "Night bomber variant with bomb racks and auxiliary fuel tanks for extended range" }
    ],
    history: "The MF.11 was the backbone of the escuadrilla expedicionaria in Morocco from 1913 onward. It flew reconnaissance over the Rif, spotted for artillery, and carried out the first Spanish bombing attacks using improvised grenades and later purpose-built bombs. Despite its vulnerability to ground fire, it served faithfully until replaced by more modern types from 1916."
  },
  {
    id: 4,
    name: "Morane-Saulnier G",
    designation: "Morane-Saulnier Type G",
    year: 1914,
    yearEnd: 1917,
    branch: "ejercito",
    type: "recon",
    typeLabel: "Reconnaissance Monoplane",
    crew: 2,
    description: "The Morane-Saulnier G was a sleek wire-braced monoplane that brought speed advantages to the Spanish reconnaissance squadrons. Its clean aerodynamic design made it faster than contemporary pusher biplanes, though the narrow-track landing gear demanded skilled piloting. Spain acquired several examples in 1914 for the Morocco campaign.",
    engine: "Gnome Lambda 9-cylinder rotary, 80 hp or Le Rhone 9C, 80 hp",
    wingspan: "10.68 m",
    length: "6.87 m",
    height: "3.20 m",
    emptyWeight: "420 kg",
    maxWeight: "680 kg",
    maxSpeed: "122 km/h",
    range: "400 km",
    ceiling: "4,000 m",
    armament: "None standard (some modified with over-wing Lewis gun in later service)",
    variants: [
      { name: "Type G", desc: "Standard two-seat reconnaissance version with Gnome or Le Rhone 80 hp rotary" },
      { name: "Type GA", desc: "Modified variant with larger fuel capacity for extended reconnaissance missions" }
    ],
    history: "Morane-Saulnier Gs supplemented the Farman pushers in Morocco, their higher speed making them useful for fast reconnaissance sorties where minimising exposure to ground fire was critical. They also served as trainers for transitioning pilots to monoplane handling characteristics."
  },
  {
    id: 5,
    name: "Caudron G.3",
    designation: "Caudron G.3 A2 / D2 / E2",
    year: 1914,
    yearEnd: 1919,
    branch: "ejercito",
    type: "recon",
    typeLabel: "Reconnaissance / Trainer",
    crew: 2,
    description: "The Caudron G.3 was one of the most versatile and widely used aircraft in the early Spanish military inventory. A twin-boom biplane with a short nacelle for the crew, it combined reasonable performance with excellent stability and rugged construction. Spain operated the G.3 in Morocco for reconnaissance and artillery spotting, and later extensively as a trainer at Cuatro Vientos.",
    engine: "Le Rhone 9C 9-cylinder rotary, 80 hp or Gnome Lambda, 80 hp or Anzani radial, 80 hp",
    wingspan: "13.40 m",
    length: "6.40 m",
    height: "2.50 m",
    emptyWeight: "420 kg",
    maxWeight: "710 kg",
    maxSpeed: "106 km/h",
    range: "320 km",
    ceiling: "4,300 m",
    armament: "None standard; observer could carry rifle or light machine gun",
    variants: [
      { name: "G.3 A2", desc: "Two-seat artillery observation and reconnaissance variant with camera mounting points" },
      { name: "G.3 D2", desc: "Two-seat dual-control trainer version with duplicated flying controls" },
      { name: "G.3 E2", desc: "Elementary training variant with simplified equipment and Le Rhone or Anzani engine" }
    ],
    history: "The G.3 earned a reputation as a reliable and forgiving aircraft well-suited to the rough conditions of Moroccan airfields. It served throughout the entire 1914-1919 period, gradually transitioning from frontline reconnaissance to training as more capable types arrived. Its twin-boom design was influential in the development of later Caudron types."
  },
  {
    id: 6,
    name: "Morane-Saulnier L",
    designation: "Morane-Saulnier Type L / LA Parasol",
    year: 1915,
    yearEnd: 1919,
    branch: "ejercito",
    type: "recon",
    typeLabel: "Reconnaissance / Observation Parasol",
    crew: 2,
    description: "The Morane-Saulnier L introduced the parasol wing configuration to Spanish military aviation. The high-wing monoplane layout provided the observer with an unprecedented downward and forward field of view, making it ideal for reconnaissance and artillery spotting over the mountainous Moroccan terrain. Its distinctive parasol silhouette became a familiar sight over the Rif.",
    engine: "Le Rhone 9C 9-cylinder rotary, 80 hp or Gnome Lambda, 80 hp",
    wingspan: "13.50 m",
    length: "6.90 m",
    height: "3.20 m",
    emptyWeight: "440 kg",
    maxWeight: "680 kg",
    maxSpeed: "115 km/h",
    range: "350 km",
    ceiling: "4,000 m",
    armament: "Observer with flexible machine gun on some examples; some fitted with deflector plates on propeller for forward-firing gun",
    variants: [
      { name: "Type L", desc: "Standard parasol reconnaissance two-seater with 80 hp Le Rhone or Gnome" },
      { name: "Type LA", desc: "Improved parasol with refined wing section, enlarged vertical tail, and ailerons replacing wing-warping" }
    ],
    history: "The parasol Moranes proved particularly valuable in Morocco where their excellent downward visibility was a major advantage for spotting enemy positions in mountainous terrain. They served alongside the Farman and Caudron types through 1918, with some remaining in training use until the end of the decade."
  },
  {
    id: 7,
    name: "Farman F.40",
    designation: "Farman F.40 / F.41 / F.46",
    year: 1915,
    yearEnd: 1919,
    branch: "ejercito",
    type: "bomber",
    typeLabel: "Reconnaissance / Bomber",
    crew: 2,
    description: "The Farman F.40 represented a significant upgrade over the earlier MF.11, featuring a more powerful 130 hp Renault engine and refined aerodynamics. This pusher biplane could carry a meaningful bomb load and provided improved performance for both reconnaissance and bombing missions in the Moroccan theater. It became one of the principal combat types of the Spanish escuadrillas during the mid-war period.",
    engine: "Renault 8Fb V8, 130 hp",
    wingspan: "18.20 m",
    length: "9.60 m",
    height: "3.30 m",
    emptyWeight: "700 kg",
    maxWeight: "1,100 kg",
    maxSpeed: "128 km/h",
    range: "400 km",
    ceiling: "4,500 m",
    armament: "1 x 7mm Hotchkiss on flexible mount (observer); up to 200 kg bombs on underwing racks",
    variants: [
      { name: "F.40", desc: "Standard two-seat reconnaissance/bomber with 130 hp Renault 8Fb and nacelle for pilot and observer" },
      { name: "F.41", desc: "Modified variant with revised nacelle, additional streamlining, and improved bomb-release gear" },
      { name: "F.46", desc: "Dual-control trainer conversion with bomb equipment removed and dual flying controls installed" }
    ],
    history: "The F.40 gave Spanish bomber crews a meaningful offensive capability for the first time. Flying from Moroccan airfields, F.40s conducted systematic bombing of Rif encampments and fortified positions. The pusher layout meant the observer could operate a flexible machine gun for rear defense, though the type remained vulnerable to determined ground fire."
  },
  {
    id: 8,
    name: "Caudron G.4",
    designation: "Caudron G.4 A2 / B2 / E2",
    year: 1916,
    yearEnd: 1919,
    branch: "ejercito",
    type: "bomber",
    typeLabel: "Twin-Engine Bomber / Reconnaissance",
    crew: 3,
    description: "The Caudron G.4 was Spain's first twin-engine military aircraft and represented a major leap in capability. Based on the successful G.3 design but enlarged with two engines mounted between the twin booms, it could carry a substantial bomb load over considerable distances. Spanish G.4s were used as heavy bombers in the Morocco campaign, striking targets deep in Rif territory.",
    engine: "2 x Le Rhone 9C 9-cylinder rotary, 80 hp each or 2 x Anzani 10-cylinder radial, 100 hp each",
    wingspan: "17.00 m",
    length: "7.25 m",
    height: "2.60 m",
    emptyWeight: "780 kg",
    maxWeight: "1,250 kg",
    maxSpeed: "121 km/h",
    range: "360 km",
    ceiling: "4,300 m",
    armament: "1-2 x 7mm Hotchkiss on flexible mounts; up to 300 kg bombs",
    variants: [
      { name: "G.4 A2", desc: "Three-seat long-range reconnaissance variant with camera equipment and extra fuel" },
      { name: "G.4 B2", desc: "Three-seat bomber variant with underwing bomb racks and bomb-aiming position in nose nacelle" },
      { name: "G.4 E2", desc: "Twin-engine trainer with dual controls and reduced equipment for conversion training" }
    ],
    history: "The arrival of the G.4 gave Spanish aviation a genuine bomber force. Its twin engines provided redundancy over the hostile Moroccan terrain, and its payload allowed it to deliver devastating attacks on Rif positions. However, the rotary engines required frequent maintenance, and the type was demanding to fly on single engine."
  },
  {
    id: 9,
    name: "Avro 504",
    designation: "Avro 504A / 504B / 504J / 504K",
    year: 1916,
    yearEnd: 1919,
    branch: "ejercito",
    type: "trainer",
    typeLabel: "Trainer",
    crew: 2,
    description: "The Avro 504 was perhaps the most important training aircraft of the era, and Spain was among the many nations that adopted it. Though best known as a trainer, it had originally been designed as a military aircraft and some early variants were used on operations. Spain primarily employed the 504 for pilot training at Cuatro Vientos, where it became the standard elementary and intermediate trainer.",
    engine: "Gnome Lambda 7-cylinder rotary, 80 hp or Gnome Monosoupape, 100 hp or Clerget 9Z, 110 hp",
    wingspan: "10.97 m",
    length: "8.97 m",
    height: "3.18 m",
    emptyWeight: "560 kg",
    maxWeight: "830 kg",
    maxSpeed: "130 km/h",
    range: "400 km",
    ceiling: "4,875 m",
    armament: "None in training configuration; some early variants could carry light bombs or a Lewis gun",
    variants: [
      { name: "504A", desc: "Early production variant with 80 hp Gnome, used for training and limited operational duties" },
      { name: "504B", desc: "Modified variant with larger tailplane and ailerons replacing wing-warping for improved stability" },
      { name: "504J", desc: "Standard trainer version with 100 hp Gnome Monosoupape, widely used for advanced training" },
      { name: "504K", desc: "Universal trainer with adaptable engine mountings to accept various rotary engines; most common variant" }
    ],
    history: "The Avro 504 became the cornerstone of Spanish military flight training. Its docile handling characteristics and rugged construction made it ideal for student pilots. Spain operated 504s throughout the period and well beyond, with some remaining in training service into the 1920s."
  },
  {
    id: 10,
    name: "FBA Type H",
    designation: "FBA Type H / Type C",
    year: 1917,
    yearEnd: 1919,
    branch: "armada",
    type: "flyingboat",
    typeLabel: "Naval Flying Boat",
    crew: 2,
    description: "The FBA (Franco-British Aviation) Type H was the first aircraft operated by the newly created Aeronautica Naval in 1917. These compact pusher flying boats were acquired for coastal patrol and reconnaissance from Spanish naval bases. Operating from harbors at Cartagena, Cadiz, and later from Moroccan coastal stations, they provided the Spanish Navy with its first airborne maritime capability.",
    engine: "Hispano-Suiza 8Aa V8, 150 hp or 8Ab, 180 hp",
    wingspan: "13.30 m",
    length: "9.10 m",
    height: "3.20 m",
    emptyWeight: "780 kg",
    maxWeight: "1,150 kg",
    maxSpeed: "140 km/h",
    range: "450 km",
    ceiling: "4,200 m",
    armament: "1 x 7mm Vickers or Lewis on flexible mount; up to 100 kg bombs or depth charges",
    variants: [
      { name: "Type A", desc: "Initial production model with 150 hp Hispano-Suiza 8Aa, used for coastal patrol" },
      { name: "Type B", desc: "Improved version with 180 hp Hispano-Suiza 8Ab and reinforced hull for open-sea operations" },
      { name: "Type H", desc: "Definitive Spanish-service variant with enlarged fuel tanks and tropical equipment for Moroccan operations" }
    ],
    history: "The FBA flying boats were the founding aircraft of Spanish naval aviation. Operating from coastal bases and naval vessels equipped with launching platforms, they conducted anti-submarine patrols, convoy escort, and coastal reconnaissance. Their service in Moroccan waters demonstrated the value of naval aviation to the Spanish Admiralty."
  },
  {
    id: 11,
    name: "SPAD VII",
    designation: "Societe Pour L'Aviation et ses Derives SPAD S.VII",
    year: 1917,
    yearEnd: 1919,
    branch: "ejercito",
    type: "fighter",
    typeLabel: "Single-Seat Fighter",
    crew: 1,
    description: "The SPAD VII was Spain's first true fighter aircraft, bringing modern combat capability to the escuadrillas. Powered by the excellent Hispano-Suiza V8 engine, the SPAD VII combined rugged construction with good speed and diving performance. Its arrival in Spanish service marked the transition from reconnaissance-focused aviation to a force capable of air superiority and fighter escort missions.",
    engine: "Hispano-Suiza 8Aa V8, 150 hp (later 8Ac, 180 hp)",
    wingspan: "7.82 m",
    length: "6.08 m",
    height: "2.20 m",
    emptyWeight: "500 kg",
    maxWeight: "720 kg",
    maxSpeed: "192 km/h",
    range: "360 km",
    ceiling: "5,800 m",
    armament: "1 x 7.7mm Vickers synchronized machine gun through propeller arc",
    variants: [
      { name: "SPAD VII (150 hp)", desc: "Initial production version with Hispano-Suiza 8Aa 150 hp engine, standard in early Spanish deliveries" },
      { name: "SPAD VII (180 hp)", desc: "Upgraded version with Hispano-Suiza 8Ac 180 hp, improved rate of climb and ceiling" },
      { name: "SPAD VII 'Grand Champ'", desc: "Late-production variant with enlarged wing radiator, heavier armament provisions, and reinforced airframe" }
    ],
    history: "The SPAD VII transformed Spanish fighter capability. Though the Rif War did not present aerial opposition requiring fighter-versus-fighter combat, the SPADs proved invaluable for strafing ground targets and providing armed reconnaissance. Their Hispano-Suiza engines were particularly welcome in Spain, as Hispano-Suiza was a Spanish-origin company, facilitating maintenance and spare parts."
  },
  {
    id: 12,
    name: "Hanriot HD.1",
    designation: "Hanriot HD.1 / HD.2",
    year: 1918,
    yearEnd: 1919,
    branch: "ejercito",
    type: "fighter",
    typeLabel: "Single-Seat Fighter",
    crew: 1,
    description: "The Hanriot HD.1 was a nimble and agile fighter that supplemented the SPAD VIIs in Spanish service. Though often overshadowed by the SPAD, the HD.1 was preferred by some pilots for its superior maneuverability and lighter handling at altitude. Its Le Rhone rotary engine gave it a distinctive sound and characteristic responsiveness that made it popular with experienced fighter pilots.",
    engine: "Le Rhone 9J 9-cylinder rotary, 110 hp",
    wingspan: "8.70 m",
    length: "5.85 m",
    height: "2.94 m",
    emptyWeight: "415 kg",
    maxWeight: "620 kg",
    maxSpeed: "183 km/h",
    range: "300 km",
    ceiling: "6,000 m",
    armament: "1 x 7.7mm Vickers synchronized machine gun (some Spanish examples with 2 x Vickers)",
    variants: [
      { name: "HD.1", desc: "Standard single-seat landplane fighter with 110 hp Le Rhone 9J, single Vickers gun" },
      { name: "HD.1bis", desc: "Modified variant with enlarged tail surfaces and strengthened wing for dive attacks" },
      { name: "HD.2", desc: "Floatplane fighter conversion for naval use with pontoon undercarriage and reinforced fuselage" }
    ],
    history: "Spanish HD.1s served primarily in the Morocco theater where their maneuverability was valuable for low-altitude ground attack and strafing missions. The type continued in Spanish service well after 1919, eventually becoming one of the standard Spanish fighters of the early 1920s. Some HD.2 floatplane variants were evaluated by the Aeronautica Naval."
  },
  
  {
    id: 13,
    name: "Breguet XIV",
    designation: "Breguet XIV A2 / B2",
    year: 1918,
    yearEnd: 1919,
    branch: "ejercito",
    type: "bomber",
    typeLabel: "Bomber / Reconnaissance",
    crew: 2,
    description: "The Breguet XIV was one of the finest two-seat military aircraft of the First World War era, and its acquisition by Spain represented a quantum leap in capability. With its powerful Renault V12 engine, robust airframe, and substantial payload, the Breguet could outrun many fighters of the period while carrying a meaningful bomb load. Spain acquired Breguet XIVs in 1918, making them the most capable aircraft in the Spanish inventory.",
    engine: "Renault 12Fcx V12, 300 hp or 12Fe, 320 hp",
    wingspan: "14.36 m",
    length: "8.87 m",
    height: "3.30 m",
    emptyWeight: "1,010 kg",
    maxWeight: "1,770 kg",
    maxSpeed: "175 km/h",
    range: "700 km",
    ceiling: "5,800 m",
    armament: "1 x 7.7mm Vickers fixed forward; 2 x 7.7mm Lewis on flexible mount (observer); up to 460 kg bombs (B2)",
    variants: [
      { name: "XIV A2", desc: "Two-seat reconnaissance/artillery observation variant with camera installation, wireless, and reduced bomb load" },
      { name: "XIV B2", desc: "Two-seat day bomber with internal and external bomb racks, bomb-aiming position, and full defensive armament" },
      { name: "XIV B1", desc: "Single-seat bomber variant with increased bomb load and no observer position (limited use)" },
      { name: "XIV T", desc: "Post-war transport conversion with enclosed cabin for 4 passengers or cargo" }
    ],
    history: "The Breguet XIV became the most important combat aircraft in Spanish service at the end of the decade. Its combination of speed, range, and payload made it vastly superior to the older Farmans and Caudrons it replaced. In Morocco, it could strike targets deep in Rif territory and return safely. The Breguet remained the backbone of Spanish bomber squadrons well into the 1920s."
  },

  {
    id: 14,
    name: "De Havilland DH.4",
    designation: "Airco DH.4 / DH.4A",
    year: 1918,
    yearEnd: 1919,
    branch: "ejercito",
    type: "bomber",
    typeLabel: "Day Bomber / Reconnaissance",
    crew: 2,
    description: "The De Havilland DH.4 was a highly capable day bomber that entered Spanish service in late 1918. Designed by Geoffrey de Havilland for Aircraft Manufacturing Company (Airco), it was considered one of the best single-engine bombers of the war. Its Rolls-Royce Eagle engine gave it excellent performance, and its bomb load and defensive armament made it a formidable strike aircraft.",
    engine: "Rolls-Royce Eagle III V12, 250 hp or Eagle VIII, 375 hp",
    wingspan: "12.92 m",
    length: "9.35 m",
    height: "3.05 m",
    emptyWeight: "1,080 kg",
    maxWeight: "1,660 kg",
    maxSpeed: "170 km/h",
    range: "680 km",
    ceiling: "6,700 m",
    armament: "1-2 x 7.7mm Vickers fixed forward; 1-2 x 7.7mm Lewis on Scarff ring (observer); up to 210 kg bombs",
    variants: [
      { name: "DH.4 (Eagle III)", desc: "Standard bomber version with 250 hp Rolls-Royce Eagle III, primary variant in Spanish service" },
      { name: "DH.4 (Eagle VIII)", desc: "Upgraded variant with 375 hp Eagle VIII engine, improved high-altitude performance and climb rate" },
      { name: "DH.4A", desc: "Post-war civil transport conversion with enclosed cabin for 2 passengers, some used as liaison aircraft" }
    ],
    history: "Spanish DH.4s arrived too late in the war to see extensive combat but were quickly integrated into the bomber squadrons replacing older Farman types. Their range and speed made them valuable for long-range reconnaissance over Morocco. The DH.4 continued to serve into the early 1920s as Spain modernized its air arm."
  }
];
