// ================================================
// data.js — Base de datos de aeronaves (1911-1939)
// ================================================
// CAMPO "image": Añadir la URL de la imagen aquí.
// Si está vacío, se mostrará un marcador de posición.

var aircraftData = [
  {
    id: 1,
    name: "Farman MF.7",
    image: "",
    designation: "Henri Farman MF.7 Longhorn",
    year: 1911, yearEnd: 1916,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Reconocimiento / Entrenamiento",
    crew: 2,
    description: "El Farman MF.7, apodado «Longhorn» por sus característicos patines de aterrizaje extendidos, fue la primera aeronave militar adquirida por España. En 1911, el Ejército compró tres ejemplares destinados al recién creado aeródromo de Cuatro Vientos, cerca de Madrid.",
    engine: "Renault 8B V8, 70 cv",
    wingspan: "15,90 m", length: "11,45 m", height: "3,40 m",
    emptyWeight: "480 kg", maxWeight: "700 kg",
    maxSpeed: "95 km/h", range: "250 km", ceiling: "3.800 m",
    armament: "Ninguno fijo; el observador podía portar armas ligeras",
    variants: [
      { name: "MF.7", desc: "Versión estándar con motor Renault 8B de 70 cv y patines curvados característicos" },
      { name: "MF.7bis", desc: "Variante mejorada con alerones modificados, tren de aterrizaje reforzado y refinamientos aerodinámicos menores" }
    ],
    history: "Los MF.7 de Cuatro Vientos fueron los caballos de batalla de la instrucción inicial. Aunque obsoletos al inicio de las operaciones en Marruecos, sirvieron como plataforma esencial para la primera generación de pilotos militares españoles."
  },
  {
    id: 2,
    name: "Nieuport IV",
    image: "",
    designation: "Nieuport IV-G / IV-M",
    year: 1912, yearEnd: 1916,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Reconocimiento / Entrenamiento",
    crew: 2,
    description: "El Nieuport IV fue uno de los primeros monoplanos en servicio militar español. Adquirido a partir de 1912, complementó a los Farmans en Cuatro Vientos. La variante IV-G era biplaza para reconocimiento y entrenamiento.",
    engine: "Gnome Omega 7 cilindros rotativo, 70 cv",
    wingspan: "9,20 m", length: "6,80 m", height: "2,60 m",
    emptyWeight: "340 kg", maxWeight: "560 kg",
    maxSpeed: "110 km/h", range: "200 km", ceiling: "3.500 m",
    armament: "Ninguno estándar",
    variants: [
      { name: "IV-G", desc: "Versión biplaza de reconocimiento y entrenamiento con Gnome de 70 cv y ala de cuerda ancha" },
      { name: "IV-M", desc: "Versión monoplaza con envergadura reducida para misiones de enlace y comunicaciones" }
    ],
    history: "Los Nieuport IV sirvieron junto a los biplanos Farman en las primeras escuadrillas. Su configuración de monoplano ofrecía mayor velocidad pero era más exigente de pilotar. Hacia 1915 fueron reemplazados por tipos más modernos."
  },
  {
    id: 3,
    name: "Farman MF.11",
    image: "",
    designation: "Henry Farman F.11 / MF.11bis",
    year: 1913, yearEnd: 1918,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Reconocimiento / Bombardeo ligero",
    crew: 2,
    description: "El Farman MF.11 fue la aeronave de combate principal durante las primeras operaciones militares españolas en Marruecos. Biplano propulsor con la barquilla montada delante del motor, ofrecía al observador un excelente campo de tiro frontal.",
    engine: "Renault 8Bb V8, 80 cv (posteriormente 8Bd de 100 cv)",
    wingspan: "16,15 m", length: "9,45 m", height: "3,20 m",
    emptyWeight: "530 kg", maxWeight: "830 kg",
    maxSpeed: "105 km/h", range: "300 km", ceiling: "4.000 m",
    armament: "1 × Hotchkiss M1914 de 7 mm en montaje flexible (observador); hasta 100 kg de bombas",
    variants: [
      { name: "MF.11 A2", desc: "Variante biplaza de reconocimiento con Renault de 80 cv, modelo estándar utilizado en Marruecos" },
      { name: "MF.11bis", desc: "Versión mejorada con Renault 8Bd de 100 cv, superficies de cola ampliadas y estructura reforzada" },
      { name: "MF.11 Bn2", desc: "Variante de bombardeo nocturno con soportes de bombas y depósitos auxiliares de combustible" }
    ],
    history: "El MF.11 fue la espina dorsal de la escuadrilla expedicionaria en Marruecos desde 1913. Realizó reconocimiento sobre el Rif, dirigió el tiro artillero y llevó a cabo los primeros bombardeos españoles con granadas improvisadas."
  },
  {
    id: 4,
    name: "Caudron G.3",
    image: "",
    designation: "Caudron G.3 A2 / D2 / E2",
    year: 1914, yearEnd: 1919,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Reconocimiento / Entrenamiento",
    crew: 2,
    description: "El Caudron G.3 fue uno de los aviones más versátiles del inventario militar español. Biplano de doble botalón con una corta barquilla para la tripulación, combinaba prestaciones razonables con excelente estabilidad y construcción robusta.",
    engine: "Le Rhône 9C 9 cilindros rotativo, 80 cv o Gnome Lambda, 80 cv",
    wingspan: "13,40 m", length: "6,40 m", height: "2,50 m",
    emptyWeight: "420 kg", maxWeight: "710 kg",
    maxSpeed: "106 km/h", range: "320 km", ceiling: "4.300 m",
    armament: "Ninguno estándar; el observador podía portar fusil o ametralladora ligera",
    variants: [
      { name: "G.3 A2", desc: "Variante biplaza de observación artillera y reconocimiento con puntos de montaje de cámara" },
      { name: "G.3 D2", desc: "Versión de entrenamiento con doble mando y controles duplicados" },
      { name: "G.3 E2", desc: "Variante de instrucción elemental con equipo simplificado y motor Le Rhône o Anzani" }
    ],
    history: "El G.3 se ganó una reputación de avión fiable y dócil, bien adaptado a las duras condiciones de los aeródromos marroquíes. Sirvió durante todo el período 1914-1919, pasando gradualmente de primera línea a entrenamiento."
  },
  {
    id: 5,
    name: "Farman F.40",
    image: "",
    designation: "Farman F.40 / F.41 / F.46",
    year: 1915, yearEnd: 1919,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Reconocimiento / Bombardeo",
    crew: 2,
    description: "El Farman F.40 supuso una mejora significativa respecto al MF.11, con un motor Renault de 130 cv y aerodinámica refinada. Biplano propulsor capaz de transportar una carga bélica considerable, se convirtió en uno de los principales tipos de combate durante el período central de la guerra del Rif.",
    engine: "Renault 8Fb V8, 130 cv",
    wingspan: "18,20 m", length: "9,60 m", height: "3,30 m",
    emptyWeight: "700 kg", maxWeight: "1.100 kg",
    maxSpeed: "128 km/h", range: "400 km", ceiling: "4.500 m",
    armament: "1 × Hotchkiss de 7 mm en montaje flexible; hasta 200 kg de bombas",
    variants: [
      { name: "F.40", desc: "Versión estándar biplaza de reconocimiento/bombardeo con Renault 8Fb de 130 cv" },
      { name: "F.41", desc: "Variante con barquilla revisada, mejor aerodinámica y mecanismo de liberación de bombas mejorado" },
      { name: "F.46", desc: "Conversión a entrenador con doble mando y equipo de bombardeo retirado" }
    ],
    history: "El F.40 proporcionó por primera vez a las tripulaciones españolas una capacidad ofensiva real. Desde los aeródromos marroquíes, realizó bombardeos sistemáticos sobre campamentos y posiciones rifeñas."
  },
  {
    id: 6,
    name: "Caudron G.4",
    image: "",
    designation: "Caudron G.4 A2 / B2 / E2",
    year: 1916, yearEnd: 1919,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Bimotor de Bombardeo / Reconocimiento",
    crew: 3,
    description: "El Caudron G.4 fue el primer bimotor militar español y representó un salto cualitativo importante. Basado en el exitoso G.3 pero ampliado con dos motores entre los dobles botalones, podía transportar una carga de bombas considerable a grandes distancias.",
    engine: "2 × Le Rhône 9C 9 cilindros rotativo, 80 cv cada uno o 2 × Anzani 10 cilindros radial, 100 cv cada uno",
    wingspan: "17,00 m", length: "7,25 m", height: "2,60 m",
    emptyWeight: "780 kg", maxWeight: "1.250 kg",
    maxSpeed: "121 km/h", range: "360 km", ceiling: "4.300 m",
    armament: "1-2 × Hotchkiss de 7 mm en montajes flexibles; hasta 300 kg de bombas",
    variants: [
      { name: "G.4 A2", desc: "Variante triplaza de reconocimiento de largo alcance con equipo fotográfico y combustible extra" },
      { name: "G.4 B2", desc: "Variante triplaza de bombardeo con soportes subalares y posición de bombardero en barquilla delantera" },
      { name: "G.4 E2", desc: "Entrenador bimotor con doble mando para conversión operativa" }
    ],
    history: "La llegada del G.4 dotó a la aviación española de una fuerza de bombardeo genuina. Sus motores dobles proporcionaban redundancia sobre el terreno hostil marroquí, aunque los motores rotativos requerían mantenimiento frecuente."
  },
  {
    id: 7,
    name: "Avro 504",
    image: "",
    designation: "Avro 504A / 504B / 504J / 504K",
    year: 1916, yearEnd: 1925,
    branch: "ejercito",
    type: "entrenamiento",
    typeLabel: "Entrenamiento",
    crew: 2,
    description: "El Avro 504 fue posiblemente el avión de entrenamiento más importante de su época y España fue una de las muchas naciones que lo adoptó. Se empleó principalmente como entrenador elemental e intermedio en Cuatro Vientos.",
    engine: "Gnome Lambda 7 cilindros rotativo, 80 cv o Gnome Monosoupape, 100 cv o Clerget 9Z, 110 cv",
    wingspan: "10,97 m", length: "8,97 m", height: "3,18 m",
    emptyWeight: "560 kg", maxWeight: "830 kg",
    maxSpeed: "130 km/h", range: "400 km", ceiling: "4.875 m",
    armament: "Ninguno en configuración de entrenamiento; algunas variantes podían portar bombas ligeras o Lewis",
    variants: [
      { name: "504A", desc: "Variante inicial con Gnome de 80 cv, usada en entrenamiento y tareas operativas limitadas" },
      { name: "504K", desc: "Entrenador universal con soporte de motor adaptable a diversos rotativos; variante más común" }
    ],
    history: "El Avro 504 fue la piedra angular de la instrucción de vuelo militar española. Sus características de manejo dóciles y construcción robusta lo hacían ideal para pilotos alumnos."
  },
  {
    id: 8,
    name: "FBA Type H",
    image: "",
    designation: "FBA Type H / Type C",
    year: 1917, yearEnd: 1925,
    branch: "armada",
    type: "hidroavion",
    typeLabel: "Hidroavión Naval",
    crew: 2,
    description: "El FBA Type H fue la primera aeronave operada por la recién creada Aeronáutica Naval en 1917. Estos compactos hidrocanoas propulsores fueron adquiridos para patrulla costera y reconocimiento desde bases navales españolas.",
    engine: "Hispano-Suiza 8Aa V8, 150 cv o 8Ab, 180 cv",
    wingspan: "13,30 m", length: "9,10 m", height: "3,20 m",
    emptyWeight: "780 kg", maxWeight: "1.150 kg",
    maxSpeed: "140 km/h", range: "450 km", ceiling: "4.200 m",
    armament: "1 × Vickers o Lewis de 7 mm en montaje flexible; hasta 100 kg de bombas o cargas de profundidad",
    variants: [
      { name: "Type A", desc: "Modelo de producción inicial con Hispano-Suiza 8Aa de 150 cv para patrulla costera" },
      { name: "Type H", desc: "Variante definitiva en servicio español con depósitos ampliados y equipamiento tropical para Marruecos" }
    ],
    history: "Los hidroaviones FBA fueron las aeronaves fundacionales de la aviación naval española. Operaron desde bases costeras realizando patrullas antisubmarinas, escolta de convoyes y reconocimiento marítimo."
  },
  {
    id: 9,
    name: "SPAD VII",
    image: "",
    designation: "Société Pour L'Aviation et ses Dérivés SPAD S.VII",
    year: 1917, yearEnd: 1924,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza monoplaza",
    crew: 1,
    description: "El SPAD VII fue el primer avión de caza verdadero de España, dotando a las escuadrillas de capacidad de combate moderna. Propulsado por el excelente motor V8 Hispano-Suiza, combinaba construcción robusta con buena velocidad y prestaciones en picado.",
    engine: "Hispano-Suiza 8Aa V8, 150 cv (posteriormente 8Ac, 180 cv)",
    wingspan: "7,82 m", length: "6,08 m", height: "2,20 m",
    emptyWeight: "500 kg", maxWeight: "720 kg",
    maxSpeed: "192 km/h", range: "360 km", ceiling: "5.800 m",
    armament: "1 × Vickers de 7,7 mm sincronizada a través del arco de la hélice",
    variants: [
      { name: "SPAD VII (150 cv)", desc: "Versión inicial con Hispano-Suiza 8Aa de 150 cv, estándar en las primeras entregas españolas" },
      { name: "SPAD VII (180 cv)", desc: "Versión mejorada con Hispano-Suiza 8Ac de 180 cv, mejor régimen de trepada y techo" }
    ],
    history: "El SPAD VII transformó la capacidad de caza española. En Marruecos demostró su valor en misiones de ametrallamiento y reconocimiento armado. Sus motores Hispano-Suiza facilitaban el mantenimiento al ser de origen español."
  },
  {
    id: 10,
    name: "Hanriot HD.1",
    image: "",
    designation: "Hanriot HD.1 / HD.2",
    year: 1918, yearEnd: 1928,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza monoplaza",
    crew: 1,
    description: "El Hanriot HD.1 fue un caza ágil y maniobrable que complementó a los SPAD VII en servicio español. Algunos pilotos lo preferían por su superior maniobrabilidad y manejo más ligero en altitud. Su motor rotativo Le Rhône le confería una respuesta característica.",
    engine: "Le Rhône 9J 9 cilindros rotativo, 110 cv",
    wingspan: "8,70 m", length: "5,85 m", height: "2,94 m",
    emptyWeight: "415 kg", maxWeight: "620 kg",
    maxSpeed: "183 km/h", range: "300 km", ceiling: "6.000 m",
    armament: "1 × Vickers de 7,7 mm sincronizada (algunos ejemplares españoles con 2 × Vickers)",
    variants: [
      { name: "HD.1", desc: "Caza terrestre estándar con Le Rhône 9J de 110 cv y una Vickers" },
      { name: "HD.2", desc: "Conversión a caza con flotadores para uso naval con pontones y fuselaje reforzado" }
    ],
    history: "Los HD.1 españoles sirvieron principalmente en el teatro marroquí, donde su maniobrabilidad era valiosa para misiones de ataque a baja cota. El tipo continuó en servicio hasta bien entrada la década de 1920."
  },
  {
    id: 11,
    name: "Breguet XIV",
    image: "",
    designation: "Breguet XIV A2 / B2",
    year: 1918, yearEnd: 1930,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Bombardeo / Reconocimiento",
    crew: 2,
    description: "El Breguet XIV fue uno de los mejores biplazas militares de la Primera Guerra Mundial. Su adquisición por España representó un salto cualitativo: con su potente motor Renault V12 y carga bélica sustancial, superaba a muchos cazas de la época en velocidad.",
    engine: "Renault 12Fcx V12, 300 cv o 12Fe, 320 cv",
    wingspan: "14,36 m", length: "8,87 m", height: "3,30 m",
    emptyWeight: "1.010 kg", maxWeight: "1.770 kg",
    maxSpeed: "175 km/h", range: "700 km", ceiling: "5.800 m",
    armament: "1 × Vickers de 7,7 mm fija frontal; 2 × Lewis de 7,7 mm en montaje flexible; hasta 460 kg de bombas (B2)",
    variants: [
      { name: "XIV A2", desc: "Variante biplaza de reconocimiento/observación con instalación fotográfica y radiotelegrafía" },
      { name: "XIV B2", desc: "Bombardeo diurno con soportes internos y externos, posición de bombardero y armamento defensivo completo" },
      { name: "XIV T", desc: "Conversión de transporte de posguerra con cabina cerrada para 4 pasajeros o carga" }
    ],
    history: "El Breguet XIV se convirtió en el avión de combate más importante en servicio español al final de la década de 1910. En Marruecos podía atacar objetivos en el interior del Rif y regresar con seguridad. Fue la espina dorsal de los escuadrones de bombardeo hasta la llegada del Breguet XIX."
  },
  {
    id: 12,
    name: "De Havilland DH.9",
    image: "",
    designation: "Airco DH.9 / DH.9A",
    year: 1920, yearEnd: 1930,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Bombardeo diurno / Reconocimiento",
    crew: 2,
    description: "El De Havilland DH.9 fue un bombardero diurno de gran capacidad que entró en servicio español en 1920. Diseñado como sucesor del DH.4, ofrecía mejores prestaciones y mayor carga de bombas. Fue ampliamente utilizado en las operaciones del Rif.",
    engine: "Siddeley Puma I6, 230 cv o Liberty 12 V12, 400 cv (DH.9A)",
    wingspan: "12,92 m", length: "9,27 m", height: "3,05 m",
    emptyWeight: "1.010 kg", maxWeight: "1.725 kg",
    maxSpeed: "170 km/h", range: "680 km", ceiling: "5.100 m",
    armament: "1-2 × Vickers de 7,7 mm fija; 1-2 × Lewis en anillo Scarff; hasta 210 kg de bombas",
    variants: [
      { name: "DH.9", desc: "Versión estándar con Siddeley Puma de 230 cv, utilizada en las operaciones del Rif" },
      { name: "DH.9A", desc: "Versión mejorada con Liberty 12 de 400 cv, mayor autonomía y carga, algunas construidas por CASA" }
    ],
    history: "Los DH.9 españoles participaron intensamente en las campañas de Marruecos durante la década de 1920, realizando bombardeo táctico y reconocimiento de largo alcance. Su autonomía los hacía especialmente valiosos sobre el terreno marroquí."
  },
  {
    id: 13,
    name: "Bristol F.2B Fighter",
    image: "",
    designation: "Bristol F.2B Fighter",
    year: 1920, yearEnd: 1931,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Caza / Reconocimiento",
    crew: 2,
    description: "El Bristol F.2B Fighter fue uno de los mejores biplazas de la Primera Guerra Mundial y sirvió en España como avión de caza y reconocimiento. Su combinación de velocidad, maniobrabilidad y armamento defensivo lo hacía formidable incluso frente a cazas monoplazas.",
    engine: "Rolls-Royce Falcon III V12, 275 cv",
    wingspan: "11,96 m", length: "7,87 m", height: "2,97 m",
    emptyWeight: "975 kg", maxWeight: "1.475 kg",
    maxSpeed: "198 km/h", range: "460 km", ceiling: "5.945 m",
    armament: "1 × Vickers de 7,7 mm fija sincronizada; 1-2 × Lewis de 7,7 mm en montaje Scarff (observador)",
    variants: [
      { name: "F.2B (Falcon III)", desc: "Variante estándar con Rolls-Royce Falcon III de 275 cv, principal versión en servicio español" }
    ],
    history: "Los Bristol Fighter españoles operaron en Marruecos como escolta de bombardeo y reconocimiento armado. Su versatilidad los mantuvo en servicio hasta bien entrada la década de 1930."
  },
  {
    id: 14,
    name: "Nieuport 24/27",
    image: "",
    designation: "Nieuport 24 / 24bis / 27",
    year: 1921, yearEnd: 1930,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza monoplaza",
    crew: 1,
    description: "Los Nieuport 24 y 27 fueron los últimos cazas de la línea Nieuport en servir con la aviación militar española. Evolución de los exitosos Nieuport 11 y 17, ofrecían mejor rendimiento que los SPAD VII en maniobrabilidad a baja cota, aunque eran más frágiles.",
    engine: "Le Rhône 9Jb 9 cilindros rotativo, 120 cv (Ni.24) o Gnome Monosoupape 9N, 150 cv (Ni.27)",
    wingspan: "8,21 m", length: "5,78 m", height: "2,40 m",
    emptyWeight: "385 kg", maxWeight: "580 kg",
    maxSpeed: "185 km/h", range: "300 km", ceiling: "5.500 m",
    armament: "1 × Vickers de 7,7 mm sincronizada o 2 × Lewis sobre el ala superior (algunos Ni.24)",
    variants: [
      { name: "Nieuport 24", desc: "Caza con Le Rhône de 120 cv y cola rediseñada, algunos con armamento sobre el ala" },
      { name: "Nieuport 27", desc: "Versión final de producción con Gnome Monosoupape de 150 cv y tren de aterrizaje revisado" }
    ],
    history: "Los Nieuport 24/27 sirvieron como cazas de primera línea en Marruecos, complementando y posteriormente reemplazando a los SPAD VII y Hanriot HD.1 más antiguos."
  },
  {
    id: 15,
    name: "Breguet XIX",
    image: "",
    designation: "Breguet XIX A2 / B2 / G.R. (Grand Raid)",
    year: 1922, yearEnd: 1937,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Bombardeo / Reconocimiento",
    crew: 2,
    description: "El Breguet XIX fue el avión estándar de la aviación militar española durante más de una década. Versátil, robusto y fiable, sirvió como bombardero, avión de reconocimiento y plataforma para récords de distancia. Construido bajo licencia por CASA en España.",
    engine: "Lorraine-Dietrich 12Db V12, 400 cv o Hispano-Suiza 12Hb V12, 500 cv",
    wingspan: "14,83 m", length: "9,51 m", height: "3,69 m",
    emptyWeight: "1.370 kg", maxWeight: "2.450 kg",
    maxSpeed: "230 km/h", range: "800 km", ceiling: "7.000 m",
    armament: "1 × Vickers de 7,7 mm fija; 2 × Lewis de 7,7 mm en torreta; hasta 500 kg de bombas",
    variants: [
      { name: "XIX A2", desc: "Variante de reconocimiento con equipo fotográfico y motores Lorraine de 400 cv" },
      { name: "XIX B2", desc: "Variante de bombardeo con soportes de bombas internos y externos, armamento completo" },
      { name: "XIX G.R. (Grand Raid)", desc: "Versión de largo alcance para récords de distancia con depósitos ampliados" },
      { name: "XIX hidroavión", desc: "Conversión con flotadores para la Aeronáutica Naval" }
    ],
    history: "El Breguet XIX fue la espina dorsal de la aviación militar española desde 1922 hasta la Guerra Civil. Participó en todas las operaciones del Rif, incluyendo Alhucemas, y en los vuelos de larga distancia que dieron fama a la aviación española. Durante la Guerra Civil fue utilizado por ambos bandos, aunque ya obsoleto."
  },
  {
    id: 16,
    name: "Fokker C.IV",
    image: "",
    designation: "Fokker C.IV",
    year: 1923, yearEnd: 1932,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Reconocimiento / Bombardeo ligero",
    crew: 2,
    description: "El Fokker C.IV fue un biplaza de reconocimiento holandés que entró en servicio español en 1923. Sus prestaciones eran adecuadas para las misiones de reconocimiento y bombardeo ligero en Marruecos.",
    engine: "Napier Lion W12, 450 cv",
    wingspan: "14,00 m", length: "9,40 m", height: "3,30 m",
    emptyWeight: "1.250 kg", maxWeight: "2.050 kg",
    maxSpeed: "205 km/h", range: "750 km", ceiling: "5.500 m",
    armament: "2 × Vickers de 7,7 mm fijas; 1 × Lewis de 7,7 mm en montaje móvil; hasta 200 kg de bombas",
    variants: [
      { name: "C.IV", desc: "Variante estándar de reconocimiento con Napier Lion de 450 cv" }
    ],
    history: "Los Fokker C.IV participaron en la fase final de la guerra del Rif, incluyendo el desembarco de Alhucemas. Su autonomía y velocidad los hacían útiles para misiones de exploración profunda."
  },
  {
    id: 17,
    name: "Macchi M.18",
    image: "",
    designation: "Macchi M.18",
    year: 1923, yearEnd: 1934,
    branch: "armada",
    type: "hidroavion",
    typeLabel: "Hidroavión Naval",
    crew: 2,
    description: "El Macchi M.18 fue un hidroavión italiano de reconocimiento y bombardeo que sirvió con la Aeronáutica Naval española. Versátil y fiable, operó desde bases costeras y desde buques portahidroaviones.",
    engine: "Isotta-Fraschini V6, 250 cv",
    wingspan: "14,90 m", length: "10,80 m", height: "3,70 m",
    emptyWeight: "1.450 kg", maxWeight: "2.200 kg",
    maxSpeed: "165 km/h", range: "600 km", ceiling: "4.500 m",
    armament: "1-2 × ametralladoras de 7,7 mm en montaje flexible; hasta 400 kg de bombas",
    variants: [
      { name: "M.18", desc: "Versión estándar de reconocimiento y bombardeo con Isotta-Fraschini V6 de 250 cv" },
      { name: "M.18AR", desc: "Variante con flotadores desmontables para operar desde tierra o agua" }
    ],
    history: "Los Macchi M.18 operaron desde las bases navales de Cartagena, Cádiz y la base de Atalayón en Marruecos. Participaron en las operaciones navales del desembarco de Alhucemas y en misiones de patrulla costera."
  },
  {
    id: 18,
    name: "Dornier Wal",
    image: "",
    designation: "Dornier Do J Wal / Super Wal",
    year: 1929, yearEnd: 1939,
    branch: "armada",
    type: "hidroavion",
    typeLabel: "Hidroavión de Patrulla / Reconocimiento",
    crew: 4,
    description: "El Dornier Wal fue un gran hidrocanoa bimotor de construcción metálica que prestó servicio con la Aeronáutica Naval española. Famoso por el vuelo del Plus Ultra, fue el hidroavión más importante de la aviación naval española durante la década de 1930.",
    engine: "2 × Napier Lion W12, 450 cv cada uno o 2 × Rolls-Royce Eagle IX V12, 375 cv cada uno",
    wingspan: "22,00 m", length: "17,25 m", height: "5,00 m",
    emptyWeight: "3.500 kg", maxWeight: "5.600 kg",
    maxSpeed: "190 km/h", range: "1.200 km", ceiling: "3.500 m",
    armament: "2-3 × ametralladoras de 7,7 mm en posiciones defensivas; hasta 500 kg de bombas",
    variants: [
      { name: "Wal (Napier Lion)", desc: "Versión estándar con dos Napier Lion de 450 cv, utilizada en el vuelo del Plus Ultra" },
      { name: "Wal (Rolls-Royce Eagle)", desc: "Versión con motores Rolls-Royce Eagle, mayor fiabilidad y autonomía" },
      { name: "Super Wal", desc: "Versión ampliada con mayor capacidad y motores más potentes" }
    ],
    history: "El Dornier Wal se hizo célebre por el vuelo del Plus Ultra (1926), que cruzó el Atlántico Sur desde Palos de la Frontera a Buenos Aires. Durante la Guerra Civil, los Wal supervivientes prestaron servicio en misiones de patrulla marítima."
  },
  {
    id: 19,
    name: "Nieuport-Delage NiD-52",
    image: "",
    designation: "Nieuport-Delage NiD-52 / NiD-62",
    year: 1930, yearEnd: 1938,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza monoplaza",
    crew: 1,
    description: "El Nieuport-Delage NiD-52 fue el caza estándar de la aviación militar española a principios de la década de 1930. Construido bajo licencia por Hispano-Suiza en Guadalajara, era un sesquiplano elegante pero ya obsoleto al estallar la Guerra Civil en 1936.",
    engine: "Hispano-Suiza 12Mbr V12, 500 cv",
    wingspan: "12,00 m", length: "7,90 m", height: "3,20 m",
    emptyWeight: "1.250 kg", maxWeight: "1.850 kg",
    maxSpeed: "260 km/h", range: "550 km", ceiling: "8.500 m",
    armament: "2 × Vickers de 7,7 mm sincronizadas",
    variants: [
      { name: "NiD-52", desc: "Versión estándar de caza sesquiplano con Hispano-Suiza 12Mbr de 500 cv" },
      { name: "NiD-62", desc: "Versión mejorada con motor Hispano-Suiza 12Xcrs de 690 cv y aerodinámica refinada" }
    ],
    history: "Al estallar la Guerra Civil, el NiD-52 era el caza más numeroso en ambas fuerzas. Obsoleto frente a los cazas modernos, sufrió graves pérdidas pero combatió en los primeros meses del conflicto hasta ser reemplazado por los Polikarpov y Fiat."
  },
  {
    id: 20,
    name: "De Havilland DH.82 Tiger Moth",
    image: "",
    designation: "De Havilland DH.82A Tiger Moth",
    year: 1934, yearEnd: 1939,
    branch: "ejercito",
    type: "entrenamiento",
    typeLabel: "Entrenamiento",
    crew: 2,
    description: "El Tiger Moth fue el entrenador estándar de la aviación militar española en el período previo a la Guerra Civil. Biplano robusto y dócil, fue adquirido para formar a los pilotos que luego volarían los cazas y bombarderos modernos.",
    engine: "De Havilland Gipsy Major I4 invertido, 130 cv",
    wingspan: "8,94 m", length: "7,29 m", height: "2,68 m",
    emptyWeight: "506 kg", maxWeight: "816 kg",
    maxSpeed: "157 km/h", range: "480 km", ceiling: "4.145 m",
    armament: "Ninguno (algunos equipados con soportes para bombas de entrenamiento)",
    variants: [
      { name: "DH.82A", desc: "Versión estándar con Gipsy Major de 130 cv, la más utilizada en España" }
    ],
    history: "Los Tiger Moth formaron a cientos de pilotos españoles antes y durante la Guerra Civil. Ambos bandos utilizaron ejemplares capturados para la instrucción de nuevos pilotos."
  },
  {
    id: 21,
    name: "Vickers Vildebeest",
    image: "",
    designation: "Vickers Type 264 Vildebeest IV",
    year: 1934, yearEnd: 1939,
    branch: "armada",
    type: "bombardeo",
    typeLabel: "Torpedero / Bombardeo",
    crew: 3,
    description: "El Vickers Vildebeest fue un biplano torpedero adquirido por la Aeronáutica Naval para misiones de ataque marítimo. Aunque obsoleto al estallar la Guerra Civil, siguió operando en misiones de patrulla y ataque costero.",
    engine: "Bristol Pegasus IIM3 radial, 825 cv",
    wingspan: "14,95 m", length: "11,28 m", height: "4,32 m",
    emptyWeight: "2.195 kg", maxWeight: "3.540 kg",
    maxSpeed: "230 km/h", range: "1.250 km", ceiling: "5.545 m",
    armament: "1 × Vickers de 7,7 mm fija; 1-2 × Lewis en posiciones dorsales; 1 torpedo de 457 mm o 500 kg de bombas",
    variants: [
      { name: "Vildebeest IV", desc: "Versión con Bristol Pegasus IIM3 de 825 cv, la principal en servicio español" }
    ],
    history: "Los Vildebeest de la Armada operaron desde bases costeras durante la Guerra Civil en misiones de patrulla marítima y ataque a buques. Su lentitud los hacía vulnerables a los cazas enemigos."
  },
  {
    id: 22,
    name: "Junkers Ju 52/3m",
    image: "",
    designation: "Junkers Ju 52/3m (transporte y bombardeo)",
    year: 1936, yearEnd: 1939,
    branch: "nacional",
    type: "transporte",
    typeLabel: "Transporte / Bombardeo",
    crew: 3,
    description: "El Junkers Ju 52/3m fue el principal avión de transporte del bando nacional durante la Guerra Civil. Su robustez y capacidad de carga lo convirtieron en la espina dorsal del puente aéreo que transportó a las tropas del Ejército de África a la península en los primeros días del conflicto.",
    engine: "3 × BMW 132A radial, 660 cv cada uno",
    wingspan: "29,25 m", length: "18,90 m", height: "4,50 m",
    emptyWeight: "6.570 kg", maxWeight: "10.500 kg",
    maxSpeed: "265 km/h", range: "1.300 km", ceiling: "5.500 m",
    armament: "1-2 × MG 15 de 7,92 mm en posiciones defensivas; hasta 2.000 kg de bombas (versión de bombardeo)",
    variants: [
      { name: "Ju 52/3m (transporte)", desc: "Versión de transporte estándar con capacidad para 17-18 soldados o carga equivalente" },
      { name: "Ju 52/3m (bombardeo)", desc: "Versión modificada con soportes de bombas y armamento defensivo adicional" }
    ],
    history: "El Ju 52 fue decisivo en los primeros días de la Guerra Civil al trasladar por aire a las tropas del Ejército de África desde Marruecos a la península. Este puente aéreo fue una operación pionera en la historia del transporte aéreo militar."
  },
  {
    id: 23,
    name: "Polikarpov I-15",
    image: "",
    designation: "Polikarpov I-15 / I-15bis «Chato»",
    year: 1936, yearEnd: 1939,
    branch: "republicana",
    type: "caza",
    typeLabel: "Caza biplano",
    crew: 1,
    description: "El Polikarpov I-15, apodado «Chato» por sus alas en gaviota, fue uno de los dos cazas soviéticos principales de la aviación republicana. Extremadamente maniobrable, era formidable en combate cerrado a baja y media cota.",
    engine: "M-25V radial, 750 cv",
    wingspan: "10,00 m", length: "6,10 m", height: "2,74 m",
    emptyWeight: "1.250 kg", maxWeight: "1.725 kg",
    maxSpeed: "370 km/h", range: "530 km", ceiling: "9.300 m",
    armament: "4 × ShKAS de 7,62 mm en el capó; hasta 150 kg de bombas",
    variants: [
      { name: "I-15", desc: "Versión inicial con ala en gaviota y M-25 de 700 cv, apodada «Chato»" },
      { name: "I-15bis", desc: "Versión con ala recta, motor M-25V de 750 cv y aerodinámica mejorada" }
    ],
    history: "El I-15 «Chato» fue el caza biplano más importante de la República. Su excepcional maniobrabilidad lo hacía letal en combate cerrado. Participó en la defensa de Madrid, Brunete, Teruel y el Ebro."
  },
  {
    id: 24,
    name: "Polikarpov I-16",
    image: "",
    designation: "Polikarpov I-16 Type 5/10/18 «Mosca»",
    year: 1936, yearEnd: 1939,
    branch: "republicana",
    type: "caza",
    typeLabel: "Caza monoplano",
    crew: 1,
    description: "El Polikarpov I-16, apodado «Mosca» (y «Rata» por los nacionales), fue un revolucionario caza monoplano de ala baja. Uno de los primeros cazas con tren retráctil del mundo, fue el caza más rápido de la Guerra Civil en su momento y el principal adversario del Fiat CR.32 y el Messerschmitt Bf 109.",
    engine: "M-25A radial, 730 cv (Type 5) o M-25V, 750 cv (Type 10) o M-62, 800 cv (Type 18)",
    wingspan: "9,00 m", length: "5,96 m", height: "2,56 m",
    emptyWeight: "1.070 kg", maxWeight: "1.540 kg",
    maxSpeed: "460 km/h (Type 18)", range: "450 km", ceiling: "9.700 m",
    armament: "2-4 × ShKAS de 7,62 mm; 2 × ShVAK de 20 mm (Type 18); hasta 200 kg de bombas",
    variants: [
      { name: "I-16 Type 5", desc: "Versión inicial con M-25A de 730 cv y 2 ShKAS, la primera en llegar a España" },
      { name: "I-16 Type 10", desc: "Versión mejorada con 4 ShKAS y motor M-25V de 750 cv, la más numerosa" },
      { name: "I-16 Type 18", desc: "Versión con motor M-62 de 800 cv, cañones ShVAK de 20 mm y mejores prestaciones" }
    ],
    history: "El I-16 «Mosca» fue el caza de mayor prestaciones de la República. Su velocidad y trepada superaban al Fiat CR.32, pero su manejo era más exigente. Combatió desde la defensa de Madrid hasta la batalla del Ebro, siendo poco a poco superado por los Bf 109."
  },
  {
    id: 25,
    name: "Heinkel He 51",
    image: "",
    designation: "Heinkel He 51 A-1 / B-1 / C-1",
    year: 1936, yearEnd: 1939,
    branch: "nacional",
    type: "caza",
    typeLabel: "Caza biplano",
    crew: 1,
    description: "El Heinkel He 51 fue el primer caza suministrado a la aviación nacional por la Alemania nazi. Biplano de construcción mixta, era robusto pero ya obsoleto frente al Polikarpov I-16 republicano. Pese a sus limitaciones, sirvió como caza, avión de ataque a tierra y entrenador avanzado.",
    engine: "BMW VI 7,3Z V12, 750 cv",
    wingspan: "11,00 m", length: "8,40 m", height: "3,20 m",
    emptyWeight: "1.460 kg", maxWeight: "1.900 kg",
    maxSpeed: "330 km/h", range: "570 km", ceiling: "7.700 m",
    armament: "2 × MG 17 de 7,92 mm sincronizadas; hasta 6 bombas de 10 kg para apoyo cercano (versión C)",
    variants: [
      { name: "He 51 A-1", desc: "Versión de caza estándar con BMW VI de 750 cv, primera en llegar a España" },
      { name: "He 51 B-1", desc: "Variante con flotadores para operaciones marítimas, utilizada de forma limitada" },
      { name: "He 51 C-1", desc: "Versión de ataque a tierra con soportes para bombas ligeras, la más útil en combate" }
    ],
    history: "El He 51 llegó a España con la Legión Cóndor como sustituto provisional del He 45. Rápidamente demostró ser inferior al I-16 republicano en velocidad y trepada, siendo relegado a misiones de ataque al suelo y entrenamiento avanzado."
  },
  {
    id: 26,
    name: "Fiat CR.32",
    image: "",
    designation: "Fiat CR.32 / CR.32bis / CR.32quater «Chirri»",
    year: 1936, yearEnd: 1939,
    branch: "nacional",
    type: "caza",
    typeLabel: "Caza biplano",
    crew: 1,
    description: "El Fiat CR.32, apodado «Chirri», fue el caza más emblemático del bando nacional y posiblemente el mejor biplano de caza de la Guerra Civil. Suministrado por Italia, era extraordinariamente maniobrable y robusto, formando el núcleo de la Aviación Legionaria y de las escuadrillas de caza nacionales.",
    engine: "Fiat A.30 RA bis V12, 600 cv",
    wingspan: "9,50 m", length: "7,45 m", height: "2,36 m",
    emptyWeight: "1.260 kg", maxWeight: "1.690 kg",
    maxSpeed: "360 km/h", range: "680 km", ceiling: "8.800 m",
    armament: "2 × Breda-SAFAT de 12,7 mm sincronizadas; hasta 200 kg de bombas (CR.32bis y quater)",
    variants: [
      { name: "CR.32", desc: "Versión estándar con 2 × Breda de 12,7 mm y Fiat A.30 RA bis de 600 cv" },
      { name: "CR.32bis", desc: "Variante con 2 × Breda de 12,7 mm + 2 × Breda de 7,7 mm sobre el ala, soportes para bombas" },
      { name: "CR.32quater", desc: "Versión aligerada sin armamento alar, solo las 2 Breda de 12,7 mm, mejor maniobrabilidad" }
    ],
    history: "El CR.32 «Chirri» fue el caza más exitoso del bando nacional. A sus mandos, Joaquín García Morato logró 40 victorias, convirtiéndose en el as de la Guerra Civil. En combate cerrado podía enfrentarse al I-15 con ventaja, aunque era más lento que el I-16 en velocidad punta."
  },
  {
    id: 27,
    name: "Savoia-Marchetti SM.79",
    image: "",
    designation: "Savoia-Marchetti SM.79 Sparviero",
    year: 1936, yearEnd: 1939,
    branch: "nacional",
    type: "bombardeo",
    typeLabel: "Bombardero medio",
    crew: 5,
    description: "El Savoia-Marchetti SM.79 «Sparviero» fue el bombardero italiano más importante en servicio con el bando nacional. Trimotor de madera y tela, era rápido y resistente al daño. Apodado «el jorobado» por su característica cabina superior, realizó misiones de bombardeo estratégico y ataque marítimo.",
    engine: "3 × Alfa Romeo 126 RC.34 radial, 750 cv cada uno",
    wingspan: "21,20 m", length: "16,20 m", height: "4,10 m",
    emptyWeight: "6.800 kg", maxWeight: "10.500 kg",
    maxSpeed: "430 km/h", range: "2.000 km", ceiling: "6.500 m",
    armament: "1 × Breda de 12,7 mm en torreta dorsal; 2 × Breda de 7,7 mm (ventral y lateral); hasta 1.250 kg de bombas",
    variants: [
      { name: "SM.79-I", desc: "Versión estándar de bombardeo con tres Alfa Romeo 126 RC.34, principal variante en España" },
      { name: "SM.79-II", desc: "Variante con motores Piaggio P.XI RC.40 de 1.000 cv, algunas unidades en la fase final de la guerra" }
    ],
    history: "Los SM.79 del bando nacional realizaron bombardeos sobre ciudades republicanas y misiones de ataque marítimo contra puertos y buques. Su velocidad les permitía a menudo escapar de los cazas enemigos sin escolta de caza."
  },
  {
    id: 28,
    name: "Savoia-Marchetti SM.81",
    image: "",
    designation: "Savoia-Marchetti SM.81 Pipistrello",
    year: 1936, yearEnd: 1939,
    branch: "nacional",
    type: "bombardeo",
    typeLabel: "Bombardero medio / Transporte",
    crew: 6,
    description: "El Savoia-Marchetti SM.81 «Pipistrello» fue un trimotor bombardero/transporte italiano que sirvió con las fuerzas nacionales desde el inicio del conflicto. Antecesor del SM.79, era más lento pero igualmente fiable, y fue utilizado tanto en bombardeo como en transporte de tropas y suministros.",
    engine: "3 × Alfa Romeo 125 RC.35 radial, 680 cv cada uno o 3 × Piaggio P.X RC.35, 700 cv cada uno",
    wingspan: "24,00 m", length: "18,30 m", height: "4,80 m",
    emptyWeight: "5.600 kg", maxWeight: "9.300 kg",
    maxSpeed: "340 km/h", range: "1.500 km", ceiling: "6.500 m",
    armament: "1-2 × Breda de 12,7 mm en torretas; 3-4 × Breda de 7,7 mm; hasta 2.000 kg de bombas",
    variants: [
      { name: "SM.81 (Alfa Romeo)", desc: "Versión estándar con motores Alfa Romeo 125 RC.35 de 680 cv" },
      { name: "SM.81 (Piaggio)", desc: "Versión con motores Piaggio P.X RC.35 de 700 cv, ligeramente más potente" }
    ],
    history: "Los SM.81 fueron de los primeros aviones italianos en llegar a España tras el golpe de julio de 1936. Participaron en el puente aéreo del Estrecho y en bombardeos sobre objetivos republicanos durante toda la guerra."
  },
  {
    id: 29,
    name: "Tupolev SB",
    image: "",
    designation: "Tupolev ANT-40 SB / SB-2 «Katiuska»",
    year: 1936, yearEnd: 1939,
    branch: "republicana",
    type: "bombardeo",
    typeLabel: "Bombardero medio rápido",
    crew: 3,
    description: "El Tupolev SB, apodado «Katiuska» por los españoles, fue un bombardero medio bimotor de ala baja que sirvió con la aviación republicana. En su momento era uno de los bombarderos más rápidos del mundo, capaz de escapar de muchos cazas enemigos en vuelo nivelado.",
    engine: "2 × Klimov M-100A V12, 860 cv cada uno",
    wingspan: "20,33 m", length: "12,57 m", height: "3,25 m",
    emptyWeight: "3.260 kg", maxWeight: "5.600 kg",
    maxSpeed: "423 km/h", range: "1.200 km", ceiling: "9.300 m",
    armament: "4 × ShKAS de 7,62 mm en posiciones defensivas; hasta 600 kg de bombas en bahía interna",
    variants: [
      { name: "SB-2M-100A", desc: "Versión estándar con Klimov M-100A de 860 cv, principal variante en España" },
      { name: "SB-2M-103", desc: "Versión con Klimov M-103 de 960 cv, mejor velocidad, llegada en 1938" }
    ],
    history: "Los «Katiuska» fueron los bombarderos más efectivos de la República. Su velocidad les permitía realizar incursiones sin escolta de caza. Bombardearon objetivos nacionales en el frente, puertos y aeródromos, sufriendo pérdidas crecientes a medida que los cazas nacionales mejoraban."
  },
  {
    id: 30,
    name: "Polikarpov R-5",
    image: "",
    designation: "Polikarpov R-5 / R-Z «Natacha» / R-5SSS",
    year: 1936, yearEnd: 1939,
    branch: "republicana",
    type: "ataque",
    typeLabel: "Reconocimiento / Ataque",
    crew: 2,
    description: "El Polikarpov R-5 fue un biplaza de reconocimiento y ataque ligero suministrado por la Unión Soviética a la República. Versión mejorada, el R-Z «Natacha», fue utilizado intensivamente en misiones de observación artillera, bombardeo ligero y apoyo cercano en el frente.",
    engine: "M-17F V12, 680 cv (R-5) o M-34 radial, 830 cv (R-Z)",
    wingspan: "15,50 m", length: "10,56 m", height: "3,25 m",
    emptyWeight: "1.970 kg", maxWeight: "3.050 kg",
    maxSpeed: "280 km/h (R-Z)", range: "800 km", ceiling: "6.400 m",
    armament: "1 × PV-1 de 7,62 mm fija; 1 × ShKAS de 7,62 mm (observador); hasta 500 kg de bombas (R-Z)",
    variants: [
      { name: "R-5SSS", desc: "Versión de reconocimiento y bombardeo con M-17F de 680 cv, mejor aerodinámica" },
      { name: "R-Z «Natacha»", desc: "Versión de ataque mejorada con motor M-34 de 830 cv, mayor carga bélica y armamento reforzado" }
    ],
    history: "Los R-5 y R-Z «Natacha» realizaron miles de misiones de reconocimiento y ataque a lo largo de la Guerra Civil. Su baja velocidad los hacía vulnerables a los cazas enemigos, pero su capacidad para operar desde aeródromos improvisados los hacía muy valiosos para el apoyo táctico."
  },
  {
    id: 31,
    name: "Dornier Do 17",
    image: "",
    designation: "Dornier Do 17 E-1 / F-1 / P-1",
    year: 1937, yearEnd: 1939,
    branch: "nacional",
    type: "bombardeo",
    typeLabel: "Bombardero medio rápido",
    crew: 4,
    description: "El Dornier Do 17, apodado «lápiz volador» por su fuselaje esbelto, fue un bombardero bimotor alemán suministrado a la Legión Cóndor. Rápido y difícil de interceptar por los cazas republicanos de primera generación, realizó misiones de bombardeo y reconocimiento fotográfico.",
    engine: "2 × BMW VI 7,3 V12, 750 cv cada uno",
    wingspan: "18,00 m", length: "15,80 m", height: "3,40 m",
    emptyWeight: "3.300 kg", maxWeight: "5.500 kg",
    maxSpeed: "350 km/h", range: "1.100 km", ceiling: "5.900 m",
    armament: "4-6 × MG 15 de 7,92 mm en posiciones defensivas; hasta 500 kg de bombas",
    variants: [
      { name: "Do 17 E-1", desc: "Versión de bombardeo estándar con BMW VI, utilizada por la Legión Cóndor" },
      { name: "Do 17 F-1", desc: "Versión de reconocimiento de largo alcance con cámaras y combustible adicional" },
      { name: "Do 17 P-1", desc: "Versión de reconocimiento táctico con motores BMW 132 radiales" }
    ],
    history: "Los Do 17 de la Legión Cóndor operaron desde bases en España en misiones de bombardeo y reconocimiento. Su velocidad les permitía frecuentemente evadir a los cazas republicanos, aunque sufrieron pérdidas ante los I-16."
  },
  {
    id: 32,
    name: "Heinkel He 111",
    image: "",
    designation: "Heinkel He 111 B-1 / B-2 / E-1",
    year: 1937, yearEnd: 1939,
    branch: "nacional",
    type: "bombardeo",
    typeLabel: "Bombardero medio",
    crew: 5,
    description: "El Heinkel He 111 fue el bombardero alemán más moderno empleado en la Guerra Civil. Bimotor con la característica cabina acristalada, representó un salto tecnológico respecto a los Ju 52 y Do 17 anteriores. Fue utilizado tanto en bombardeo táctico como estratégico.",
    engine: "2 × Junkers Jumo 211 Da V12, 1.000 cv cada uno (B-2) o 2 × Daimler-Benz DB 600Ga V12, 950 cv (E-1)",
    wingspan: "22,60 m", length: "16,40 m", height: "3,40 m",
    emptyWeight: "5.500 kg", maxWeight: "8.600 kg",
    maxSpeed: "370 km/h", range: "1.500 km", ceiling: "6.500 m",
    armament: "3 × MG 15 de 7,92 mm en posiciones defensivas (nariz, dorsal, ventral); hasta 2.000 kg de bombas",
    variants: [
      { name: "He 111 B-1", desc: "Versión inicial con Jumo 210 Da de 680 cv, primeras entregas a la Legión Cóndor" },
      { name: "He 111 B-2", desc: "Versión con Jumo 211 Da de 1.000 cv, mejor velocidad y capacidad de carga" },
      { name: "He 111 E-1", desc: "Versión con DB 600Ga de 950 cv y mayor capacidad de bombas, llegada en 1938" }
    ],
    history: "Los He 111 de la Legión Cóndor participaron en bombardeos estratégicos sobre ciudades republicanas, incluyendo la infraestructura industrial y los puertos. Su velocidad y armamento defensivo los hacían más resistentes que los anteriores bombarderos."
  },
  {
    id: 33,
    name: "Messerschmitt Bf 109",
    image: "",
    designation: "Messerschmitt Bf 109 B-1 / B-2 / C-1 / D-1",
    year: 1937, yearEnd: 1939,
    branch: "nacional",
    type: "caza",
    typeLabel: "Caza monoplano",
    crew: 1,
    description: "El Messerschmitt Bf 109 fue el caza más avanzado empleado en la Guerra Civil Española. Monoplano de ala baja con tren retráctil, representaba la nueva generación de cazas y superaba a todos los aviones republicanos en velocidad y trepada, incluido el Polikarpov I-16.",
    engine: "Junkers Jumo 210 Da V12, 680 cv (B-1/B-2) o Jumo 210 Ga, 730 cv (C-1) o Daimler-Benz DB 600Aa, 960 cv (D-1)",
    wingspan: "9,87 m", length: "8,80 m", height: "2,45 m",
    emptyWeight: "1.580 kg", maxWeight: "1.980 kg",
    maxSpeed: "470 km/h (D-1)", range: "440 km", ceiling: "8.200 m",
    armament: "2-3 × MG 17 de 7,92 mm (versión B); 4 × MG 17 (versión C); 2 × MG 17 + 1 × MG FF de 20 mm (versión D temprana)",
    variants: [
      { name: "Bf 109 B-1/B-2", desc: "Versión inicial con Jumo 210 Da/Ga de 680/730 cv y 2-3 MG 17, primera en combatir en España" },
      { name: "Bf 109 C-1", desc: "Versión con 4 × MG 17 y Jumo 210 Ga de 730 cv, mayor potencia de fuego" },
      { name: "Bf 109 D-1", desc: "Versión con DB 600Aa de 960 cv, la más potente en España, superior a todos los cazas republicanos" }
    ],
    history: "El Bf 109 llegó a España con la Legión Cóndor a finales de 1937 y cambió decisivamente la guerra aérea. En manos de pilotos experimentados como Werner Mölders, demostró una superioridad clara sobre el I-16 en velocidad y trepada, contribuyendo a la superioridad aérea nacional en 1938-39."
  },
  {
    id: 34,
    name: "Henschel Hs 123",
    image: "",
    designation: "Henschel Hs 123 A-1",
    year: 1937, yearEnd: 1939,
    branch: "nacional",
    type: "ataque",
    typeLabel: "Ataque a tierra / Buzo",
    crew: 1,
    description: "El Henschel Hs 123 fue un biplano de ataque a tierra alemán que demostró ser extraordinariamente efectivo en la Guerra Civil. Aunque de diseño aparentemente anticuado, su resistencia al daño, precisión en el bombardeo en picado y capacidad para operar desde aeródromos improvisados lo convirtieron en un arma temible.",
    engine: "BMW 132Dc radial, 880 cv",
    wingspan: "10,50 m", length: "8,33 m", height: "3,20 m",
    emptyWeight: "1.500 kg", maxWeight: "2.220 kg",
    maxSpeed: "341 km/h", range: "855 km", ceiling: "9.000 m",
    armament: "2 × MG 17 de 7,92 mm en el capó; hasta 450 kg de bombas (1 × 250 kg bajo el fuselaje + 4 × 50 kg bajo las alas)",
    variants: [
      { name: "Hs 123 A-1", desc: "Versión única de producción con BMW 132Dc de 880 cv, armamento fijo y soportes de bombas" }
    ],
    history: "Los Hs 123 de la Legión Cóndor fueron devastadores en misiones de apoyo cercano y bombardeo en picado sobre posiciones republicanas. Su precisión y resistencia al daño los hicieron muy apreciados, y demostraron que un biplano podía seguir siendo útil en combate moderno."
  },
  {
    id: 35,
    name: "Douglas DC-2",
    image: "",
    designation: "Douglas DC-2 / DC-2-142",
    year: 1934, yearEnd: 1939,
    branch: "republicana",
    type: "transporte",
    typeLabel: "Transporte",
    crew: 2,
    description: "El Douglas DC-2 fue un bimotor de transporte comercial adaptado al servicio militar durante la Guerra Civil. La República adquirió varios ejemplares de la línea comercial de LAPE (Líneas Aéreas Postales Españolas), utilizándolos para transporte de personal, evacuación sanitaria y misiones de enlace.",
    engine: "2 × Wright SGR-1820-F52 Cyclone radial, 750 cv cada uno",
    wingspan: "25,91 m", length: "18,89 m", height: "4,97 m",
    emptyWeight: "5.650 kg", maxWeight: "8.440 kg",
    maxSpeed: "325 km/h", range: "1.750 km", ceiling: "6.860 m",
    armament: "Ninguno estándar",
    variants: [
      { name: "DC-2-142", desc: "Versión estándar de transporte con Wright Cyclone de 750 cv, la principal en servicio español" }
    ],
    history: "Los DC-2 de LAPE fueron requisados por la República al estallar la guerra. Realizaron misiones de transporte de autoridades, evacuación de heridos y enlace entre frentes. Algunos lograron escapar a territorio francés al final del conflicto."
  }
];
