// ================================================
// data.js — Base de datos de aeronaves (1911-1939)
// ================================================
// CAMPO "image": Añadir la URL de la imagen aquí.
// Si está vacío, se mostrará un marcador de posición.

var aircraftData = [
  {
    id: 1,
    name: "Farman MF.7",
    image: "",
    designation: "Henri Farman MF.7 Longhorn",
    year: 1911, yearEnd: 1916,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Reconocimiento / Entrenamiento",
    crew: 2,
    description: "El Farman MF.7, apodado «Longhorn» por sus característicos patines de aterrizaje extendidos, fue la primera aeronave militar adquirida por España. En 1911, el Ejército compró tres ejemplares destinados al recién creado aeródromo de Cuatro Vientos, cerca de Madrid.",
    engine: "Renault 8B V8, 70 cv",
    wingspan: "15,90 m", length: "11,45 m", height: "3,40 m",
    emptyWeight: "480 kg", maxWeight: "700 kg",
    maxSpeed: "95 km/h", range: "250 km", ceiling: "3.800 m",
    armament: "Ninguno fijo; el observador podía portar armas ligeras",
    variants: [
      { name: "MF.7", desc: "Versión estándar con motor Renault 8B de 70 cv y patines curvados característicos" },
      { name: "MF.7bis", desc: "Variante mejorada con alerones modificados, tren de aterrizaje reforzado y refinamientos aerodinámicos menores" }
    ],
    history: "Los MF.7 de Cuatro Vientos fueron los caballos de batalla de la instrucción inicial. Aunque obsoletos al inicio de las operaciones en Marruecos, sirvieron como plataforma esencial para la primera generación de pilotos militares españoles."
  },
  {
    id: 2,
    name: "Nieuport IV",
    image: "",
    designation: "Nieuport IV-G / IV-M",
    year: 1912, yearEnd: 1916,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Reconocimiento / Entrenamiento",
    crew: 2,
    description: "El Nieuport IV fue uno de los primeros monoplanos en servicio militar español. Adquirido a partir de 1912, complementó a los Farmans en Cuatro Vientos. La variante IV-G era biplaza para reconocimiento y entrenamiento.",
    engine: "Gnome Omega 7 cilindros rotativo, 70 cv",
    wingspan: "9,20 m", length: "6,80 m", height: "2,60 m",
    emptyWeight: "340 kg", maxWeight: "560 kg",
    maxSpeed: "110 km/h", range: "200 km", ceiling: "3.500 m",
    armament: "Ninguno estándar",
    variants: [
      { name: "IV-G", desc: "Versión biplaza de reconocimiento y entrenamiento con Gnome de 70 cv y ala de cuerda ancha" },
      { name: "IV-M", desc: "Versión monoplaza con envergadura reducida para misiones de enlace y comunicaciones" }
    ],
    history: "Los Nieuport IV sirvieron junto a los biplanos Farman en las primeras escuadrillas. Su configuración de monoplano ofrecía mayor velocidad pero era más exigente de pilotar. Hacia 1915 fueron reemplazados por tipos más modernos."
  },
  {
    id: 3,
    name: "Farman MF.11",
    image: "",
    designation: "Henry Farman F.11 / MF.11bis",
    year: 1913, yearEnd: 1918,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Reconocimiento / Bombardeo ligero",
    crew: 2,
    description: "El Farman MF.11 fue la aeronave de combate principal durante las primeras operaciones militares españolas en Marruecos. Biplano propulsor con la barquilla montada delante del motor, ofrecía al observador un excelente campo de tiro frontal.",
    engine: "Renault 8Bb V8, 80 cv (posteriormente 8Bd de 100 cv)",
    wingspan: "16,15 m", length: "9,45 m", height: "3,20 m",
    emptyWeight: "530 kg", maxWeight: "830 kg",
    maxSpeed: "105 km/h", range: "300 km", ceiling: "4.000 m",
    armament: "1 × Hotchkiss M1914 de 7 mm en montaje flexible (observador); hasta 100 kg de bombas",
    variants: [
      { name: "MF.11 A2", desc: "Variante biplaza de reconocimiento con Renault de 80 cv, modelo estándar utilizado en Marruecos" },
      { name: "MF.11bis", desc: "Versión mejorada con Renault 8Bd de 100 cv, superficies de cola ampliadas y estructura reforzada" },
      { name: "MF.11 Bn2", desc: "Variante de bombardeo nocturno con soportes de bombas y depósitos auxiliares de combustible" }
    ],
    history: "El MF.11 fue la espina dorsal de la escuadrilla expedicionaria en Marruecos desde 1913. Realizó reconocimiento sobre el Rif, dirigió el tiro artillero y llevó a cabo los primeros bombardeos españoles con granadas improvisadas."
  },
  {
    id: 4,
    name: "Caudron G.3",
    image: "",
    designation: "Caudron G.3 A2 / D2 / E2",
    year: 1914, yearEnd: 1919,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Reconocimiento / Entrenamiento",
    crew: 2,
    description: "El Caudron G.3 fue uno de los aviones más versátiles del inventario militar español. Biplano de doble botalón con una corta barquilla para la tripulación, combinaba prestaciones razonables con excelente estabilidad y construcción robusta.",
    engine: "Le Rhône 9C 9 cilindros rotativo, 80 cv o Gnome Lambda, 80 cv",
    wingspan: "13,40 m", length: "6,40 m", height: "2,50 m",
    emptyWeight: "420 kg", maxWeight: "710 kg",
    maxSpeed: "106 km/h", range: "320 km", ceiling: "4.300 m",
    armament: "Ninguno estándar; el observador podía portar fusil o ametralladora ligera",
    variants: [
      { name: "G.3 A2", desc: "Variante biplaza de observación artillera y reconocimiento con puntos de montaje de cámara" },
      { name: "G.3 D2", desc: "Versión de entrenamiento con doble mando y controles duplicados" },
      { name: "G.3 E2", desc: "Variante de instrucción elemental con equipo simplificado y motor Le Rhône o Anzani" }
    ],
    history: "El G.3 se ganó una reputación de avión fiable y dócil, bien adaptado a las duras condiciones de los aeródromos marroquíes. Sirvió durante todo el período 1914-1919, pasando gradualmente de primera línea a entrenamiento."
  },
  {
    id: 5,
    name: "Farman F.40",
    image: "",
    designation: "Farman F.40 / F.41 / F.46",
    year: 1915, yearEnd: 1919,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Reconocimiento / Bombardeo",
    crew: 2,
    description: "El Farman F.40 supuso una mejora significativa respecto al MF.11, con un motor Renault de 130 cv y aerodinámica refinada. Biplano propulsor capaz de transportar una carga bélica considerable, se convirtió en uno de los principales tipos de combate durante el período central de la guerra del Rif.",
    engine: "Renault 8Fb V8, 130 cv",
    wingspan: "18,20 m", length: "9,60 m", height: "3,30 m",
    emptyWeight: "700 kg", maxWeight: "1.100 kg",
    maxSpeed: "128 km/h", range: "400 km", ceiling: "4.500 m",
    armament: "1 × Hotchkiss de 7 mm en montaje flexible; hasta 200 kg de bombas",
    variants: [
      { name: "F.40", desc: "Versión estándar biplaza de reconocimiento/bombardeo con Renault 8Fb de 130 cv" },
      { name: "F.41", desc: "Variante con barquilla revisada, mejor aerodinámica y mecanismo de liberación de bombas mejorado" },
      { name: "F.46", desc: "Conversión a entrenador con doble mando y equipo de bombardeo retirado" }
    ],
    history: "El F.40 proporcionó por primera vez a las tripulaciones españolas una capacidad ofensiva real. Desde los aeródromos marroquíes, realizó bombardeos sistemáticos sobre campamentos y posiciones rifeñas."
  },
  {
    id: 6,
    name: "Caudron G.4",
    image: "",
    designation: "Caudron G.4 A2 / B2 / E2",
    year: 1916, yearEnd: 1919,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Bimotor de Bombardeo / Reconocimiento",
    crew: 3,
    description: "El Caudron G.4 fue el primer bimotor militar español y representó un salto cualitativo importante. Basado en el exitoso G.3 pero ampliado con dos motores entre los dobles botalones, podía transportar una carga de bombas considerable a grandes distancias.",
    engine: "2 × Le Rhône 9C 9 cilindros rotativo, 80 cv cada uno o 2 × Anzani 10 cilindros radial, 100 cv cada uno",
    wingspan: "17,00 m", length: "7,25 m", height: "2,60 m",
    emptyWeight: "780 kg", maxWeight: "1.250 kg",
    maxSpeed: "121 km/h", range: "360 km", ceiling: "4.300 m",
    armament: "1-2 × Hotchkiss de 7 mm en montajes flexibles; hasta 300 kg de bombas",
    variants: [
      { name: "G.4 A2", desc: "Variante triplaza de reconocimiento de largo alcance con equipo fotográfico y combustible extra" },
      { name: "G.4 B2", desc: "Variante triplaza de bombardeo con soportes subalares y posición de bombardero en barquilla delantera" },
      { name: "G.4 E2", desc: "Entrenador bimotor con doble mando para conversión operativa" }
    ],
    history: "La llegada del G.4 dotó a la aviación española de una fuerza de bombardeo genuina. Sus motores dobles proporcionaban redundancia sobre el terreno hostil marroquí, aunque los motores rotativos requerían mantenimiento frecuente."
  },
  {
    id: 7,
    name: "Avro 504",
    image: "",
    designation: "Avro 504A / 504B / 504J / 504K",
    year: 1916, yearEnd: 1925,
    branch: "ejercito",
    type: "entrenamiento",
    typeLabel: "Entrenamiento",
    crew: 2,
    description: "El Avro 504 fue posiblemente el avión de entrenamiento más importante de su época y España fue una de las muchas naciones que lo adoptó. Se empleó principalmente como entrenador elemental e intermedio en Cuatro Vientos.",
    engine: "Gnome Lambda 7 cilindros rotativo, 80 cv o Gnome Monosoupape, 100 cv o Clerget 9Z, 110 cv",
    wingspan: "10,97 m", length: "8,97 m", height: "3,18 m",
    emptyWeight: "560 kg", maxWeight: "830 kg",
    maxSpeed: "130 km/h", range: "400 km", ceiling: "4.875 m",
    armament: "Ninguno en configuración de entrenamiento; algunas variantes podían portar bombas ligeras o Lewis",
    variants: [
      { name: "504A", desc: "Variante inicial con Gnome de 80 cv, usada en entrenamiento y tareas operativas limitadas" },
      { name: "504K", desc: "Entrenador universal con soporte de motor adaptable a diversos rotativos; variante más común" }
    ],
    history: "El Avro 504 fue la piedra angular de la instrucción de vuelo militar española. Sus características de manejo dóciles y construcción robusta lo hacían ideal para pilotos alumnos."
  },
  {
    id: 8,
    name: "FBA Type H",
    image: "",
    designation: "FBA Type H / Type C",
    year: 1917, yearEnd: 1925,
    branch: "armada",
    type: "hidroavion",
    typeLabel: "Hidroavión Naval",
    crew: 2,
    description: "El FBA Type H fue la primera aeronave operada por la recién creada Aeronáutica Naval en 1917. Estos compactos hidrocanoas propulsores fueron adquiridos para patrulla costera y reconocimiento desde bases navales españolas.",
    engine: "Hispano-Suiza 8Aa V8, 150 cv o 8Ab, 180 cv",
    wingspan: "13,30 m", length: "9,10 m", height: "3,20 m",
    emptyWeight: "780 kg", maxWeight: "1.150 kg",
    maxSpeed: "140 km/h", range: "450 km", ceiling: "4.200 m",
    armament: "1 × Vickers o Lewis de 7 mm en montaje flexible; hasta 100 kg de bombas o cargas de profundidad",
    variants: [
      { name: "Type A", desc: "Modelo de producción inicial con Hispano-Suiza 8Aa de 150 cv para patrulla costera" },
      { name: "Type H", desc: "Variante definitiva en servicio español con depósitos ampliados y equipamiento tropical para Marruecos" }
    ],
    history: "Los hidroaviones FBA fueron las aeronaves fundacionales de la aviación naval española. Operaron desde bases costeras realizando patrullas antisubmarinas, escolta de convoyes y reconocimiento marítimo."
  },
  {
    id: 9,
    name: "SPAD VII",
    image: "",
    designation: "Société Pour L'Aviation et ses Dérivés SPAD S.VII",
    year: 1917, yearEnd: 1924,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza monoplaza",
    crew: 1,
    description: "El SPAD VII fue el primer avión de caza verdadero de España, dotando a las escuadrillas de capacidad de combate moderna. Propulsado por el excelente motor V8 Hispano-Suiza, combinaba construcción robusta con buena velocidad y prestaciones en picado.",
    engine: "Hispano-Suiza 8Aa V8, 150 cv (posteriormente 8Ac, 180 cv)",
    wingspan: "7,82 m", length: "6,08 m", height: "2,20 m",
    emptyWeight: "500 kg", maxWeight: "720 kg",
    maxSpeed: "192 km/h", range: "360 km", ceiling: "5.800 m",
    armament: "1 × Vickers de 7,7 mm sincronizada a través del arco de la hélice",
    variants: [
      { name: "SPAD VII (150 cv)", desc: "Versión inicial con Hispano-Suiza 8Aa de 150 cv, estándar en las primeras entregas españolas" },
      { name: "SPAD VII (180 cv)", desc: "Versión mejorada con Hispano-Suiza 8Ac de 180 cv, mejor régimen de trepada y techo" }
    ],
    history: "El SPAD VII transformó la capacidad de caza española. En Marruecos demostró su valor en misiones de ametrallamiento y reconocimiento armado. Sus motores Hispano-Suiza facilitaban el mantenimiento al ser de origen español."
  },
  {
    id: 10,
    name: "Hanriot HD.1",
    image: "",
    designation: "Hanriot HD.1 / HD.2",
    year: 1918, yearEnd: 1928,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza monoplaza",
    crew: 1,
    description: "El Hanriot HD.1 fue un caza ágil y maniobrable que complementó a los SPAD VII en servicio español. Algunos pilotos lo preferían por su superior maniobrabilidad y manejo más ligero en altitud. Su motor rotativo Le Rhône le confería una respuesta característica.",
    engine: "Le Rhône 9J 9 cilindros rotativo, 110 cv",
    wingspan: "8,70 m", length: "5,85 m", height: "2,94 m",
    emptyWeight: "415 kg", maxWeight: "620 kg",
    maxSpeed: "183 km/h", range: "300 km", ceiling: "6.000 m",
    armament: "1 × Vickers de 7,7 mm sincronizada (algunos ejemplares españoles con 2 × Vickers)",
    variants: [
      { name: "HD.1", desc: "Caza terrestre estándar con Le Rhône 9J de 110 cv y una Vickers" },
      { name: "HD.2", desc: "Conversión a caza con flotadores para uso naval con pontones y fuselaje reforzado" }
    ],
    history: "Los HD.1 españoles sirvieron principalmente en el teatro marroquí, donde su maniobrabilidad era valiosa para misiones de ataque a baja cota. El tipo continuó en servicio hasta bien entrada la década de 1920."
  },
  {
    id: 11,
    name: "Breguet XIV",
    image: "",
    designation: "Breguet XIV A2 / B2",
    year: 1918, yearEnd: 1930,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Bombardeo / Reconocimiento",
    crew: 2,
    description: "El Breguet XIV fue uno de los mejores biplazas militares de la Primera Guerra Mundial. Su adquisición por España representó un salto cualitativo: con su potente motor Renault V12 y carga bélica sustancial, superaba a muchos cazas de la época en velocidad.",
    engine: "Renault 12Fcx V12, 300 cv o 12Fe, 320 cv",
    wingspan: "14,36 m", length: "8,87 m", height: "3,30 m",
    emptyWeight: "1.010 kg", maxWeight: "1.770 kg",
    maxSpeed: "175 km/h", range: "700 km", ceiling: "5.800 m",
    armament: "1 × Vickers de 7,7 mm fija frontal; 2 × Lewis de 7,7 mm en montaje flexible; hasta 460 kg de bombas (B2)",
    variants: [
      { name: "XIV A2", desc: "Variante biplaza de reconocimiento/observación con instalación fotográfica y radiotelegrafía" },
      { name: "XIV B2", desc: "Bombardeo diurno con soportes internos y externos, posición de bombardero y armamento defensivo completo" },
      { name: "XIV T", desc: "Conversión de transporte de posguerra con cabina cerrada para 4 pasajeros o carga" }
    ],
    history: "El Breguet XIV se convirtió en el avión de combate más importante en servicio español al final de la década de 1910. En Marruecos podía atacar objetivos en el interior del Rif y regresar con seguridad. Fue la espina dorsal de los escuadrones de bombardeo hasta la llegada del Breguet XIX."
  },
  {
    id: 12,
    name: "De Havilland DH.9",
    image: "",
    designation: "Airco DH.9 / DH.9A",
    year: 1920, yearEnd: 1930,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Bombardeo diurno / Reconocimiento",
    crew: 2,
    description: "El De Havilland DH.9 fue un bombardero diurno de gran capacidad que entró en servicio español en 1920. Diseñado como sucesor del DH.4, ofrecía mejores prestaciones y mayor carga de bombas. Fue ampliamente utilizado en las operaciones del Rif.",
    engine: "Siddeley Puma I6, 230 cv o Liberty 12 V12, 400 cv (DH.9A)",
    wingspan: "12,92 m", length: "9,27 m", height: "3,05 m",
    emptyWeight: "1.010 kg", maxWeight: "1.725 kg",
    maxSpeed: "170 km/h", range: "680 km", ceiling: "5.100 m",
    armament: "1-2 × Vickers de 7,7 mm fija; 1-2 × Lewis en anillo Scarff; hasta 210 kg de bombas",
    variants: [
      { name: "DH.9", desc: "Versión estándar con Siddeley Puma de 230 cv, utilizada en las operaciones del Rif" },
      { name: "DH.9A", desc: "Versión mejorada con Liberty 12 de 400 cv, mayor autonomía y carga, algunas construidas por CASA" }
    ],
    history: "Los DH.9 españoles participaron intensamente en las campañas de Marruecos durante la década de 1920, realizando bombardeo táctico y reconocimiento de largo alcance. Su autonomía los hacía especialmente valiosos sobre el terreno marroquí."
  },
  {
    id: 13,
    name: "Bristol F.2B Fighter",
    image: "",
    designation: "Bristol F.2B Fighter",
    year: 1920, yearEnd: 1931,
    branch: "ejercito",
    type: "reconocimiento",
    typeLabel: "Caza / Reconocimiento",
    crew: 2,
    description: "El Bristol F.2B Fighter fue uno de los mejores biplazas de la Primera Guerra Mundial y sirvió en España como avión de caza y reconocimiento. Su combinación de velocidad, maniobrabilidad y armamento defensivo lo hacía formidable incluso frente a cazas monoplazas.",
    engine: "Rolls-Royce Falcon III V12, 275 cv",
    wingspan: "11,96 m", length: "7,87 m", height: "2,97 m",
    emptyWeight: "975 kg", maxWeight: "1.475 kg",
    maxSpeed: "198 km/h", range: "460 km", ceiling: "5.945 m",
    armament: "1 × Vickers de 7,7 mm fija sincronizada; 1-2 × Lewis de 7,7 mm en montaje Scarff (observador)",
    variants: [
      { name: "F.2B (Falcon III)", desc: "Variante estándar con Rolls-Royce Falcon III de 275 cv, principal versión en servicio español" }
    ],
    history: "Los Bristol Fighter españoles operaron en Marruecos como escolta de bombardeo y reconocimiento armado. Su versatilidad los mantuvo en servicio hasta bien entrada la década de 1930."
  },
  {
    id: 14,
    name: "Nieuport 24/27",
    image: "",
    designation: "Nieuport 24 / 24bis / 27",
    year: 1921, yearEnd: 1930,
    branch: "ejercito",
    type: "caza",
    typeLabel: "Caza monoplaza",
    crew: 1,
    description: "Los Nieuport 24 y 27 fueron los últimos cazas de la línea Nieuport en servir con la aviación militar española. Evolución de los exitosos Nieuport 11 y 17, ofrecían mejor rendimiento que los SPAD VII en maniobrabilidad a baja cota, aunque eran más frágiles.",
    engine: "Le Rhône 9Jb 9 cilindros rotativo, 120 cv (Ni.24) o Gnome Monosoupape 9N, 150 cv (Ni.27)",
    wingspan: "8,21 m", length: "5,78 m", height: "2,40 m",
    emptyWeight: "385 kg", maxWeight: "580 kg",
    maxSpeed: "185 km/h", range: "300 km", ceiling: "5.500 m",
    armament: "1 × Vickers de 7,7 mm sincronizada o 2 × Lewis sobre el ala superior (algunos Ni.24)",
    variants: [
      { name: "Nieuport 24", desc: "Caza con Le Rhône de 120 cv y cola rediseñada, algunos con armamento sobre el ala" },
      { name: "Nieuport 27", desc: "Versión final de producción con Gnome Monosoupape de 150 cv y tren de aterrizaje revisado" }
    ],
    history: "Los Nieuport 24/27 sirvieron como cazas de primera línea en Marruecos, complementando y posteriormente reemplazando a los SPAD VII y Hanriot HD.1 más antiguos."
  },
  {
    id: 15,
    name: "Breguet XIX",
    image: "",
    designation: "Breguet XIX A2 / B2 / G.R. (Grand Raid)",
    year: 1922, yearEnd: 1937,
    branch: "ejercito",
    type: "bombardeo",
    typeLabel: "Bombardeo / Reconocimiento",
    crew: 2,
    description: "El Breguet XIX fue el avión estándar de la aviación militar española durante más de una década.
